import { MissionsStatus } from '../enums/MissionsStatus.mjs';

export interface MissionList {
	missionId: number;
	status: MissionsStatus;
}

export enum MissionID {
	INIT,
	// PAPY
	PAPY_JOE_FISH,
	PAPY_JOE_DOG,
	PAPY_JOE_KILGOU,
	PAPY_JOE_KILWLF,
	PAPY_JOE_FFLOW,
	PAPY_JOE_KBOOK,
	PAPY_JOE_MSG,
	PAPY_JOE_LETTRE,
	PAPY_JOE_KILGLU,
	PAPY_JOE_KILGNT,
	PAPY_JOE_KILCOQ,
	// BAO BOB
	BAO_BOB_KILPIR,
	BAO_BOB_TROC,
	BAO_BOB_KILKSK,
	BAO_BOB_KILANG,
	BAO_BOB_BIGPCH,
	BAO_BOB_RALLY1,
	BAO_BOB_RALLY2,
	BAO_BOB_RALLY3,
	BAO_BOB_RALLY4,
	BAO_BOB_TOUR,
	// DIAN
	DIAN_KSWIM,
	DIAN_RIVALS,
	DIAN_KFOOD,
	DIAN_POISON,
	// SHAMAN MOU
	SHAMAN_INIT1,
	SHAMAN_INIT2,
	SHAMAN_BURN,
	SHAMAN_BARBEC,
	SHAMAN_JOKE,
	SHAMAN_DEFEND,
	SHAMAN_SHIPMT,
	SHAMAN_SALES,
	SHAMAN_RITUAL,
	SHAMAN_HIERO,
	SHAMAN_PIGEON,
	// GARDIEN DE LA FORET
	GARDIEN_UNMUTE,
	GARDIEN_ORCHID,
	GARDIEN_LICENS,
	GARDIEN_KING,
	GARDIEN_WISHES,
	GARDIEN_NEWPLT,
	GARDIEN_GSHOP,
	// NICOLAS MULOT
	HULOT_SEQACT,
	HULOT_TOXIC,
	HULOT_MAP,
	HULOT_HUCURE,
	HULOT_BCKPCK
}
