import { Comparator, ConditionEnum, Operator } from '../enums/Parser.mjs';
import { PlaceEnum } from '../enums/PlaceEnum.mjs';
import { DayEnum } from '../enums/dayEnum.mjs';
import { Scenario } from '../enums/Scenario.mjs';

// Choisit le type de value en fonction de l'enum utilisée
export type Condition = {
	[Operator.AND]?: [Condition, Condition, ...Condition[]];
	[Operator.OR]?: [Condition, Condition, ...Condition[]];
	[Operator.NOT]?: Condition;
	[ConditionEnum.MINLEVEL]?: number;
	[ConditionEnum.MAXLEVEL]?: number;
	[ConditionEnum.FINISHED_MISSION]?: number;
	[ConditionEnum.SKILL]?: number;
	[ConditionEnum.POSSESS_OBJECT]?: number;
	[ConditionEnum.COLLEC]?: number;
	[ConditionEnum.STATUS]?: number;
	[ConditionEnum.RANDOM]?: number;
	[ConditionEnum.DINOZ_LIFE]?: [Comparator, number];
	[ConditionEnum.SCENARIO]?: [Scenario, number, '+' | '-' | '='];
	[ConditionEnum.CURRENT_MISSION]?: number;
	[ConditionEnum.POSSESS_INGREDIENT]?: string;
	[ConditionEnum.ACTIVE]?: boolean;
	[ConditionEnum.PLAYER_EPIC]?: string;
	[ConditionEnum.HOUR]?: number;
	[ConditionEnum.TAG]?: string;
	[ConditionEnum.GVAR]?: string;
	[ConditionEnum.EVENT]?: string;
	[ConditionEnum.CLANACT]?: string;
	[ConditionEnum.SWAIT]?: string;
	[ConditionEnum.RACE]?: string;
	[ConditionEnum.EQUIP]?: number;
	[ConditionEnum.TIME]?: number;
	[ConditionEnum.UTIME]?: string;
	[ConditionEnum.GOTO]?: string;
	[ConditionEnum.TALKTO]?: string;
	[ConditionEnum.FINISH_MISSION]?: string;
	[ConditionEnum.KILL]?: string;
	[ConditionEnum.DO]?: string;
	[ConditionEnum.HIDE_PLACE]?: string;
	[ConditionEnum.PLACE_IS]?: PlaceEnum;
	[ConditionEnum.OVERWRITE]?: string;
	[ConditionEnum.LAUNCH_FIGHT]?: string;
	[ConditionEnum.DAY]?: DayEnum;
	[ConditionEnum.WEEK_PLACE]?: boolean;
};
