stages:
  - build
  - test
  - update_release

before_script:
  - "node --version"
  - "yarn --version"
  - yarn install

container-build:
  stage: build
  image: "demurgos/node:2024.2"
  cache:
    - key:
        files:
          - "yarn.lock"
      paths:
        - ".yarn/cache/"
  artifacts:
    paths:
      - node_modules/
  script:
    - yarn build:gitlab
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

front-lint:
  stage: test
  image: "demurgos/node:2024.2"
  needs: [container-build]
  script:
    - yarn lint:test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

update_release_hash:
  stage: update_release
  image: alpine:latest
  before_script:
    - apk add --no-cache git jq curl
  script:
    - git clone https://oauth2:${TARGET_REPO_TOKEN}@gitlab.com:eternaltwin/config.git
    - cd target-repo
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - |
      jq --arg hash "$CI_COMMIT_SHA" \
         '.release = $hash \
         release.json > release.json.tmp
    - mv release.json.tmp release.json
    - git add release.json
    - git commit -m "[DRPG] Staging $CI_COMMIT_SHA [skip ci]"
    - git push origin main
  
  only:
    - main
  when: on_success

#back-coverage:
#  stage: test
#  image: "demurgos/node:2022.1"
#  needs: [container-build]
#  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
#  variables:
#    CARGO_HOME: ".cargo"
#    RUSTFLAGS: "-C target-feature=-crt-static"
#  cache:
#    paths:
#      - "ed-be/coverage/"
#      - junit.xml
#  script:
#    - yarn test:ci
#  dependencies:
#    - container-build
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#    - if: '$CI_COMMIT_BRANCH == "develop"'
#  artifacts:
#    when: always
#    reports:
#      junit:
#        - ed-be/junit.xml
#      coverage_report:
#        coverage_format: cobertura
#        path: ed-be/coverage/cobertura-coverage.xml
