export interface PlayerEdit {
	customText?: string;
	hasImported?: boolean;
	rewards?: string[];
	items?: string[];
	ingredients?: string[];
	quests?: string[];
	selectedItem?: number;
	selectedIngredient?: number;
	itemQuantity: number;
	ingredientQuantity: number;
	epicOperation?: string;
	itemOperation?: string;
	ingOperation?: string;
	selectedQuestId?: number;
	progressionQuest?: number;
	questOperation?: string;
	money?: number;
	operation?: string;
	quetzuBought?: number;
	dailyGridRewards?: number;
	leader?: boolean;
	engineer?: boolean;
	cooker?: boolean;
	shopKeeper?: boolean;
	merchant?: boolean;
	priest?: boolean;
	teacher?: boolean;
	messie?: boolean;
	matelasseur?: boolean;
	role?: 'admin' | 'beta' | 'player';
}
