import { ItemFiche } from '../models';

export const listOfAllItems: Array<ItemFiche> = [
	{
		itemId: 1,
		name: 'irma',
		canBeEquipped: false,
		canBeUsedNow: true,
		quantity: 0,
		maxQuantity: 80,
		price: 450,
	},
	{
		itemId: 2,
		name: 'angel',
		canBeEquipped: false,
		canBeUsedNow: true,
		quantity: 0,
		maxQuantity: 8,
		price: 1000,
	},
	{
		itemId: 3,
		name: 'burger',
		canBeEquipped: true,
		canBeUsedNow: true,
		quantity: 0,
		maxQuantity: 24,
		price: 350,
	},
	{
		itemId: 4,
		name: 'hotpan',
		canBeEquipped: false,
		canBeUsedNow: true,
		quantity: 0,
		maxQuantity: 8,
		price: 3000,
	},
	{
		itemId: 5,
		name: 'tartev',
		canBeEquipped: false,
		canBeUsedNow: true,
		quantity: 0,
		maxQuantity: 16,
		price: 1000,
	},
	{
		itemId: 6,
		name: 'ration',
		canBeEquipped: true,
		canBeUsedNow: false,
		quantity: 0,
		maxQuantity: 8,
		price: 500,
	},
	{
		itemId: 7,
		name: 'surviv',
		canBeEquipped: true,
		canBeUsedNow: false,
		quantity: 0,
		maxQuantity: 8,
		price: 500, // To double check
	},
	{
		itemId: 7,
		name: 'mergz',
		canBeEquipped: true,
		canBeUsedNow: false,
		quantity: 0,
		maxQuantity: 4,
		price: 500, // To double check
	},
	{
		itemId: 8,
		name: 'fruit',
		canBeEquipped: false,
		canBeUsedNow: true,
		quantity: 0,
		maxQuantity: 8,
		price: 500, // To double check
	},
	{
		itemId: 10,
		name: 'hlmsos',
		canBeEquipped: true,
		canBeUsedNow: false,
		quantity: 0,
		maxQuantity: 12,
		price: 150,
	},
	{
		itemId: 11,
		name: 'ppoiv',
		canBeEquipped: true,
		canBeUsedNow: false,
		quantity: 0,
		maxQuantity: 12,
		price: 150,
	},
	{
		itemId: 12,
		name: 'zippo',
		canBeEquipped: true,
		canBeUsedNow: false,
		quantity: 0,
		maxQuantity: 12,
		price: 150,
	},
	{
		itemId: 12,
		name: 'flamch',
		canBeEquipped: true,
		canBeUsedNow: false,
		quantity: 0,
		maxQuantity: 80,
		price: 150,
	},
	{
		itemId: 13,
		name: 'combi',
		canBeEquipped: true,
		canBeUsedNow: false,
		quantity: 0,
		maxQuantity: 12,
		price: 150,
	},
];
