export enum missionsList {
	INIT,
	// PAPY
	PAPY_JOE_FISH,
	PAPY_JOE_DOG,
	PAPY_JOE_KILGOU,
	PAPY_JOE_KILWLF,
	PAPY_JOE_FFLOW,
	PAPY_JOE_KBOOK,
	PAPY_JOE_MSG,
	PAPY_JOE_LETTRE,
	PAPY_JOE_KILGLU,
	PAPY_JOE_KILGNT,
	PAPY_JOE_KILCOQ,
	// BAO BOB
	BAO_BOB_KILPIR,
	BAO_BOB_TROC,
	BAO_BOB_KILKSK,
	BAO_BOB_KILANG,
	BAO_BOB_BIGPCH,
	BAO_BOB_RALLY1,
	BAO_BOB_RALLY2,
	BAO_BOB_RALLY3,
	BAO_BOB_RALLY4,
	BAO_BOB_TOUR
}
