import { getImgURL } from '../../../mixin/mixin';

export enum EmotesTwinoidV2Enum {
	TWINOIDV2_ARROW = 'arrow_v2',
	TWINOIDV2_CALIM = 'calim',
	TWINOIDV2_CHART = 'chart_v2',
	TWINOIDV2_CONFUSED = 'confused_v2',
	TWINOIDV2_COOL = 'cool_v2',
	TWINOIDV2_CROSS = 'cross_v2',
	TWINOIDV2_CRY = 'cry_v2',
	TWINOIDV2_CRYLOT = 'crylot',
	TWINOIDV2_CUTE = 'cute',
	TWINOIDV2_DONTCARE = 'dontcare_v2',
	TWINOIDV2_DROWL = 'drowl',
	TWINOIDV2_EEK = 'eek_v2',
	TWINOIDV2_EVIL = 'evil_v2',
	TWINOIDV2_EXCLAIM = 'exclaim_v2',
	TWINOIDV2_FACEPALM = 'facepalm',
	TWINOIDV2_FEAR = 'fear',
	TWINOIDV2_GETOUT = 'getout',
	TWINOIDV2_HAPPY = 'happy_v2',
	TWINOIDV2_HAPPY2 = 'happy2',
	TWINOIDV2_HUH = 'huh_v2',
	TWINOIDV2_IDEA = 'idea_v2',
	TWINOIDV2_KEEPCOOL = 'keepcool_v2',
	TWINOIDV2_LOL = 'lol_v2',
	TWINOIDV2_LOOKUP = 'lookup',
	TWINOIDV2_MAD = 'mad_v2',
	TWINOIDV2_NOOO = 'nooo_v2',
	TWINOIDV2_OMG = 'omg',
	TWINOIDV2_PSYCHO = 'psycho',
	TWINOIDV2_PUKE = 'puke',
	TWINOIDV2_QUESTION = 'question_v2',
	TWINOIDV2_RAZZ = 'razz',
	TWINOIDV2_REDFACE = 'redface',
	TWINOIDV2_SAD = 'sad_v2',
	TWINOIDV2_SADIST = 'sadist',
	TWINOIDV2_SMILE = 'smile_v2',
	TWINOIDV2_STOP = 'stop',
	TWINOIDV2_SURPRISED = 'surprised_v2',
	TWINOIDV2_TWINOID = 'twinoid',
	TWINOIDV2_WINK = 'wink_v2',
	TWINOIDV2_WINK2 = 'wink2_v2',
	TWINOIDV2_YEAH = 'yeah_v2',
	TWINOIDV2_ZOMBIE = 'zombie'
}

export const EmotesTwinoidV2Aliases: { [index: string]: string } = {
	['arrow_v2']: EmotesTwinoidV2Enum.TWINOIDV2_ARROW,
	['calim']: EmotesTwinoidV2Enum.TWINOIDV2_CALIM,
	['chart_v2']: EmotesTwinoidV2Enum.TWINOIDV2_CHART,
	['confused_v2']: EmotesTwinoidV2Enum.TWINOIDV2_CONFUSED,
	['cool_v2']: EmotesTwinoidV2Enum.TWINOIDV2_COOL,
	['cross_v2']: EmotesTwinoidV2Enum.TWINOIDV2_CROSS,
	['cry_v2']: EmotesTwinoidV2Enum.TWINOIDV2_CRY,
	['crylot']: EmotesTwinoidV2Enum.TWINOIDV2_CRYLOT,
	['cute']: EmotesTwinoidV2Enum.TWINOIDV2_CUTE,
	['dontcare_v2']: EmotesTwinoidV2Enum.TWINOIDV2_DONTCARE,
	['drowl']: EmotesTwinoidV2Enum.TWINOIDV2_DROWL,
	['eek_v2']: EmotesTwinoidV2Enum.TWINOIDV2_EEK,
	['evil_v2']: EmotesTwinoidV2Enum.TWINOIDV2_EVIL,
	['exclaim_v2']: EmotesTwinoidV2Enum.TWINOIDV2_EXCLAIM,
	['facepalm']: EmotesTwinoidV2Enum.TWINOIDV2_FACEPALM,
	['fear']: EmotesTwinoidV2Enum.TWINOIDV2_FEAR,
	['getout']: EmotesTwinoidV2Enum.TWINOIDV2_GETOUT,
	['happy_v2']: EmotesTwinoidV2Enum.TWINOIDV2_HAPPY,
	['happy2']: EmotesTwinoidV2Enum.TWINOIDV2_HAPPY2,
	['huh_v2']: EmotesTwinoidV2Enum.TWINOIDV2_HUH,
	['idea_v2']: EmotesTwinoidV2Enum.TWINOIDV2_IDEA,
	['keepcool_v2']: EmotesTwinoidV2Enum.TWINOIDV2_KEEPCOOL,
	['lol_v2']: EmotesTwinoidV2Enum.TWINOIDV2_LOL,
	['lookup']: EmotesTwinoidV2Enum.TWINOIDV2_LOOKUP,
	['mad_v2']: EmotesTwinoidV2Enum.TWINOIDV2_MAD,
	['nooo_v2']: EmotesTwinoidV2Enum.TWINOIDV2_NOOO,
	['omg']: EmotesTwinoidV2Enum.TWINOIDV2_OMG,
	['psycho']: EmotesTwinoidV2Enum.TWINOIDV2_PSYCHO,
	['puke']: EmotesTwinoidV2Enum.TWINOIDV2_PUKE,
	['question_v2']: EmotesTwinoidV2Enum.TWINOIDV2_QUESTION,
	['razz']: EmotesTwinoidV2Enum.TWINOIDV2_RAZZ,
	['redface']: EmotesTwinoidV2Enum.TWINOIDV2_REDFACE,
	['sad_v2']: EmotesTwinoidV2Enum.TWINOIDV2_SAD,
	['sadist']: EmotesTwinoidV2Enum.TWINOIDV2_SADIST,
	['smile_v2']: EmotesTwinoidV2Enum.TWINOIDV2_SMILE,
	['stop']: EmotesTwinoidV2Enum.TWINOIDV2_STOP,
	['surprised_v2']: EmotesTwinoidV2Enum.TWINOIDV2_SURPRISED,
	['twinoid']: EmotesTwinoidV2Enum.TWINOIDV2_TWINOID,
	['wink_v2']: EmotesTwinoidV2Enum.TWINOIDV2_WINK,
	['wink2_v2']: EmotesTwinoidV2Enum.TWINOIDV2_WINK2,
	['yeah_v2']: EmotesTwinoidV2Enum.TWINOIDV2_YEAH,
	['zombie']: EmotesTwinoidV2Enum.TWINOIDV2_ZOMBIE
};

export const EmotesTwinoidV2Icons: { [index: string]: string } = {
	[EmotesTwinoidV2Enum.TWINOIDV2_ARROW]: getImgURL('emotes/twinoidv2', 'arrow'),
	[EmotesTwinoidV2Enum.TWINOIDV2_CALIM]: getImgURL('emotes/twinoidv2', 'calim'),
	[EmotesTwinoidV2Enum.TWINOIDV2_CHART]: getImgURL('emotes/twinoidv2', 'chart'),
	[EmotesTwinoidV2Enum.TWINOIDV2_CONFUSED]: getImgURL('emotes/twinoidv2', 'confused'),
	[EmotesTwinoidV2Enum.TWINOIDV2_COOL]: getImgURL('emotes/twinoidv2', 'cool'),
	[EmotesTwinoidV2Enum.TWINOIDV2_CROSS]: getImgURL('emotes/twinoidv2', 'cross'),
	[EmotesTwinoidV2Enum.TWINOIDV2_CRY]: getImgURL('emotes/twinoidv2', 'cry'),
	[EmotesTwinoidV2Enum.TWINOIDV2_CRYLOT]: getImgURL('emotes/twinoidv2', 'crylot'),
	[EmotesTwinoidV2Enum.TWINOIDV2_CUTE]: getImgURL('emotes/twinoidv2', 'cute'),
	[EmotesTwinoidV2Enum.TWINOIDV2_DONTCARE]: getImgURL('emotes/twinoidv2', 'dontcare'),
	[EmotesTwinoidV2Enum.TWINOIDV2_DROWL]: getImgURL('emotes/twinoidv2', 'drowl'),
	[EmotesTwinoidV2Enum.TWINOIDV2_EEK]: getImgURL('emotes/twinoidv2', 'eek'),
	[EmotesTwinoidV2Enum.TWINOIDV2_EVIL]: getImgURL('emotes/twinoidv2', 'evil'),
	[EmotesTwinoidV2Enum.TWINOIDV2_EXCLAIM]: getImgURL('emotes/twinoidv2', 'exclaim'),
	[EmotesTwinoidV2Enum.TWINOIDV2_FACEPALM]: getImgURL('emotes/twinoidv2', 'facepalm'),
	[EmotesTwinoidV2Enum.TWINOIDV2_FEAR]: getImgURL('emotes/twinoidv2', 'fear'),
	[EmotesTwinoidV2Enum.TWINOIDV2_GETOUT]: getImgURL('emotes/twinoidv2', 'getout'),
	[EmotesTwinoidV2Enum.TWINOIDV2_HAPPY]: getImgURL('emotes/twinoidv2', 'happy'),
	[EmotesTwinoidV2Enum.TWINOIDV2_HAPPY2]: getImgURL('emotes/twinoidv2', 'happy2'),
	[EmotesTwinoidV2Enum.TWINOIDV2_HUH]: getImgURL('emotes/twinoidv2', 'huh'),
	[EmotesTwinoidV2Enum.TWINOIDV2_IDEA]: getImgURL('emotes/twinoidv2', 'idea'),
	[EmotesTwinoidV2Enum.TWINOIDV2_KEEPCOOL]: getImgURL('emotes/twinoidv2', 'keepcool'),
	[EmotesTwinoidV2Enum.TWINOIDV2_LOL]: getImgURL('emotes/twinoidv2', 'lol'),
	[EmotesTwinoidV2Enum.TWINOIDV2_LOOKUP]: getImgURL('emotes/twinoidv2', 'lookup'),
	[EmotesTwinoidV2Enum.TWINOIDV2_MAD]: getImgURL('emotes/twinoidv2', 'mad'),
	[EmotesTwinoidV2Enum.TWINOIDV2_NOOO]: getImgURL('emotes/twinoidv2', 'nooo'),
	[EmotesTwinoidV2Enum.TWINOIDV2_OMG]: getImgURL('emotes/twinoidv2', 'omg'),
	[EmotesTwinoidV2Enum.TWINOIDV2_PSYCHO]: getImgURL('emotes/twinoidv2', 'psycho'),
	[EmotesTwinoidV2Enum.TWINOIDV2_PUKE]: getImgURL('emotes/twinoidv2', 'puke'),
	[EmotesTwinoidV2Enum.TWINOIDV2_QUESTION]: getImgURL('emotes/twinoidv2', 'question'),
	[EmotesTwinoidV2Enum.TWINOIDV2_RAZZ]: getImgURL('emotes/twinoidv2', 'razz'),
	[EmotesTwinoidV2Enum.TWINOIDV2_REDFACE]: getImgURL('emotes/twinoidv2', 'redface'),
	[EmotesTwinoidV2Enum.TWINOIDV2_SAD]: getImgURL('emotes/twinoidv2', 'sad'),
	[EmotesTwinoidV2Enum.TWINOIDV2_SADIST]: getImgURL('emotes/twinoidv2', 'sadist'),
	[EmotesTwinoidV2Enum.TWINOIDV2_SMILE]: getImgURL('emotes/twinoidv2', 'smile'),
	[EmotesTwinoidV2Enum.TWINOIDV2_STOP]: getImgURL('emotes/twinoidv2', 'stop'),
	[EmotesTwinoidV2Enum.TWINOIDV2_SURPRISED]: getImgURL('emotes/twinoidv2', 'surprised'),
	[EmotesTwinoidV2Enum.TWINOIDV2_TWINOID]: getImgURL('emotes/twinoidv2', 'twinoid'),
	[EmotesTwinoidV2Enum.TWINOIDV2_WINK]: getImgURL('emotes/twinoidv2', 'wink'),
	[EmotesTwinoidV2Enum.TWINOIDV2_WINK2]: getImgURL('emotes/twinoidv2', 'wink2'),
	[EmotesTwinoidV2Enum.TWINOIDV2_YEAH]: getImgURL('emotes/twinoidv2', 'yeah'),
	[EmotesTwinoidV2Enum.TWINOIDV2_ZOMBIE]: getImgURL('emotes/twinoidv2', 'zombie')
};
