import { getImgURL } from '../../../mixin/mixin';

export enum EmotesTwinoidV1Enum {
	TWINOIDV1_ARROW = 'arrow',
	TWINOIDV1_CHART = 'chart',
	TWINOIDV1_CONFUSED = 'confused',
	TWINOIDV1_COOL = 'cool',
	TWINOIDV1_CROSS = 'cross',
	TWINOIDV1_CRY = 'cry',
	TWINOIDV1_DONTCARE = 'dontcare',
	TWINOIDV1_EEK = 'eek',
	TWINOIDV1_EVIL = 'evil',
	TWINOIDV1_EXCLAIM = 'exclaim',
	TWINOIDV1_HAPPY = 'happy',
	TWINOIDV1_HUH = 'huh',
	TWINOIDV1_IDEA = 'idea',
	TWINOIDV1_KEEPCOOL = 'keepcool',
	TWINOIDV1_LOL = 'lol',
	TWINOIDV1_MAD = 'mad',
	TWINOIDV1_NOOO = 'nooo',
	TWINOIDV1_QUESTION = 'question',
	TWINOIDV1_SAD = 'sad',
	TWINOIDV1_SMILE = 'smile',
	TWINOIDV1_SURPRISED = 'surprised',
	TWINOIDV1_TWISTED = 'twisted',
	TWINOIDV1_WINK = 'wink',
	TWINOIDV1_WINK2 = 'wink2',
	TWINOIDV1_YEAH = 'yeah'
}

export const EmotesTwinoidV1Aliases: { [index: string]: string } = {
	['arrow']: EmotesTwinoidV1Enum.TWINOIDV1_ARROW,
	['chart']: EmotesTwinoidV1Enum.TWINOIDV1_CHART,
	['confused']: EmotesTwinoidV1Enum.TWINOIDV1_CONFUSED,
	['cool']: EmotesTwinoidV1Enum.TWINOIDV1_COOL,
	['cross']: EmotesTwinoidV1Enum.TWINOIDV1_CROSS,
	['cry']: EmotesTwinoidV1Enum.TWINOIDV1_CRY,
	['dontcare']: EmotesTwinoidV1Enum.TWINOIDV1_DONTCARE,
	['eek']: EmotesTwinoidV1Enum.TWINOIDV1_EEK,
	['evil']: EmotesTwinoidV1Enum.TWINOIDV1_EVIL,
	['exclaim']: EmotesTwinoidV1Enum.TWINOIDV1_EXCLAIM,
	['happy']: EmotesTwinoidV1Enum.TWINOIDV1_HAPPY,
	['huh']: EmotesTwinoidV1Enum.TWINOIDV1_HUH,
	['idea']: EmotesTwinoidV1Enum.TWINOIDV1_IDEA,
	['keepcool']: EmotesTwinoidV1Enum.TWINOIDV1_KEEPCOOL,
	['lol']: EmotesTwinoidV1Enum.TWINOIDV1_LOL,
	['mad']: EmotesTwinoidV1Enum.TWINOIDV1_MAD,
	['nooo']: EmotesTwinoidV1Enum.TWINOIDV1_NOOO,
	['question']: EmotesTwinoidV1Enum.TWINOIDV1_QUESTION,
	['sad']: EmotesTwinoidV1Enum.TWINOIDV1_SAD,
	['smile']: EmotesTwinoidV1Enum.TWINOIDV1_SMILE,
	['surprised']: EmotesTwinoidV1Enum.TWINOIDV1_SURPRISED,
	['twisted']: EmotesTwinoidV1Enum.TWINOIDV1_TWISTED,
	['wink']: EmotesTwinoidV1Enum.TWINOIDV1_WINK,
	['wink2']: EmotesTwinoidV1Enum.TWINOIDV1_WINK2,
	['yeah']: EmotesTwinoidV1Enum.TWINOIDV1_YEAH
};

export const EmotesTwinoidV1Icons: { [index: string]: string } = {
	[EmotesTwinoidV1Enum.TWINOIDV1_ARROW]: getImgURL('emotes/twinoidv1', 'arrow'),
	[EmotesTwinoidV1Enum.TWINOIDV1_CHART]: getImgURL('emotes/twinoidv1', 'chart'),
	[EmotesTwinoidV1Enum.TWINOIDV1_CONFUSED]: getImgURL('emotes/twinoidv1', 'confused'),
	[EmotesTwinoidV1Enum.TWINOIDV1_COOL]: getImgURL('emotes/twinoidv1', 'cool'),
	[EmotesTwinoidV1Enum.TWINOIDV1_CROSS]: getImgURL('emotes/twinoidv1', 'cross'),
	[EmotesTwinoidV1Enum.TWINOIDV1_CRY]: getImgURL('emotes/twinoidv1', 'cry'),
	[EmotesTwinoidV1Enum.TWINOIDV1_DONTCARE]: getImgURL('emotes/twinoidv1', 'dontcare'),
	[EmotesTwinoidV1Enum.TWINOIDV1_EEK]: getImgURL('emotes/twinoidv1', 'eek'),
	[EmotesTwinoidV1Enum.TWINOIDV1_EVIL]: getImgURL('emotes/twinoidv1', 'evil'),
	[EmotesTwinoidV1Enum.TWINOIDV1_EXCLAIM]: getImgURL('emotes/twinoidv1', 'exclaim'),
	[EmotesTwinoidV1Enum.TWINOIDV1_HAPPY]: getImgURL('emotes/twinoidv1', 'happy'),
	[EmotesTwinoidV1Enum.TWINOIDV1_HUH]: getImgURL('emotes/twinoidv1', 'huh'),
	[EmotesTwinoidV1Enum.TWINOIDV1_IDEA]: getImgURL('emotes/twinoidv1', 'idea'),
	[EmotesTwinoidV1Enum.TWINOIDV1_KEEPCOOL]: getImgURL('emotes/twinoidv1', 'keepcool'),
	[EmotesTwinoidV1Enum.TWINOIDV1_LOL]: getImgURL('emotes/twinoidv1', 'lol'),
	[EmotesTwinoidV1Enum.TWINOIDV1_MAD]: getImgURL('emotes/twinoidv1', 'mad'),
	[EmotesTwinoidV1Enum.TWINOIDV1_NOOO]: getImgURL('emotes/twinoidv1', 'nooo'),
	[EmotesTwinoidV1Enum.TWINOIDV1_QUESTION]: getImgURL('emotes/twinoidv1', 'question'),
	[EmotesTwinoidV1Enum.TWINOIDV1_SAD]: getImgURL('emotes/twinoidv1', 'sad'),
	[EmotesTwinoidV1Enum.TWINOIDV1_SMILE]: getImgURL('emotes/twinoidv1', 'smile'),
	[EmotesTwinoidV1Enum.TWINOIDV1_SURPRISED]: getImgURL('emotes/twinoidv1', 'surprised'),
	[EmotesTwinoidV1Enum.TWINOIDV1_TWISTED]: getImgURL('emotes/twinoidv1', 'twisted'),
	[EmotesTwinoidV1Enum.TWINOIDV1_WINK]: getImgURL('emotes/twinoidv1', 'wink'),
	[EmotesTwinoidV1Enum.TWINOIDV1_WINK2]: getImgURL('emotes/twinoidv1', 'wink2'),
	[EmotesTwinoidV1Enum.TWINOIDV1_YEAH]: getImgURL('emotes/twinoidv1', 'yeah')
};
