import { getImgURL } from '../../../mixin/mixin';

export enum EmotesStatusEnum {
	STATUS_AMULST = 'amulst',
	STATUS_ASSAULT_BONUS = 'assault_bonus',
	STATUS_ASTONE = 'astone',
	STATUS_BASALT = 'basalt',
	STATUS_BCKPCK = 'bckppck',
	STATUS_BLOCKED_INVENTORY = 'blocked_inventory',
	STATUS_BONUS_DEF_AIR = 'bonus_def_air',
	STATUS_BONUS_DEF_FIRE = 'bonus_def_fire',
	STATUS_BONUS_DEF_LIGHTNING = 'bonus_def_lightning',
	STATUS_BONUS_DEF_WATER = 'bonus_def_water',
	STATUS_BONUS_DEF_WOOD = 'bonus_def_wood',
	STATUS_BOUEE = 'bouee',
	STATUS_BRKPEL = 'fx_brkpel',
	STATUS_BRKPEL2 = 'brkpel2',
	STATUS_CCARD = 'ccard',
	STATUS_CONTS1 = 'conts1',
	STATUS_CONTS2 = 'conts2',
	STATUS_CONTS3 = 'conts3',
	STATUS_CORAIL = 'corail',
	STATUS_CUP1 = 'cup1',
	STATUS_CUP2 = 'cup2',
	STATUS_CUP3 = 'cup3',
	STATUS_CUP4 = 'cup4',
	STATUS_CUZMAL = 'cuzmal',
	STATUS_DAZZLED = 'dazzled',
	STATUS_DEF_BONUS = 'def_bonus',
	STATUS_DEMON = 'fx_demon',
	STATUS_DODGE_BONUS = 'dodge_bonus',
	STATUS_ENERGY_BONUS = 'energy_bonus',
	STATUS_ENERGY_PENALTY = 'energy_penalty',
	STATUS_FASTER = 'faster',
	STATUS_FCHARM = 'fcharm',
	STATUS_GANTS = 'gant',
	STATUS_GSHOP = 'gshop',
	STATUS_ICE = 'ice',
	STATUS_INITIATIVE_BONUS = 'initiative_bonus',
	STATUS_INITIATIVE_PENALTY = 'initiative_penalty',
	STATUS_LANTRN = 'lantrn',
	STATUS_LOCKED = 'locked',
	STATUS_LVLUP1 = 'lvlup1',
	STATUS_LVLUP2 = 'lvlup2',
	STATUS_LVLUP3 = 'lvlup3',
	STATUS_MARAIS = 'marais',
	STATUS_MATESC = 'matesc',
	STATUS_MAUDIT = 'maudit',
	STATUS_MCAPT = 'mcapt',
	STATUS_MEDAL1 = 'medal1',
	STATUS_MEDAL2 = 'medal2',
	STATUS_MEDAL3 = 'medal3',
	STATUS_MEDAL4 = 'medal4',
	STATUS_MORSSO = 'morsso',
	STATUS_MUTE = 'mute',
	STATUS_NENUPH = 'nenuph',
	STATUS_NEWSKI = 'newski',
	STATUS_PALMES = 'palmes',
	STATUS_PELLE = 'pelle',
	STATUS_PELLE2 = 'pelle2',
	STATUS_PETRIFIED = 'petrified',
	STATUS_POISONED = 'poisoned',
	STATUS_POTION = 'potion',
	STATUS_PROTECTED = 'protected',
	STATUS_RASCA = 'rasca',
	STATUS_REINCA = 'reinca',
	STATUS_RENAIS = 'renais',
	STATUS_SHARINGAN = 'sharingan',
	STATUS_SKULL = 'skull',
	STATUS_SLEEP = 'sleep',
	STATUS_SLOW_DOWN = 'slow_down',
	STATUS_SYLKEY = 'sylkey',
	STATUS_TOTEM = 'totem',
	STATUS_UNTOUCHABLE = 'untouchable',
	STATUS_VKILL = 'vkill',
	STATUS_WCHARM = 'wcharm',
	STATUS_WPURE = 'wpure'
}

export const EmotesStatusAliases: { [index: string]: string } = {
	['amulst']: EmotesStatusEnum.STATUS_AMULST,
	['assault_bonus']: EmotesStatusEnum.STATUS_ASSAULT_BONUS,
	['astone']: EmotesStatusEnum.STATUS_ASTONE,
	['basalt']: EmotesStatusEnum.STATUS_BASALT,
	['bckppck']: EmotesStatusEnum.STATUS_BCKPCK,
	['blocked_inventory']: EmotesStatusEnum.STATUS_BLOCKED_INVENTORY,
	['bonus_def_air']: EmotesStatusEnum.STATUS_BONUS_DEF_AIR,
	['bonus_def_fire']: EmotesStatusEnum.STATUS_BONUS_DEF_FIRE,
	['bonus_def_lightning']: EmotesStatusEnum.STATUS_BONUS_DEF_LIGHTNING,
	['bonus_def_water']: EmotesStatusEnum.STATUS_BONUS_DEF_WATER,
	['bonus_def_wood']: EmotesStatusEnum.STATUS_BONUS_DEF_WOOD,
	['bouee']: EmotesStatusEnum.STATUS_BOUEE,
	['fx_brkpel']: EmotesStatusEnum.STATUS_BRKPEL,
	['brkpel2']: EmotesStatusEnum.STATUS_BRKPEL2,
	['ccard']: EmotesStatusEnum.STATUS_CCARD,
	['conts1']: EmotesStatusEnum.STATUS_CONTS1,
	['conts2']: EmotesStatusEnum.STATUS_CONTS2,
	['conts3']: EmotesStatusEnum.STATUS_CONTS3,
	['corail']: EmotesStatusEnum.STATUS_CORAIL,
	['cup1']: EmotesStatusEnum.STATUS_CUP1,
	['cup2']: EmotesStatusEnum.STATUS_CUP2,
	['cup3']: EmotesStatusEnum.STATUS_CUP3,
	['cup4']: EmotesStatusEnum.STATUS_CUP4,
	['cuzmal']: EmotesStatusEnum.STATUS_CUZMAL,
	['dazzled']: EmotesStatusEnum.STATUS_DAZZLED,
	['def_bonus']: EmotesStatusEnum.STATUS_DEF_BONUS,
	['fx_demon']: EmotesStatusEnum.STATUS_DEMON,
	['dodge_bonus']: EmotesStatusEnum.STATUS_DODGE_BONUS,
	['energy_bonus']: EmotesStatusEnum.STATUS_ENERGY_BONUS,
	['energy_penalty']: EmotesStatusEnum.STATUS_ENERGY_PENALTY,
	['faster']: EmotesStatusEnum.STATUS_FASTER,
	['fcharm']: EmotesStatusEnum.STATUS_FCHARM,
	['gant']: EmotesStatusEnum.STATUS_GANTS,
	['gshop']: EmotesStatusEnum.STATUS_GSHOP,
	['ice']: EmotesStatusEnum.STATUS_ICE,
	['initiative_bonus']: EmotesStatusEnum.STATUS_INITIATIVE_BONUS,
	['initiative_penalty']: EmotesStatusEnum.STATUS_INITIATIVE_PENALTY,
	['lantrn']: EmotesStatusEnum.STATUS_LANTRN,
	['locked']: EmotesStatusEnum.STATUS_LOCKED,
	['lvlup1']: EmotesStatusEnum.STATUS_LVLUP1,
	['lvlup2']: EmotesStatusEnum.STATUS_LVLUP2,
	['lvlup3']: EmotesStatusEnum.STATUS_LVLUP3,
	['marais']: EmotesStatusEnum.STATUS_MARAIS,
	['matesc']: EmotesStatusEnum.STATUS_MATESC,
	['maudit']: EmotesStatusEnum.STATUS_MAUDIT,
	['mcapt']: EmotesStatusEnum.STATUS_MCAPT,
	['medal1']: EmotesStatusEnum.STATUS_MEDAL1,
	['medal2']: EmotesStatusEnum.STATUS_MEDAL2,
	['medal3']: EmotesStatusEnum.STATUS_MEDAL3,
	['medal4']: EmotesStatusEnum.STATUS_MEDAL4,
	['morsso']: EmotesStatusEnum.STATUS_MORSSO,
	['mute']: EmotesStatusEnum.STATUS_MUTE,
	['nenuph']: EmotesStatusEnum.STATUS_NENUPH,
	['newski']: EmotesStatusEnum.STATUS_NEWSKI,
	['palmes']: EmotesStatusEnum.STATUS_PALMES,
	['pelle']: EmotesStatusEnum.STATUS_PELLE,
	['pelle2']: EmotesStatusEnum.STATUS_PELLE2,
	['petrified']: EmotesStatusEnum.STATUS_PETRIFIED,
	['poisoned']: EmotesStatusEnum.STATUS_POISONED,
	['potion']: EmotesStatusEnum.STATUS_POTION,
	['protected']: EmotesStatusEnum.STATUS_PROTECTED,
	['rasca']: EmotesStatusEnum.STATUS_RASCA,
	['reinca']: EmotesStatusEnum.STATUS_REINCA,
	['renais']: EmotesStatusEnum.STATUS_RENAIS,
	['sharingan']: EmotesStatusEnum.STATUS_SHARINGAN,
	['skull']: EmotesStatusEnum.STATUS_SKULL,
	['sleep']: EmotesStatusEnum.STATUS_SLEEP,
	['slow_down']: EmotesStatusEnum.STATUS_SLOW_DOWN,
	['sylkey']: EmotesStatusEnum.STATUS_SYLKEY,
	['totem']: EmotesStatusEnum.STATUS_TOTEM,
	['untouchable']: EmotesStatusEnum.STATUS_UNTOUCHABLE,
	['vkill']: EmotesStatusEnum.STATUS_VKILL,
	['wcharm']: EmotesStatusEnum.STATUS_WCHARM,
	['wpure']: EmotesStatusEnum.STATUS_WPURE
};

export const EmotesStatusIcons: { [index: string]: string } = {
	[EmotesStatusEnum.STATUS_AMULST]: getImgURL('status', 'fx_amulst'),
	[EmotesStatusEnum.STATUS_ASSAULT_BONUS]: getImgURL('guide', 'status_assault_bonus'),
	[EmotesStatusEnum.STATUS_ASTONE]: getImgURL('status', 'fx_astone'),
	[EmotesStatusEnum.STATUS_BASALT]: getImgURL('status', 'fx_basalt'),
	[EmotesStatusEnum.STATUS_BCKPCK]: getImgURL('status', 'fx_bckpck'),
	[EmotesStatusEnum.STATUS_BLOCKED_INVENTORY]: getImgURL('guide', 'status_blocked_inventory'),
	[EmotesStatusEnum.STATUS_BONUS_DEF_AIR]: getImgURL('guide', 'status_bonus_def_air'),
	[EmotesStatusEnum.STATUS_BONUS_DEF_FIRE]: getImgURL('guide', 'status_bonus_def_fire'),
	[EmotesStatusEnum.STATUS_BONUS_DEF_LIGHTNING]: getImgURL('guide', 'status_bonus_def_lightning'),
	[EmotesStatusEnum.STATUS_BONUS_DEF_WATER]: getImgURL('guide', 'status_bonus_def_water'),
	[EmotesStatusEnum.STATUS_BONUS_DEF_WOOD]: getImgURL('guide', 'status_bonus_def_wood'),
	[EmotesStatusEnum.STATUS_BOUEE]: getImgURL('status', 'fx_bouee'),
	[EmotesStatusEnum.STATUS_BRKPEL]: getImgURL('status', 'fx_brkpel'),
	[EmotesStatusEnum.STATUS_BRKPEL2]: getImgURL('status', 'fx_brkpel2'),
	[EmotesStatusEnum.STATUS_CCARD]: getImgURL('status', 'fx_ccard'),
	[EmotesStatusEnum.STATUS_CONTS1]: getImgURL('status', 'fx_conts1'),
	[EmotesStatusEnum.STATUS_CONTS2]: getImgURL('status', 'fx_conts2'),
	[EmotesStatusEnum.STATUS_CONTS3]: getImgURL('status', 'fx_conts3'),
	[EmotesStatusEnum.STATUS_CORAIL]: getImgURL('status', 'fx_corail'),
	[EmotesStatusEnum.STATUS_CUP1]: getImgURL('status', 'fx_cup1'),
	[EmotesStatusEnum.STATUS_CUP2]: getImgURL('status', 'fx_cup2'),
	[EmotesStatusEnum.STATUS_CUP3]: getImgURL('status', 'fx_cup3'),
	[EmotesStatusEnum.STATUS_CUP4]: getImgURL('status', 'fx_cup4'),
	[EmotesStatusEnum.STATUS_CUZMAL]: getImgURL('status', 'fx_cuzmal'),
	[EmotesStatusEnum.STATUS_DAZZLED]: getImgURL('guide', 'status_dazzled'),
	[EmotesStatusEnum.STATUS_DEF_BONUS]: getImgURL('guide', 'status_def_bonus'),
	[EmotesStatusEnum.STATUS_DEMON]: getImgURL('status', 'fx_demon'),
	[EmotesStatusEnum.STATUS_DODGE_BONUS]: getImgURL('guide', 'status_dodge_bonus'),
	[EmotesStatusEnum.STATUS_ENERGY_BONUS]: getImgURL('guide', 'status_energy_bonus'),
	[EmotesStatusEnum.STATUS_ENERGY_PENALTY]: getImgURL('guide', 'status_energy_penalty'),
	[EmotesStatusEnum.STATUS_FASTER]: getImgURL('guide', 'status_faster'),
	[EmotesStatusEnum.STATUS_FCHARM]: getImgURL('status', 'fx_fcharm'),
	[EmotesStatusEnum.STATUS_GANTS]: getImgURL('status', 'fx_gant'),
	[EmotesStatusEnum.STATUS_GSHOP]: getImgURL('status', 'fx_gshop'),
	[EmotesStatusEnum.STATUS_ICE]: getImgURL('status', 'fx_ice'),
	[EmotesStatusEnum.STATUS_INITIATIVE_BONUS]: getImgURL('guide', 'status_initiative_bonus'),
	[EmotesStatusEnum.STATUS_INITIATIVE_PENALTY]: getImgURL('guide', 'status_initiative_penalty'),
	[EmotesStatusEnum.STATUS_LANTRN]: getImgURL('status', 'fx_lantrn'),
	[EmotesStatusEnum.STATUS_LOCKED]: getImgURL('guide', 'status_locked'),
	[EmotesStatusEnum.STATUS_LVLUP1]: getImgURL('status', 'fx_lvlup1'),
	[EmotesStatusEnum.STATUS_LVLUP2]: getImgURL('status', 'fx_lvlup2'),
	[EmotesStatusEnum.STATUS_LVLUP3]: getImgURL('status', 'fx_lvlup3'),
	[EmotesStatusEnum.STATUS_MARAIS]: getImgURL('status', 'fx_marais'),
	[EmotesStatusEnum.STATUS_MATESC]: getImgURL('status', 'fx_matesc'),
	[EmotesStatusEnum.STATUS_MAUDIT]: getImgURL('status', 'fx_maudit'),
	[EmotesStatusEnum.STATUS_MCAPT]: getImgURL('status', 'fx_mcapt'),
	[EmotesStatusEnum.STATUS_MEDAL1]: getImgURL('status', 'fx_medal1'),
	[EmotesStatusEnum.STATUS_MEDAL2]: getImgURL('status', 'fx_medal2'),
	[EmotesStatusEnum.STATUS_MEDAL3]: getImgURL('status', 'fx_medal3'),
	[EmotesStatusEnum.STATUS_MEDAL4]: getImgURL('status', 'fx_medal4'),
	[EmotesStatusEnum.STATUS_MORSSO]: getImgURL('status', 'fx_morsso'),
	[EmotesStatusEnum.STATUS_MUTE]: getImgURL('guide', 'status_mute'),
	[EmotesStatusEnum.STATUS_NENUPH]: getImgURL('status', 'fx_nenuph'),
	[EmotesStatusEnum.STATUS_NEWSKI]: getImgURL('status', 'fx_newski'),
	[EmotesStatusEnum.STATUS_PALMES]: getImgURL('status', 'fx_palmes'),
	[EmotesStatusEnum.STATUS_PELLE]: getImgURL('status', 'fx_pelle'),
	[EmotesStatusEnum.STATUS_PELLE2]: getImgURL('status', 'fx_pelle2'),
	[EmotesStatusEnum.STATUS_PETRIFIED]: getImgURL('guide', 'status_petrified'),
	[EmotesStatusEnum.STATUS_POISONED]: getImgURL('guide', 'status_poisoned'),
	[EmotesStatusEnum.STATUS_POTION]: getImgURL('status', 'fx_potion'),
	[EmotesStatusEnum.STATUS_PROTECTED]: getImgURL('guide', 'status_protected'),
	[EmotesStatusEnum.STATUS_RASCA]: getImgURL('status', 'fx_rasca'),
	[EmotesStatusEnum.STATUS_REINCA]: getImgURL('status', 'fx_reinca'),
	[EmotesStatusEnum.STATUS_RENAIS]: getImgURL('status', 'fx_renais'),
	[EmotesStatusEnum.STATUS_SHARINGAN]: getImgURL('guide', 'status_sharingan'),
	[EmotesStatusEnum.STATUS_SKULL]: getImgURL('status', 'fx_skull'),
	[EmotesStatusEnum.STATUS_SLEEP]: getImgURL('guide', 'status_sleep'),
	[EmotesStatusEnum.STATUS_SLOW_DOWN]: getImgURL('guide', 'status_slow_down'),
	[EmotesStatusEnum.STATUS_SYLKEY]: getImgURL('status', 'fx_sylkey'),
	[EmotesStatusEnum.STATUS_TOTEM]: getImgURL('status', 'fx_totem'),
	[EmotesStatusEnum.STATUS_UNTOUCHABLE]: getImgURL('guide', 'status_untouchable'),
	[EmotesStatusEnum.STATUS_VKILL]: getImgURL('status', 'fx_vkill'),
	[EmotesStatusEnum.STATUS_WCHARM]: getImgURL('status', 'fx_wcharm'),
	[EmotesStatusEnum.STATUS_WPURE]: getImgURL('status', 'fx_wpure')
};
