import { getImgURL } from '../../../mixin/mixin';

export enum EmotesResourcesEnum {
	// Items
	RESOURCES_ABYSS = 'abyss',
	RESOURCES_AIR_SPHERE = 'air_sphere',
	RESOURCES_AMAZON = 'amazon',
	RESOURCES_AMNESIC_RICE = 'amnesic_rice',
	RESOURCES_ANNIVERSARY_TICKET = 'anniversary_ticket',
	RESOURCES_ANTI_GRAVE_SUIT = 'anti_grave_suit',
	RESOURCES_ANTICHROMATIC = 'antichromatic',
	RESOURCES_ANTIDOTE = 'antidote',
	RESOURCES_BAMBOO_FRIEND = 'bamboo_friend',
	RESOURCES_BANISHEMENT = 'banishement',
	RESOURCES_BATTERING_RAM = 'battering_ram',
	RESOURCES_BEER = 'beer',
	RESOURCES_BOX_COMMON = 'box_common',
	RESOURCES_BOX_EPIC = 'box_epic',
	RESOURCES_BOX_LEGENDARY = 'box_legendary',
	RESOURCES_BOX_RARE = 'box_rare',
	RESOURCES_CANDLE_CARD = 'candle_card',
	RESOURCES_CASTIVORE_EGG = 'castivore_egg',
	RESOURCES_CASTIVORE_EGG_RARE = 'castivore_egg_rare',
	RESOURCES_CHRISTMAS_EGG = 'christmas_egg',
	RESOURCES_CHRISTMAS_TICKET = 'christmas_ticket',
	RESOURCES_CLOUD_BURGER = 'cloud_burger',
	RESOURCES_CURSE_LOCKER = 'curse_locker',
	RESOURCES_CUZCUSSIAN_MASK = 'cuzcussian_mask',
	RESOURCES_DAILY_TICKET = 'daily_ticket',
	RESOURCES_DANGER_DETECTOR = 'danger_detector',
	RESOURCES_DEMON_TICKET = 'demon_ticket',
	RESOURCES_DEVIL_OINTMENT = 'devil_ointment',
	RESOURCES_DIMENSIONAL_POWDER = 'dimensional_powder',
	RESOURCES_DINOZ_CUBE = 'dinoz_cube',
	RESOURCES_EASTER_EGG = 'easter_egg',
	RESOURCES_EGG_BLUE = 'egg_blue',
	RESOURCES_EGG_RED = 'egg_red',
	RESOURCES_ELIXIR = 'elixir',
	RESOURCES_ELIXIR_OF_LIFE = 'elixir_of_life',
	RESOURCES_EMBER = 'ember',
	RESOURCES_EMPTY = 'empty',
	RESOURCES_ENCHANTED_STEROID = 'enchanted_steroid',
	RESOURCES_ENCYCLOPEDIA = 'encyclopedia',
	RESOURCES_FEAR_FACTOR = 'fear_factor',
	RESOURCES_FEROSS_EGG = 'feross_egg',
	RESOURCES_FEROSS_EGG_CHRISTMAS = 'feross_egg_christmas',
	RESOURCES_FIGHT_RATION = 'fight_ration',
	RESOURCES_FIRE_CRACKER = 'fire_cracker',
	RESOURCES_FIRE_SPHERE = 'fire_sphere',
	RESOURCES_FRIENDLY_WHISTLE = 'friendly_whistle',
	RESOURCES_FUCA_PILL = 'fuca_pill',
	RESOURCES_GOBLIN_COSTUME = 'goblin_costume',
	RESOURCES_GOBLIN_MERGUEZ = 'goblin_merguez',
	RESOURCES_GOLD = 'gold',
	RESOURCES_GORILLOZ_EGG = 'gorilloz_egg',
	RESOURCES_GORILLOZ_EGG_RARE = 'gorilloz_egg_rare',
	RESOURCES_HIPPOCLAMP_EGG = 'hippoclamp_egg',
	RESOURCES_HOT_BREAD = 'hot_bread',
	RESOURCES_ICEDOC = 'icedoc',
	RESOURCES_KABUKI_EGG = 'kabuki_egg',
	RESOURCES_KABUKI_EGG_RARE = 'kabuki_egg_rare',
	RESOURCES_LAND_OF_ASHES = 'land_of_ashes',
	RESOURCES_LIFE_STEALER = 'life_stealer',
	RESOURCES_LIGHTNING_SPHERE = 'lightning_sphere',
	RESOURCES_LITTLE_PEPPER = 'little_pepper',
	RESOURCES_LORIS_COSTUME = 'loris_costume',
	RESOURCES_MAGIC_STAR = 'magic_star',
	RESOURCES_MAHAMUTI_EGG = 'mahamuti_egg',
	RESOURCES_MAHAMUTI_EGG_RARE = 'mahamuti_egg_rare',
	RESOURCES_MEAT_PIE = 'meat_pie',
	RESOURCES_MONOCHROMATIC = 'monochromatic',
	RESOURCES_MOUEFFE_EGG = 'moueffe_egg',
	RESOURCES_MOUEFFE_EGG_RARE = 'moueffe_egg_rare',
	RESOURCES_NUAGOZ_EGG = 'nuagoz_egg',
	RESOURCES_NUAGOZ_EGG_RARE = 'nuagoz_egg_rare',
	RESOURCES_PAMPLEBOUM = 'pampleboum',
	RESOURCES_PAMPLEBOUM_PIT = 'pampleboum_pit',
	RESOURCES_PIGMOU_EGG = 'pigmou_egg',
	RESOURCES_PIGMOU_EGG_RARE = 'pigmou_egg_rare',
	RESOURCES_PIRHANOZ_IN_BAG = 'pirhanoz_in_bag',
	RESOURCES_PLANAILLE_EGG = 'planaille_egg',
	RESOURCES_PLANAILLE_EGG_RARE = 'planaille_egg_rare',
	RESOURCES_POISONITE_SHOT = 'poisonite_shot',
	RESOURCES_PORTABLE_LOVE = 'portable_love',
	RESOURCES_POTION_ANGEL = 'potion_angel',
	RESOURCES_POTION_IRMA = 'potion_irma',
	RESOURCES_PTEROZ_EGG = 'pteroz_egg',
	RESOURCES_PTSAGE = 'ptsage',
	RESOURCES_QUETZU_EGG_RARE = 'quetzu_egg_rare',
	RESOURCES_REFRIGERATED_SHIELD = 'refrigerated_shield',
	RESOURCES_ROCKY_EGG = 'rocky_egg',
	RESOURCES_SANTAZ_EGG = 'santaz_egg',
	RESOURCES_SANTAZ_EGG_RARE = 'santaz_egg_rare',
	RESOURCES_SCALE = 'scale',
	RESOURCES_SIRAIN_EGG = 'sirain_egg',
	RESOURCES_SIRAIN_EGG_RARE = 'sirain_egg_rare',
	RESOURCES_SMOG_EGG = 'smog_egg',
	RESOURCES_SMOG_EGG_ANNIVERSARY = 'smog_egg_anniversary',
	RESOURCES_SMOG_EGG_CHRISTMAS_BLUE = 'smog_egg_christmas_blue',
	RESOURCES_SMOG_EGG_CHRISTMAS_GREEN = 'smog_egg_christmas_green',
	RESOURCES_SORCERERS_STICK = 'sorcerers_stick',
	RESOURCES_SOS_FLAME = 'sos_flame',
	RESOURCES_SOS_HELMET = 'sos_helmet',
	RESOURCES_SOUFFLET_EGG = 'soufflet_egg',
	RESOURCES_SPECIAL_POTION_IRMA = 'special_potion_irma',
	RESOURCES_ST_ELMAS_FIRE = 'st_elmas_fire',
	RESOURCES_STRONG_TEA = 'strong_tea',
	RESOURCES_SURVIVING_RATION = 'surviving_ration',
	RESOURCES_TEAR_OF_LIFE = 'tear_of_life',
	RESOURCES_TEMPORAL_REDUCTION = 'temporal_reduction',
	RESOURCES_TEMPORAL_STABILIZER = 'temporal_stabilizer',
	RESOURCES_TICTAC_TICKET = 'tictac_ticket',
	RESOURCES_TIK_BRACELET = 'tik_bracelet',
	RESOURCES_TIME_MANIPULATOR = 'time_manipulator',
	RESOURCES_TOUFUFU_BABY = 'toufufu_baby',
	RESOURCES_TOUFUFU_BABY_RARE = 'toufufu_baby_rare',
	RESOURCES_TREASURE_COUPON = 'treasure_coupon',
	RESOURCES_TRICERAGNON_BABY = 'triceragnon_baby',
	RESOURCES_UNDEFINED = 'undefined',
	RESOURCES_UVAVU = 'uvavu',
	RESOURCES_VEGETOX_COSTUME = 'vegetox_costume',
	RESOURCES_VOID_SPHERE = 'void_sphere',
	RESOURCES_WANWAN_BABY_RARE = 'wanwan_baby_rare',
	RESOURCES_WANWAN_EGG = 'wanwan_egg',
	RESOURCES_WATER_SPHERE = 'water_sphere',
	RESOURCES_WINKS_EGG = 'winks_egg',
	RESOURCES_WINKS_EGG_RARE = 'winks_egg_rare',
	RESOURCES_WOOD_SPHERE = 'wood_sphere',
	RESOURCES_ZIPPO = 'zippo',
	// Ingredients
	RESOURCES_AN_GUILI_GUILILLE = 'an_guili_guilille',
	RESOURCES_BOLET_PHALISK_BLANC = 'bolet_phalisk_blanc',
	RESOURCES_BRAS_MECANIQUE = 'bras_mecanique',
	RESOURCES_BROCHE_EN_PARFAIT_ETAT = 'broche_en_parfait_etat',
	RESOURCES_CALISE_CISELE = 'calice_cisele',
	RESOURCES_COLLIER_KARAT = 'collier_karat',
	RESOURCES_CORNE_EN_CHOCOLAT = 'corne_en_chocolat',
	RESOURCES_DENT_DE_DOROGON = 'dent_de_dorogon',
	RESOURCES_ENERGIE_AIR = 'energie_air',
	RESOURCES_ENERGIE_BOIS = 'energie_bois',
	RESOURCES_ENERGIE_EAU = 'energie_eau',
	RESOURCES_ENERGIE_FEU = 'energie_feu',
	RESOURCES_ENERGIE_FOUDRE = 'energie_foudre',
	RESOURCES_FEUILLES_DE_PELINAE = 'feuilles_de_pelinae',
	RESOURCES_FLAUREOLE = 'flaureole',
	RESOURCES_FRAGMENT_DE_TEXTE_ANCIEN = 'fragment_de_texte_ancien',
	RESOURCES_GLOBULOS = 'globulos',
	RESOURCES_GRAINE_DE_DEVOREUSE = 'graine_de_devoreuse',
	RESOURCES_GRIFFES_ACEREES = 'griffes_acerees',
	RESOURCES_LANGUE_MONSTRUEUSE = 'langue_monstrueuse',
	RESOURCES_MEROU_LUJIDANE = 'merou_lujidane',
	RESOURCES_OEIL_VISQUEUX = 'oeil_visqueux',
	RESOURCES_ORCHIDEE_FANTASQUE = 'orchidee_fantasque',
	RESOURCES_POISSON_VENGEUR = 'poisson_vengeur',
	RESOURCES_POUSSE_SOMBRE = 'pousse_sombre',
	RESOURCES_RACINE_DE_FIGONICIA = 'racine_de_figonicia',
	RESOURCES_ROCHE_RADIO_ACTIVE = 'roche_radio_active',
	RESOURCES_SADIQUAE_MORDICUS = 'sadiquae_mordicus',
	RESOURCES_SILEX_TAILLE = 'silex_taille',
	RESOURCES_SPORE_ETHERAL = 'spore_etheral',
	RESOURCES_SUPER_POISSOn = 'super_poisson',
	RESOURCES_SUPERBE_COURONNE_ROYALE = 'superbe_couronne_royale',
	RESOURCES_TOUFFE_DE_FOURRURE = 'touffe_de_fourrure',
	RESOURCES_VIEIL_ANNEAU_PRECIEUX = 'vieil_anneau_precieux'
}

export const EmotesResourcesAliases: { [index: string]: string } = {
	['abyss']: EmotesResourcesEnum.RESOURCES_ABYSS,
	['air_sphere']: EmotesResourcesEnum.RESOURCES_AIR_SPHERE,
	['amazon']: EmotesResourcesEnum.RESOURCES_AMAZON,
	['amnesic_rice']: EmotesResourcesEnum.RESOURCES_AMNESIC_RICE,
	['anniversary_ticket']: EmotesResourcesEnum.RESOURCES_ANNIVERSARY_TICKET,
	['anti_grave_suit']: EmotesResourcesEnum.RESOURCES_ANTI_GRAVE_SUIT,
	['antichromatic']: EmotesResourcesEnum.RESOURCES_ANTICHROMATIC,
	['antidote']: EmotesResourcesEnum.RESOURCES_ANTIDOTE,
	['bamboo_friend']: EmotesResourcesEnum.RESOURCES_BAMBOO_FRIEND,
	['banishement']: EmotesResourcesEnum.RESOURCES_BANISHEMENT,
	['battering_ram']: EmotesResourcesEnum.RESOURCES_BATTERING_RAM,
	['beer']: EmotesResourcesEnum.RESOURCES_BEER,
	['box_common']: EmotesResourcesEnum.RESOURCES_BOX_COMMON,
	['box_epic']: EmotesResourcesEnum.RESOURCES_BOX_EPIC,
	['box_legendary']: EmotesResourcesEnum.RESOURCES_BOX_LEGENDARY,
	['box_rare']: EmotesResourcesEnum.RESOURCES_BOX_RARE,
	['candle_card']: EmotesResourcesEnum.RESOURCES_CANDLE_CARD,
	['castivore_egg']: EmotesResourcesEnum.RESOURCES_CASTIVORE_EGG,
	['castivore_egg_rare']: EmotesResourcesEnum.RESOURCES_CASTIVORE_EGG_RARE,
	['christmas_egg']: EmotesResourcesEnum.RESOURCES_CHRISTMAS_EGG,
	['christmas_ticket']: EmotesResourcesEnum.RESOURCES_CHRISTMAS_TICKET,
	['cloud_burger']: EmotesResourcesEnum.RESOURCES_CLOUD_BURGER,
	['curse_locker']: EmotesResourcesEnum.RESOURCES_CURSE_LOCKER,
	['cuzcussian_mask']: EmotesResourcesEnum.RESOURCES_CUZCUSSIAN_MASK,
	['daily_ticket']: EmotesResourcesEnum.RESOURCES_DAILY_TICKET,
	['danger_detector']: EmotesResourcesEnum.RESOURCES_DANGER_DETECTOR,
	['demon_ticket']: EmotesResourcesEnum.RESOURCES_DEMON_TICKET,
	['devil_ointment']: EmotesResourcesEnum.RESOURCES_DEVIL_OINTMENT,
	['dimensional_powder']: EmotesResourcesEnum.RESOURCES_DIMENSIONAL_POWDER,
	['dinoz_cube']: EmotesResourcesEnum.RESOURCES_DINOZ_CUBE,
	['easter_egg']: EmotesResourcesEnum.RESOURCES_EASTER_EGG,
	['egg_blue']: EmotesResourcesEnum.RESOURCES_EGG_BLUE,
	['egg_red']: EmotesResourcesEnum.RESOURCES_EGG_RED,
	['elixir']: EmotesResourcesEnum.RESOURCES_ELIXIR,
	['elixir_of_life']: EmotesResourcesEnum.RESOURCES_ELIXIR_OF_LIFE,
	['ember']: EmotesResourcesEnum.RESOURCES_EMBER,
	['empty']: EmotesResourcesEnum.RESOURCES_EMPTY,
	['enchanted_steroid']: EmotesResourcesEnum.RESOURCES_ENCHANTED_STEROID,
	['encyclopedia']: EmotesResourcesEnum.RESOURCES_ENCYCLOPEDIA,
	['fear_factor']: EmotesResourcesEnum.RESOURCES_FEAR_FACTOR,
	['feross_egg']: EmotesResourcesEnum.RESOURCES_FEROSS_EGG,
	['feross_egg_christmas']: EmotesResourcesEnum.RESOURCES_FEROSS_EGG_CHRISTMAS,
	['fight_ration']: EmotesResourcesEnum.RESOURCES_FIGHT_RATION,
	['fire_cracker']: EmotesResourcesEnum.RESOURCES_FIRE_CRACKER,
	['fire_sphere']: EmotesResourcesEnum.RESOURCES_FIRE_SPHERE,
	['friendly_whistle']: EmotesResourcesEnum.RESOURCES_FRIENDLY_WHISTLE,
	['fuca_pill']: EmotesResourcesEnum.RESOURCES_FUCA_PILL,
	['goblin_costume']: EmotesResourcesEnum.RESOURCES_GOBLIN_COSTUME,
	['goblin_merguez']: EmotesResourcesEnum.RESOURCES_GOBLIN_MERGUEZ,
	['gold']: EmotesResourcesEnum.RESOURCES_GOLD,
	['gorilloz_egg']: EmotesResourcesEnum.RESOURCES_GORILLOZ_EGG,
	['gorilloz_egg_rare']: EmotesResourcesEnum.RESOURCES_GORILLOZ_EGG_RARE,
	['hippoclamp_egg']: EmotesResourcesEnum.RESOURCES_HIPPOCLAMP_EGG,
	['hot_bread']: EmotesResourcesEnum.RESOURCES_HOT_BREAD,
	['icedoc']: EmotesResourcesEnum.RESOURCES_ICEDOC,
	['kabuki_egg']: EmotesResourcesEnum.RESOURCES_KABUKI_EGG,
	['kabuki_egg_rare']: EmotesResourcesEnum.RESOURCES_KABUKI_EGG_RARE,
	['land_of_ashes']: EmotesResourcesEnum.RESOURCES_LAND_OF_ASHES,
	['life_stealer']: EmotesResourcesEnum.RESOURCES_LIFE_STEALER,
	['lightning_sphere']: EmotesResourcesEnum.RESOURCES_LIGHTNING_SPHERE,
	['little_pepper']: EmotesResourcesEnum.RESOURCES_LITTLE_PEPPER,
	['loris_costume']: EmotesResourcesEnum.RESOURCES_LORIS_COSTUME,
	['magic_star']: EmotesResourcesEnum.RESOURCES_MAGIC_STAR,
	['mahamuti_egg']: EmotesResourcesEnum.RESOURCES_MAHAMUTI_EGG,
	['mahamuti_egg_rare']: EmotesResourcesEnum.RESOURCES_MAHAMUTI_EGG_RARE,
	['meat_pie']: EmotesResourcesEnum.RESOURCES_MEAT_PIE,
	['monochromatic']: EmotesResourcesEnum.RESOURCES_MONOCHROMATIC,
	['moueffe_egg']: EmotesResourcesEnum.RESOURCES_MOUEFFE_EGG,
	['moueffe_egg_rare']: EmotesResourcesEnum.RESOURCES_MOUEFFE_EGG_RARE,
	['nuagoz_egg']: EmotesResourcesEnum.RESOURCES_NUAGOZ_EGG,
	['nuagoz_egg_rare']: EmotesResourcesEnum.RESOURCES_NUAGOZ_EGG_RARE,
	['pampleboum']: EmotesResourcesEnum.RESOURCES_PAMPLEBOUM,
	['pampleboum_pit']: EmotesResourcesEnum.RESOURCES_PAMPLEBOUM_PIT,
	['pigmou_egg']: EmotesResourcesEnum.RESOURCES_PIGMOU_EGG,
	['pigmou_egg_rare']: EmotesResourcesEnum.RESOURCES_PIGMOU_EGG_RARE,
	['pirhanoz_in_bag']: EmotesResourcesEnum.RESOURCES_PIRHANOZ_IN_BAG,
	['planaille_egg']: EmotesResourcesEnum.RESOURCES_PLANAILLE_EGG,
	['planaille_egg_rare']: EmotesResourcesEnum.RESOURCES_PLANAILLE_EGG_RARE,
	['poisonite_shot']: EmotesResourcesEnum.RESOURCES_POISONITE_SHOT,
	['portable_love']: EmotesResourcesEnum.RESOURCES_PORTABLE_LOVE,
	['potion_angel']: EmotesResourcesEnum.RESOURCES_POTION_ANGEL,
	['potion_irma']: EmotesResourcesEnum.RESOURCES_POTION_IRMA,
	['pteroz_egg']: EmotesResourcesEnum.RESOURCES_PTEROZ_EGG,
	['ptsage']: EmotesResourcesEnum.RESOURCES_PTSAGE,
	['quetzu_egg_rare']: EmotesResourcesEnum.RESOURCES_QUETZU_EGG_RARE,
	['refrigerated_shield']: EmotesResourcesEnum.RESOURCES_REFRIGERATED_SHIELD,
	['rocky_egg']: EmotesResourcesEnum.RESOURCES_ROCKY_EGG,
	['santaz_egg']: EmotesResourcesEnum.RESOURCES_SANTAZ_EGG,
	['santaz_egg_rare']: EmotesResourcesEnum.RESOURCES_SANTAZ_EGG_RARE,
	['scale']: EmotesResourcesEnum.RESOURCES_SCALE,
	['sirain_egg']: EmotesResourcesEnum.RESOURCES_SIRAIN_EGG,
	['sirain_egg_rare']: EmotesResourcesEnum.RESOURCES_SIRAIN_EGG_RARE,
	['smog_egg']: EmotesResourcesEnum.RESOURCES_SMOG_EGG,
	['smog_egg_anniversary']: EmotesResourcesEnum.RESOURCES_SMOG_EGG_ANNIVERSARY,
	['smog_egg_christmas_blue']: EmotesResourcesEnum.RESOURCES_SMOG_EGG_CHRISTMAS_BLUE,
	['smog_egg_christmas_green']: EmotesResourcesEnum.RESOURCES_SMOG_EGG_CHRISTMAS_GREEN,
	['sorcerers_stick']: EmotesResourcesEnum.RESOURCES_SORCERERS_STICK,
	['sos_flame']: EmotesResourcesEnum.RESOURCES_SOS_FLAME,
	['sos_helmet']: EmotesResourcesEnum.RESOURCES_SOS_HELMET,
	['soufflet_egg']: EmotesResourcesEnum.RESOURCES_SOUFFLET_EGG,
	['special_potion_irma']: EmotesResourcesEnum.RESOURCES_SPECIAL_POTION_IRMA,
	['st_elmas_fire']: EmotesResourcesEnum.RESOURCES_ST_ELMAS_FIRE,
	['strong_tea']: EmotesResourcesEnum.RESOURCES_STRONG_TEA,
	['surviving_ration']: EmotesResourcesEnum.RESOURCES_SURVIVING_RATION,
	['tear_of_life']: EmotesResourcesEnum.RESOURCES_TEAR_OF_LIFE,
	['temporal_reduction']: EmotesResourcesEnum.RESOURCES_TEMPORAL_REDUCTION,
	['temporal_stabilizer']: EmotesResourcesEnum.RESOURCES_TEMPORAL_STABILIZER,
	['tictac_ticket']: EmotesResourcesEnum.RESOURCES_TICTAC_TICKET,
	['tik_bracelet']: EmotesResourcesEnum.RESOURCES_TIK_BRACELET,
	['time_manipulator']: EmotesResourcesEnum.RESOURCES_TIME_MANIPULATOR,
	['toufufu_baby']: EmotesResourcesEnum.RESOURCES_TOUFUFU_BABY,
	['toufufu_baby_rare']: EmotesResourcesEnum.RESOURCES_TOUFUFU_BABY_RARE,
	['treasure_coupon']: EmotesResourcesEnum.RESOURCES_TREASURE_COUPON,
	['triceragnon_baby']: EmotesResourcesEnum.RESOURCES_TRICERAGNON_BABY,
	['undefined']: EmotesResourcesEnum.RESOURCES_UNDEFINED,
	['uvavu']: EmotesResourcesEnum.RESOURCES_UVAVU,
	['vegetox_costume']: EmotesResourcesEnum.RESOURCES_VEGETOX_COSTUME,
	['void_sphere']: EmotesResourcesEnum.RESOURCES_VOID_SPHERE,
	['wanwan_baby_rare']: EmotesResourcesEnum.RESOURCES_WANWAN_BABY_RARE,
	['wanwan_egg']: EmotesResourcesEnum.RESOURCES_WANWAN_EGG,
	['water_sphere']: EmotesResourcesEnum.RESOURCES_WATER_SPHERE,
	['winks_egg']: EmotesResourcesEnum.RESOURCES_WINKS_EGG,
	['winks_egg_rare']: EmotesResourcesEnum.RESOURCES_WINKS_EGG_RARE,
	['wood_sphere']: EmotesResourcesEnum.RESOURCES_WOOD_SPHERE,
	['zippo']: EmotesResourcesEnum.RESOURCES_ZIPPO,
	['an_guili_guilille']: EmotesResourcesEnum.RESOURCES_AN_GUILI_GUILILLE,
	['bolet_phalisk_blanc']: EmotesResourcesEnum.RESOURCES_BOLET_PHALISK_BLANC,
	['bras_mecanique']: EmotesResourcesEnum.RESOURCES_BRAS_MECANIQUE,
	['broche_en_parfait_etat']: EmotesResourcesEnum.RESOURCES_BROCHE_EN_PARFAIT_ETAT,
	['calice_cisele']: EmotesResourcesEnum.RESOURCES_CALISE_CISELE,
	['collier_karat']: EmotesResourcesEnum.RESOURCES_COLLIER_KARAT,
	['corne_en_chocolat']: EmotesResourcesEnum.RESOURCES_CORNE_EN_CHOCOLAT,
	['dent_de_dorogon']: EmotesResourcesEnum.RESOURCES_DENT_DE_DOROGON,
	['energie_air']: EmotesResourcesEnum.RESOURCES_ENERGIE_AIR,
	['energie_bois']: EmotesResourcesEnum.RESOURCES_ENERGIE_BOIS,
	['energie_eau']: EmotesResourcesEnum.RESOURCES_ENERGIE_EAU,
	['energie_feu']: EmotesResourcesEnum.RESOURCES_ENERGIE_FEU,
	['energie_foudre']: EmotesResourcesEnum.RESOURCES_ENERGIE_FOUDRE,
	['feuilles_de_pelinae']: EmotesResourcesEnum.RESOURCES_FEUILLES_DE_PELINAE,
	['flaureole']: EmotesResourcesEnum.RESOURCES_FLAUREOLE,
	['fragment_de_texte_ancien']: EmotesResourcesEnum.RESOURCES_FRAGMENT_DE_TEXTE_ANCIEN,
	['globulos']: EmotesResourcesEnum.RESOURCES_GLOBULOS,
	['graine_de_devoreuse']: EmotesResourcesEnum.RESOURCES_GRAINE_DE_DEVOREUSE,
	['griffes_acerees']: EmotesResourcesEnum.RESOURCES_GRIFFES_ACEREES,
	['langue_monstrueuse']: EmotesResourcesEnum.RESOURCES_LANGUE_MONSTRUEUSE,
	['merou_lujidane']: EmotesResourcesEnum.RESOURCES_MEROU_LUJIDANE,
	['oeil_visqueux']: EmotesResourcesEnum.RESOURCES_OEIL_VISQUEUX,
	['orchidee_fantasque']: EmotesResourcesEnum.RESOURCES_ORCHIDEE_FANTASQUE,
	['poisson_vengeur']: EmotesResourcesEnum.RESOURCES_POISSON_VENGEUR,
	['pousse_sombre']: EmotesResourcesEnum.RESOURCES_POUSSE_SOMBRE,
	['racine_de_figonicia']: EmotesResourcesEnum.RESOURCES_RACINE_DE_FIGONICIA,
	['roche_radio_active']: EmotesResourcesEnum.RESOURCES_ROCHE_RADIO_ACTIVE,
	['sadiquae_mordicus']: EmotesResourcesEnum.RESOURCES_SADIQUAE_MORDICUS,
	['silex_taille']: EmotesResourcesEnum.RESOURCES_SILEX_TAILLE,
	['spore_etheral']: EmotesResourcesEnum.RESOURCES_SPORE_ETHERAL,
	['super_poisson']: EmotesResourcesEnum.RESOURCES_SUPER_POISSOn,
	['superbe_couronne_royale']: EmotesResourcesEnum.RESOURCES_SUPERBE_COURONNE_ROYALE,
	['touffe_de_fourrure']: EmotesResourcesEnum.RESOURCES_TOUFFE_DE_FOURRURE,
	['vieil_anneau_precieux']: EmotesResourcesEnum.RESOURCES_VIEIL_ANNEAU_PRECIEUX
};

export const EmotesResourcesIcons: { [index: string]: string } = {
	[EmotesResourcesEnum.RESOURCES_ABYSS]: getImgURL('item', 'item_abyss'),
	[EmotesResourcesEnum.RESOURCES_AIR_SPHERE]: getImgURL('item', 'item_air_sphere'),
	[EmotesResourcesEnum.RESOURCES_AMAZON]: getImgURL('item', 'item_amazon'),
	[EmotesResourcesEnum.RESOURCES_AMNESIC_RICE]: getImgURL('item', 'item_amnesic_rice'),
	[EmotesResourcesEnum.RESOURCES_ANNIVERSARY_TICKET]: getImgURL('item', 'item_anniversary_ticket'),
	[EmotesResourcesEnum.RESOURCES_ANTI_GRAVE_SUIT]: getImgURL('item', 'item_anti_grave_suit'),
	[EmotesResourcesEnum.RESOURCES_ANTICHROMATIC]: getImgURL('item', 'item_antichromatic'),
	[EmotesResourcesEnum.RESOURCES_ANTIDOTE]: getImgURL('item', 'item_antidote'),
	[EmotesResourcesEnum.RESOURCES_BAMBOO_FRIEND]: getImgURL('item', 'item_bamboo_friend'),
	[EmotesResourcesEnum.RESOURCES_BANISHEMENT]: getImgURL('item', 'item_banishement'),
	[EmotesResourcesEnum.RESOURCES_BATTERING_RAM]: getImgURL('item', 'item_battering_ram'),
	[EmotesResourcesEnum.RESOURCES_BEER]: getImgURL('item', 'item_beer'),
	[EmotesResourcesEnum.RESOURCES_BOX_COMMON]: getImgURL('item', 'item_box_common'),
	[EmotesResourcesEnum.RESOURCES_BOX_EPIC]: getImgURL('item', 'item_box_epic'),
	[EmotesResourcesEnum.RESOURCES_BOX_LEGENDARY]: getImgURL('item', 'item_box_legendary'),
	[EmotesResourcesEnum.RESOURCES_BOX_RARE]: getImgURL('item', 'item_box_rare'),
	[EmotesResourcesEnum.RESOURCES_CANDLE_CARD]: getImgURL('item', 'item_candle_card'),
	[EmotesResourcesEnum.RESOURCES_CASTIVORE_EGG]: getImgURL('item', 'item_castivore_egg'),
	[EmotesResourcesEnum.RESOURCES_CASTIVORE_EGG_RARE]: getImgURL('item', 'item_castivore_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_CHRISTMAS_EGG]: getImgURL('item', 'item_christmas_egg'),
	[EmotesResourcesEnum.RESOURCES_CHRISTMAS_TICKET]: getImgURL('item', 'item_christmas_ticket'),
	[EmotesResourcesEnum.RESOURCES_CLOUD_BURGER]: getImgURL('item', 'item_cloud_burger'),
	[EmotesResourcesEnum.RESOURCES_CURSE_LOCKER]: getImgURL('item', 'item_curse_locker'),
	[EmotesResourcesEnum.RESOURCES_CUZCUSSIAN_MASK]: getImgURL('item', 'item_cuzcussian_mask'),
	[EmotesResourcesEnum.RESOURCES_DAILY_TICKET]: getImgURL('item', 'item_daily_ticket'),
	[EmotesResourcesEnum.RESOURCES_DANGER_DETECTOR]: getImgURL('item', 'item_danger_detector'),
	[EmotesResourcesEnum.RESOURCES_DEMON_TICKET]: getImgURL('item', 'item_demon_ticket'),
	[EmotesResourcesEnum.RESOURCES_DEVIL_OINTMENT]: getImgURL('item', 'item_devil_ointment'),
	[EmotesResourcesEnum.RESOURCES_DIMENSIONAL_POWDER]: getImgURL('item', 'item_dimensional_powder'),
	[EmotesResourcesEnum.RESOURCES_DINOZ_CUBE]: getImgURL('item', 'item_dinoz_cube'),
	[EmotesResourcesEnum.RESOURCES_EASTER_EGG]: getImgURL('item', 'item_easter_egg'),
	[EmotesResourcesEnum.RESOURCES_EGG_BLUE]: getImgURL('item', 'item_egg_blue'),
	[EmotesResourcesEnum.RESOURCES_EGG_RED]: getImgURL('item', 'item_egg_red'),
	[EmotesResourcesEnum.RESOURCES_ELIXIR]: getImgURL('item', 'item_elixir'),
	[EmotesResourcesEnum.RESOURCES_ELIXIR_OF_LIFE]: getImgURL('item', 'item_elixir_of_life'),
	[EmotesResourcesEnum.RESOURCES_EMBER]: getImgURL('item', 'item_ember'),
	[EmotesResourcesEnum.RESOURCES_EMPTY]: getImgURL('item', 'item_empty'),
	[EmotesResourcesEnum.RESOURCES_ENCHANTED_STEROID]: getImgURL('item', 'item_enchanted_steroid'),
	[EmotesResourcesEnum.RESOURCES_ENCYCLOPEDIA]: getImgURL('item', 'item_encyclopedia'),
	[EmotesResourcesEnum.RESOURCES_FEAR_FACTOR]: getImgURL('item', 'item_fear_factor'),
	[EmotesResourcesEnum.RESOURCES_FEROSS_EGG]: getImgURL('item', 'item_feross_egg'),
	[EmotesResourcesEnum.RESOURCES_FEROSS_EGG_CHRISTMAS]: getImgURL('item', 'item_feross_egg_christmas'),
	[EmotesResourcesEnum.RESOURCES_FIGHT_RATION]: getImgURL('item', 'item_fight_ration'),
	[EmotesResourcesEnum.RESOURCES_FIRE_CRACKER]: getImgURL('item', 'item_fire_cracker'),
	[EmotesResourcesEnum.RESOURCES_FIRE_SPHERE]: getImgURL('item', 'item_fire_sphere'),
	[EmotesResourcesEnum.RESOURCES_FRIENDLY_WHISTLE]: getImgURL('item', 'item_friendly_whistle'),
	[EmotesResourcesEnum.RESOURCES_FUCA_PILL]: getImgURL('item', 'item_fuca_pill'),
	[EmotesResourcesEnum.RESOURCES_GOBLIN_COSTUME]: getImgURL('item', 'item_goblin_costume'),
	[EmotesResourcesEnum.RESOURCES_GOBLIN_MERGUEZ]: getImgURL('item', 'item_goblin_merguez'),
	[EmotesResourcesEnum.RESOURCES_GOLD]: getImgURL('item', 'item_gold'),
	[EmotesResourcesEnum.RESOURCES_GORILLOZ_EGG]: getImgURL('item', 'item_gorilloz_egg'),
	[EmotesResourcesEnum.RESOURCES_GORILLOZ_EGG_RARE]: getImgURL('item', 'item_gorilloz_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_HIPPOCLAMP_EGG]: getImgURL('item', 'item_hippoclamp_egg'),
	[EmotesResourcesEnum.RESOURCES_HOT_BREAD]: getImgURL('item', 'item_hot_bread'),
	[EmotesResourcesEnum.RESOURCES_ICEDOC]: getImgURL('item', 'obj_icedoc'),
	[EmotesResourcesEnum.RESOURCES_KABUKI_EGG]: getImgURL('item', 'item_kabuki_egg'),
	[EmotesResourcesEnum.RESOURCES_KABUKI_EGG_RARE]: getImgURL('item', 'item_kabuki_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_LAND_OF_ASHES]: getImgURL('item', 'item_land_of_ashes'),
	[EmotesResourcesEnum.RESOURCES_LIFE_STEALER]: getImgURL('item', 'item_life_stealer'),
	[EmotesResourcesEnum.RESOURCES_LIGHTNING_SPHERE]: getImgURL('item', 'item_lightning_sphere'),
	[EmotesResourcesEnum.RESOURCES_LITTLE_PEPPER]: getImgURL('item', 'item_little_pepper'),
	[EmotesResourcesEnum.RESOURCES_LORIS_COSTUME]: getImgURL('item', 'item_loris_costume'),
	[EmotesResourcesEnum.RESOURCES_MAGIC_STAR]: getImgURL('item', 'item_magic_star'),
	[EmotesResourcesEnum.RESOURCES_MAHAMUTI_EGG]: getImgURL('item', 'item_mahamuti_egg'),
	[EmotesResourcesEnum.RESOURCES_MAHAMUTI_EGG_RARE]: getImgURL('item', 'item_mahamuti_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_MEAT_PIE]: getImgURL('item', 'item_meat_pie'),
	[EmotesResourcesEnum.RESOURCES_MONOCHROMATIC]: getImgURL('item', 'item_monochromatic'),
	[EmotesResourcesEnum.RESOURCES_MOUEFFE_EGG]: getImgURL('item', 'item_moueffe_egg'),
	[EmotesResourcesEnum.RESOURCES_MOUEFFE_EGG_RARE]: getImgURL('item', 'item_moueffe_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_NUAGOZ_EGG]: getImgURL('item', 'item_nuagoz_egg'),
	[EmotesResourcesEnum.RESOURCES_NUAGOZ_EGG_RARE]: getImgURL('item', 'item_nuagoz_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_PAMPLEBOUM]: getImgURL('item', 'item_pampleboum'),
	[EmotesResourcesEnum.RESOURCES_PAMPLEBOUM_PIT]: getImgURL('item', 'item_pampleboum_pit'),
	[EmotesResourcesEnum.RESOURCES_PIGMOU_EGG]: getImgURL('item', 'item_pigmou_egg'),
	[EmotesResourcesEnum.RESOURCES_PIGMOU_EGG_RARE]: getImgURL('item', 'item_pigmou_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_PIRHANOZ_IN_BAG]: getImgURL('item', 'item_pirhanoz_in_bag'),
	[EmotesResourcesEnum.RESOURCES_PLANAILLE_EGG]: getImgURL('item', 'item_planaille_egg'),
	[EmotesResourcesEnum.RESOURCES_PLANAILLE_EGG_RARE]: getImgURL('item', 'item_planaille_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_POISONITE_SHOT]: getImgURL('item', 'item_poisonite_shot'),
	[EmotesResourcesEnum.RESOURCES_PORTABLE_LOVE]: getImgURL('item', 'item_portable_love'),
	[EmotesResourcesEnum.RESOURCES_POTION_ANGEL]: getImgURL('item', 'item_potion_angel'),
	[EmotesResourcesEnum.RESOURCES_POTION_IRMA]: getImgURL('item', 'item_potion_irma'),
	[EmotesResourcesEnum.RESOURCES_PTEROZ_EGG]: getImgURL('item', 'item_pteroz_egg'),
	[EmotesResourcesEnum.RESOURCES_PTSAGE]: getImgURL('item', 'obj_ptsage'),
	[EmotesResourcesEnum.RESOURCES_QUETZU_EGG_RARE]: getImgURL('item', 'item_quetzu_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_REFRIGERATED_SHIELD]: getImgURL('item', 'item_refrigerated_shield'),
	[EmotesResourcesEnum.RESOURCES_ROCKY_EGG]: getImgURL('item', 'item_rocky_egg'),
	[EmotesResourcesEnum.RESOURCES_SANTAZ_EGG]: getImgURL('item', 'item_santaz_egg'),
	[EmotesResourcesEnum.RESOURCES_SANTAZ_EGG_RARE]: getImgURL('item', 'item_santaz_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_SCALE]: getImgURL('item', 'item_scale'),
	[EmotesResourcesEnum.RESOURCES_SIRAIN_EGG]: getImgURL('item', 'item_sirain_egg'),
	[EmotesResourcesEnum.RESOURCES_SIRAIN_EGG_RARE]: getImgURL('item', 'item_sirain_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_SMOG_EGG]: getImgURL('item', 'item_smog_egg'),
	[EmotesResourcesEnum.RESOURCES_SMOG_EGG_ANNIVERSARY]: getImgURL('item', 'item_smog_egg_anniversary'),
	[EmotesResourcesEnum.RESOURCES_SMOG_EGG_CHRISTMAS_BLUE]: getImgURL('item', 'item_smog_egg_christmas_blue'),
	[EmotesResourcesEnum.RESOURCES_SMOG_EGG_CHRISTMAS_GREEN]: getImgURL('item', 'item_smog_egg_christmas_green'),
	[EmotesResourcesEnum.RESOURCES_SORCERERS_STICK]: getImgURL('item', 'item_sorcerers_stick'),
	[EmotesResourcesEnum.RESOURCES_SOS_FLAME]: getImgURL('item', 'item_sos_flame'),
	[EmotesResourcesEnum.RESOURCES_SOS_HELMET]: getImgURL('item', 'item_sos_helmet'),
	[EmotesResourcesEnum.RESOURCES_SOUFFLET_EGG]: getImgURL('item', 'item_souffet_egg'),
	[EmotesResourcesEnum.RESOURCES_SPECIAL_POTION_IRMA]: getImgURL('item', 'item_special_potion_irma'),
	[EmotesResourcesEnum.RESOURCES_ST_ELMAS_FIRE]: getImgURL('item', 'item_st_elmas_fire'),
	[EmotesResourcesEnum.RESOURCES_STRONG_TEA]: getImgURL('item', 'item_strong_tea'),
	[EmotesResourcesEnum.RESOURCES_SURVIVING_RATION]: getImgURL('item', 'item_surviving_ration'),
	[EmotesResourcesEnum.RESOURCES_TEAR_OF_LIFE]: getImgURL('item', 'item_tear_of_life'),
	[EmotesResourcesEnum.RESOURCES_TEMPORAL_REDUCTION]: getImgURL('item', 'item_temporal_reduction'),
	[EmotesResourcesEnum.RESOURCES_TEMPORAL_STABILIZER]: getImgURL('item', 'item_temporal_stabilizer'),
	[EmotesResourcesEnum.RESOURCES_TICTAC_TICKET]: getImgURL('item', 'item_tictac_ticket'),
	[EmotesResourcesEnum.RESOURCES_TIK_BRACELET]: getImgURL('item', 'item_tik_bracelet'),
	[EmotesResourcesEnum.RESOURCES_TIME_MANIPULATOR]: getImgURL('item', 'item_time_manipulator'),
	[EmotesResourcesEnum.RESOURCES_TOUFUFU_BABY]: getImgURL('item', 'item_toufufu_baby'),
	[EmotesResourcesEnum.RESOURCES_TOUFUFU_BABY_RARE]: getImgURL('item', 'item_toufufu_baby_rare'),
	[EmotesResourcesEnum.RESOURCES_TREASURE_COUPON]: getImgURL('item', 'item_treasure_coupon'),
	[EmotesResourcesEnum.RESOURCES_TRICERAGNON_BABY]: getImgURL('item', 'item_triceragnon_baby'),
	[EmotesResourcesEnum.RESOURCES_UNDEFINED]: getImgURL('item', 'item_undefined'),
	[EmotesResourcesEnum.RESOURCES_UVAVU]: getImgURL('item', 'item_uvavu'),
	[EmotesResourcesEnum.RESOURCES_VEGETOX_COSTUME]: getImgURL('item', 'item_vegetox_costume'),
	[EmotesResourcesEnum.RESOURCES_VOID_SPHERE]: getImgURL('item', 'item_void_sphere'),
	[EmotesResourcesEnum.RESOURCES_WANWAN_BABY_RARE]: getImgURL('item', 'item_wanwan_baby_rare'),
	[EmotesResourcesEnum.RESOURCES_WANWAN_EGG]: getImgURL('item', 'item_wanwan_egg'),
	[EmotesResourcesEnum.RESOURCES_WATER_SPHERE]: getImgURL('item', 'item_water_sphere'),
	[EmotesResourcesEnum.RESOURCES_WINKS_EGG]: getImgURL('item', 'item_winks_egg'),
	[EmotesResourcesEnum.RESOURCES_WINKS_EGG_RARE]: getImgURL('item', 'item_winks_egg_rare'),
	[EmotesResourcesEnum.RESOURCES_WOOD_SPHERE]: getImgURL('item', 'item_wood_sphere'),
	[EmotesResourcesEnum.RESOURCES_ZIPPO]: getImgURL('item', 'item_zippo'),
	[EmotesResourcesEnum.RESOURCES_AN_GUILI_GUILILLE]: getImgURL('ingredients', 'an_guili_guilille'),
	[EmotesResourcesEnum.RESOURCES_BOLET_PHALISK_BLANC]: getImgURL('ingredients', 'bolet_phalisk_blanc'),
	[EmotesResourcesEnum.RESOURCES_BRAS_MECANIQUE]: getImgURL('ingredients', 'bras_mecanique'),
	[EmotesResourcesEnum.RESOURCES_BROCHE_EN_PARFAIT_ETAT]: getImgURL('ingredients', 'broche_en_parfait_etat'),
	[EmotesResourcesEnum.RESOURCES_CALISE_CISELE]: getImgURL('ingredients', 'calice_cisele'),
	[EmotesResourcesEnum.RESOURCES_COLLIER_KARAT]: getImgURL('ingredients', 'collier_karat'),
	[EmotesResourcesEnum.RESOURCES_CORNE_EN_CHOCOLAT]: getImgURL('ingredients', 'corne_en_chocolat'),
	[EmotesResourcesEnum.RESOURCES_DENT_DE_DOROGON]: getImgURL('ingredients', 'dent_de_dorogon'),
	[EmotesResourcesEnum.RESOURCES_ENERGIE_AIR]: getImgURL('ingredients', 'energie_air'),
	[EmotesResourcesEnum.RESOURCES_ENERGIE_BOIS]: getImgURL('ingredients', 'energie_bois'),
	[EmotesResourcesEnum.RESOURCES_ENERGIE_EAU]: getImgURL('ingredients', 'energie_eau'),
	[EmotesResourcesEnum.RESOURCES_ENERGIE_FEU]: getImgURL('ingredients', 'energie_feu'),
	[EmotesResourcesEnum.RESOURCES_ENERGIE_FOUDRE]: getImgURL('ingredients', 'energie_foudre'),
	[EmotesResourcesEnum.RESOURCES_FEUILLES_DE_PELINAE]: getImgURL('ingredients', 'feuilles_de_pelinae'),
	[EmotesResourcesEnum.RESOURCES_FLAUREOLE]: getImgURL('ingredients', 'flaureole'),
	[EmotesResourcesEnum.RESOURCES_FRAGMENT_DE_TEXTE_ANCIEN]: getImgURL('ingredients', 'fragment_de_texte_ancien'),
	[EmotesResourcesEnum.RESOURCES_GLOBULOS]: getImgURL('ingredients', 'globulos'),
	[EmotesResourcesEnum.RESOURCES_GRAINE_DE_DEVOREUSE]: getImgURL('ingredients', 'graine_de_devoreuse'),
	[EmotesResourcesEnum.RESOURCES_GRIFFES_ACEREES]: getImgURL('ingredients', 'griffes_acerees'),
	[EmotesResourcesEnum.RESOURCES_LANGUE_MONSTRUEUSE]: getImgURL('ingredients', 'langue_monstrueuse'),
	[EmotesResourcesEnum.RESOURCES_MEROU_LUJIDANE]: getImgURL('ingredients', 'merou_lujidane'),
	[EmotesResourcesEnum.RESOURCES_OEIL_VISQUEUX]: getImgURL('ingredients', 'oeil_visqueux'),
	[EmotesResourcesEnum.RESOURCES_ORCHIDEE_FANTASQUE]: getImgURL('ingredients', 'orchidee_fantasque'),
	[EmotesResourcesEnum.RESOURCES_POISSON_VENGEUR]: getImgURL('ingredients', 'poisson_vengeur'),
	[EmotesResourcesEnum.RESOURCES_POUSSE_SOMBRE]: getImgURL('ingredients', 'pousse_sombre'),
	[EmotesResourcesEnum.RESOURCES_RACINE_DE_FIGONICIA]: getImgURL('ingredients', 'racine_de_figonicia'),
	[EmotesResourcesEnum.RESOURCES_ROCHE_RADIO_ACTIVE]: getImgURL('ingredients', 'roche_radio_active'),
	[EmotesResourcesEnum.RESOURCES_SADIQUAE_MORDICUS]: getImgURL('ingredients', 'sadiquae_mordicus'),
	[EmotesResourcesEnum.RESOURCES_SILEX_TAILLE]: getImgURL('ingredients', 'silex_taille'),
	[EmotesResourcesEnum.RESOURCES_SPORE_ETHERAL]: getImgURL('ingredients', 'spore_etheral'),
	[EmotesResourcesEnum.RESOURCES_SUPER_POISSOn]: getImgURL('ingredients', 'super_poisson'),
	[EmotesResourcesEnum.RESOURCES_SUPERBE_COURONNE_ROYALE]: getImgURL('ingredients', 'superbe_couronne_royale'),
	[EmotesResourcesEnum.RESOURCES_TOUFFE_DE_FOURRURE]: getImgURL('ingredients', 'touffe_de_fourrure'),
	[EmotesResourcesEnum.RESOURCES_VIEIL_ANNEAU_PRECIEUX]: getImgURL('ingredients', 'vieil_anneau_precieux')
};
