import { getImgURL } from '../../../mixin/mixin';

export enum EmotesAchievementsEnum {
	ACHIEVEMENT_BEAUTY = 'beauty',
	ACHIEVEMENT_BELIUS = 'belius',
	ACHIEVEMENT_BGUM = 'bgum',
	ACHIEVEMENT_BRKPEL = 'brkpel',
	ACHIEVEMENT_CARD = 'card',
	ACHIEVEMENT_CAUSH = 'caush',
	ACHIEVEMENT_CHASSE = 'chasse',
	ACHIEVEMENT_CLANS = 'clans',
	ACHIEVEMENT_CUEILL = 'cueill',
	ACHIEVEMENT_DEATHS = 'deaths',
	ACHIEVEMENT_DEMON = 'demon',
	ACHIEVEMENT_DICARB = 'dicarb',
	ACHIEVEMENT_ENERGY = 'energy',
	ACHIEVEMENT_FMEDAL = 'fmedal',
	ACHIEVEMENT_FOUILL = 'fouill',
	ACHIEVEMENT_GDCATT = 'gdcatt',
	ACHIEVEMENT_GDCDEF = 'gdcdef',
	ACHIEVEMENT_HEALPV = 'healpv',
	ACHIEVEMENT_HIPPO = 'hippo',
	ACHIEVEMENT_KAURA = 'kaura',
	ACHIEVEMENT_KILLD = 'killd',
	ACHIEVEMENT_KILLM = 'killm',
	ACHIEVEMENT_LABOWI = 'labowi',
	ACHIEVEMENT_LVLUP = 'lvlup',
	ACHIEVEMENT_MAGNET = 'magnet',
	ACHIEVEMENT_MARKET = 'market',
	ACHIEVEMENT_MOVES = 'moves',
	ACHIEVEMENT_MSG = 'msg',
	ACHIEVEMENT_PAC = 'pac',
	ACHIEVEMENT_PDA = 'pda',
	ACHIEVEMENT_PDAYS = 'pdays',
	ACHIEVEMENT_PECHE = 'peche',
	ACHIEVEMENT_PERLE = 'perle',
	ACHIEVEMENT_PLUME = 'plume',
	ACHIEVEMENT_PMI = 'pmi',
	ACHIEVEMENT_PTEROZ = 'pteroz',
	ACHIEVEMENT_QUETZU = 'quetzu',
	ACHIEVEMENT_ROCKY = 'rocky',
	ACHIEVEMENT_SBUYER = 'sbuyer',
	ACHIEVEMENT_TAURUS = 'taurus',
	ACHIEVEMENT_TID1 = 'tid1',
	ACHIEVEMENT_TOUR = 'tour',
	ACHIEVEMENT_UPAIR = 'upair',
	ACHIEVEMENT_UPFIRE = 'upfire',
	ACHIEVEMENT_UPTHUN = 'upthun',
	ACHIEVEMENT_UPWATR = 'upwatr',
	ACHIEVEMENT_UPWOOD = 'upwood',
	ACHIEVEMENT_VENER = 'vener'
}

export const EmotesAchievementsAliases: { [index: string]: string } = {
	['beauty']: EmotesAchievementsEnum.ACHIEVEMENT_BEAUTY,
	['belius']: EmotesAchievementsEnum.ACHIEVEMENT_BELIUS,
	['bgum']: EmotesAchievementsEnum.ACHIEVEMENT_BGUM,
	['brkpel']: EmotesAchievementsEnum.ACHIEVEMENT_BRKPEL,
	['card']: EmotesAchievementsEnum.ACHIEVEMENT_CARD,
	['caush']: EmotesAchievementsEnum.ACHIEVEMENT_CAUSH,
	['chasse']: EmotesAchievementsEnum.ACHIEVEMENT_CHASSE,
	['clans']: EmotesAchievementsEnum.ACHIEVEMENT_CLANS,
	['cueill']: EmotesAchievementsEnum.ACHIEVEMENT_CUEILL,
	['deaths']: EmotesAchievementsEnum.ACHIEVEMENT_DEATHS,
	['demon']: EmotesAchievementsEnum.ACHIEVEMENT_DEMON,
	['dicarb']: EmotesAchievementsEnum.ACHIEVEMENT_DICARB,
	['energy']: EmotesAchievementsEnum.ACHIEVEMENT_ENERGY,
	['fmedal']: EmotesAchievementsEnum.ACHIEVEMENT_FMEDAL,
	['fouill']: EmotesAchievementsEnum.ACHIEVEMENT_FOUILL,
	['gdcatt']: EmotesAchievementsEnum.ACHIEVEMENT_GDCATT,
	['gdcdef']: EmotesAchievementsEnum.ACHIEVEMENT_GDCDEF,
	['healpv']: EmotesAchievementsEnum.ACHIEVEMENT_HEALPV,
	['hippo']: EmotesAchievementsEnum.ACHIEVEMENT_HIPPO,
	['kaura']: EmotesAchievementsEnum.ACHIEVEMENT_KAURA,
	['killd']: EmotesAchievementsEnum.ACHIEVEMENT_KILLD,
	['killm']: EmotesAchievementsEnum.ACHIEVEMENT_KILLM,
	['labowi']: EmotesAchievementsEnum.ACHIEVEMENT_LABOWI,
	['lvlup']: EmotesAchievementsEnum.ACHIEVEMENT_LVLUP,
	['magnet']: EmotesAchievementsEnum.ACHIEVEMENT_MAGNET,
	['market']: EmotesAchievementsEnum.ACHIEVEMENT_MARKET,
	['moves']: EmotesAchievementsEnum.ACHIEVEMENT_MOVES,
	['msg']: EmotesAchievementsEnum.ACHIEVEMENT_MSG,
	['pac']: EmotesAchievementsEnum.ACHIEVEMENT_PAC,
	['pda']: EmotesAchievementsEnum.ACHIEVEMENT_PDA,
	['pdays']: EmotesAchievementsEnum.ACHIEVEMENT_PDAYS,
	['peche']: EmotesAchievementsEnum.ACHIEVEMENT_PECHE,
	['perle']: EmotesAchievementsEnum.ACHIEVEMENT_PERLE,
	['plume']: EmotesAchievementsEnum.ACHIEVEMENT_PLUME,
	['pmi']: EmotesAchievementsEnum.ACHIEVEMENT_PMI,
	['pteroz']: EmotesAchievementsEnum.ACHIEVEMENT_PTEROZ,
	['quetzu']: EmotesAchievementsEnum.ACHIEVEMENT_QUETZU,
	['rocky']: EmotesAchievementsEnum.ACHIEVEMENT_ROCKY,
	['sbuyer']: EmotesAchievementsEnum.ACHIEVEMENT_SBUYER,
	['taurus']: EmotesAchievementsEnum.ACHIEVEMENT_TAURUS,
	['tid1']: EmotesAchievementsEnum.ACHIEVEMENT_TID1,
	['tour']: EmotesAchievementsEnum.ACHIEVEMENT_TOUR,
	['upair']: EmotesAchievementsEnum.ACHIEVEMENT_UPAIR,
	['upfire']: EmotesAchievementsEnum.ACHIEVEMENT_UPFIRE,
	['upthun']: EmotesAchievementsEnum.ACHIEVEMENT_UPTHUN,
	['upwatr']: EmotesAchievementsEnum.ACHIEVEMENT_UPWATR,
	['upwood']: EmotesAchievementsEnum.ACHIEVEMENT_UPWOOD,
	['vener']: EmotesAchievementsEnum.ACHIEVEMENT_VENER
};

export const EmotesAchievementsIcons: { [index: string]: string } = {
	[EmotesAchievementsEnum.ACHIEVEMENT_BEAUTY]: getImgURL('achievements', 'beauty'),
	[EmotesAchievementsEnum.ACHIEVEMENT_BELIUS]: getImgURL('achievements', 'belius'),
	[EmotesAchievementsEnum.ACHIEVEMENT_BGUM]: getImgURL('achievements', 'bgum'),
	[EmotesAchievementsEnum.ACHIEVEMENT_BRKPEL]: getImgURL('achievements', 'brkpel'),
	[EmotesAchievementsEnum.ACHIEVEMENT_CARD]: getImgURL('achievements', 'card'),
	[EmotesAchievementsEnum.ACHIEVEMENT_CAUSH]: getImgURL('achievements', 'caush'),
	[EmotesAchievementsEnum.ACHIEVEMENT_CHASSE]: getImgURL('achievements', 'chasse'),
	[EmotesAchievementsEnum.ACHIEVEMENT_CLANS]: getImgURL('achievements', 'clans'),
	[EmotesAchievementsEnum.ACHIEVEMENT_CUEILL]: getImgURL('achievements', 'cueill'),
	[EmotesAchievementsEnum.ACHIEVEMENT_DEATHS]: getImgURL('achievements', 'deaths'),
	[EmotesAchievementsEnum.ACHIEVEMENT_DEMON]: getImgURL('achievements', 'demon'),
	[EmotesAchievementsEnum.ACHIEVEMENT_DICARB]: getImgURL('achievements', 'dicarb'),
	[EmotesAchievementsEnum.ACHIEVEMENT_ENERGY]: getImgURL('achievements', 'energy'),
	[EmotesAchievementsEnum.ACHIEVEMENT_FMEDAL]: getImgURL('achievements', 'fmedal'),
	[EmotesAchievementsEnum.ACHIEVEMENT_FOUILL]: getImgURL('achievements', 'fouill'),
	[EmotesAchievementsEnum.ACHIEVEMENT_GDCATT]: getImgURL('achievements', 'gdcatt'),
	[EmotesAchievementsEnum.ACHIEVEMENT_GDCDEF]: getImgURL('achievements', 'gdcdef'),
	[EmotesAchievementsEnum.ACHIEVEMENT_HEALPV]: getImgURL('achievements', 'healpv'),
	[EmotesAchievementsEnum.ACHIEVEMENT_HIPPO]: getImgURL('achievements', 'hippo'),
	[EmotesAchievementsEnum.ACHIEVEMENT_KAURA]: getImgURL('achievements', 'kaura'),
	[EmotesAchievementsEnum.ACHIEVEMENT_KILLD]: getImgURL('achievements', 'killd'),
	[EmotesAchievementsEnum.ACHIEVEMENT_KILLM]: getImgURL('achievements', 'killm'),
	[EmotesAchievementsEnum.ACHIEVEMENT_LABOWI]: getImgURL('achievements', 'labowi'),
	[EmotesAchievementsEnum.ACHIEVEMENT_LVLUP]: getImgURL('achievements', 'lvlup'),
	[EmotesAchievementsEnum.ACHIEVEMENT_MAGNET]: getImgURL('achievements', 'magnet'),
	[EmotesAchievementsEnum.ACHIEVEMENT_MARKET]: getImgURL('achievements', 'market'),
	[EmotesAchievementsEnum.ACHIEVEMENT_MOVES]: getImgURL('achievements', 'moves'),
	[EmotesAchievementsEnum.ACHIEVEMENT_MSG]: getImgURL('achievements', 'msg'),
	[EmotesAchievementsEnum.ACHIEVEMENT_PAC]: getImgURL('achievements', 'pac'),
	[EmotesAchievementsEnum.ACHIEVEMENT_PDA]: getImgURL('achievements', 'pda'),
	[EmotesAchievementsEnum.ACHIEVEMENT_PDAYS]: getImgURL('achievements', 'pdays'),
	[EmotesAchievementsEnum.ACHIEVEMENT_PECHE]: getImgURL('achievements', 'peche'),
	[EmotesAchievementsEnum.ACHIEVEMENT_PERLE]: getImgURL('achievements', 'perle'),
	[EmotesAchievementsEnum.ACHIEVEMENT_PLUME]: getImgURL('achievements', 'plume'),
	[EmotesAchievementsEnum.ACHIEVEMENT_PMI]: getImgURL('achievements', 'pmi'),
	[EmotesAchievementsEnum.ACHIEVEMENT_PTEROZ]: getImgURL('achievements', 'pteroz'),
	[EmotesAchievementsEnum.ACHIEVEMENT_QUETZU]: getImgURL('achievements', 'quetzu'),
	[EmotesAchievementsEnum.ACHIEVEMENT_ROCKY]: getImgURL('achievements', 'rocky'),
	[EmotesAchievementsEnum.ACHIEVEMENT_SBUYER]: getImgURL('achievements', 'sbuyer'),
	[EmotesAchievementsEnum.ACHIEVEMENT_TAURUS]: getImgURL('achievements', 'taurus'),
	[EmotesAchievementsEnum.ACHIEVEMENT_TID1]: getImgURL('achievements', 'tid1'),
	[EmotesAchievementsEnum.ACHIEVEMENT_TOUR]: getImgURL('achievements', 'tour'),
	[EmotesAchievementsEnum.ACHIEVEMENT_UPAIR]: getImgURL('achievements', 'upair'),
	[EmotesAchievementsEnum.ACHIEVEMENT_UPFIRE]: getImgURL('achievements', 'upfire'),
	[EmotesAchievementsEnum.ACHIEVEMENT_UPTHUN]: getImgURL('achievements', 'upthun'),
	[EmotesAchievementsEnum.ACHIEVEMENT_UPWATR]: getImgURL('achievements', 'upwatr'),
	[EmotesAchievementsEnum.ACHIEVEMENT_UPWOOD]: getImgURL('achievements', 'upwood'),
	[EmotesAchievementsEnum.ACHIEVEMENT_VENER]: getImgURL('achievements', 'vener')
};
