import { RaceList } from '../dinoz/RaceList.mjs';

export enum formatName {
	UNCOMMON,
	COMMON,
	DUO,
	ANTI_META_4,
	ANTI_META_5,
	ALL_IN_5,
	ALL_IN_6,
	FIRE,
	WATER,
	AIR,
	LIGHTNING,
	WOOD,
	FFA,
	DEMONS
}

export type formatTeam = {
	name: string;
	teamSize?: number;
	raceMinimum?: number;
	poison?: boolean;
	levelLimit?: number;
	teamRace: RaceList[];
};

export const formatTID: Readonly<Record<formatName, formatTeam>> = {
	[formatName.UNCOMMON]: {
		name: 'uncommon',
		teamSize: 4,
		raceMinimum: 4,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.HIPPOCLAMP,
			RaceList.PTEROZ,
			RaceList.ROCKY,
			RaceList.QUETZU,
			RaceList.SANTAZ,
			RaceList.FEROSS,
			RaceList.KABUKI,
			RaceList.KABUKI_DEMON,
			RaceList.TOUFUFU,
			RaceList.MAHAMUTI,
			RaceList.SOUFFLET,
			RaceList.SMOG,
			RaceList.TRICERAGNON
		]
	},
	[formatName.COMMON]: {
		name: 'common',
		teamSize: 4,
		raceMinimum: 3,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.GORILLOZ,
			RaceList.WANWAN,
			RaceList.PIGMOU,
			RaceList.PLANAILLE,
			RaceList.SIRAIN,
			RaceList.MOUEFFE,
			RaceList.NUAGOZ,
			RaceList.WINKS,
			RaceList.CASTIVORE
		]
	},
	[formatName.DUO]: {
		name: 'duo',
		teamSize: 2,
		raceMinimum: 2,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.GORILLOZ,
			RaceList.WANWAN,
			RaceList.PIGMOU,
			RaceList.PLANAILLE,
			RaceList.SIRAIN,
			RaceList.MOUEFFE,
			RaceList.NUAGOZ,
			RaceList.WINKS,
			RaceList.CASTIVORE,
			RaceList.GORILLOZ_DEMON,
			RaceList.WANWAN_DEMON,
			RaceList.PIGMOU_DEMON,
			RaceList.PLANAILLE_DEMON,
			RaceList.MOUEFFE_DEMON,
			RaceList.WINKS_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.PTEROZ,
			RaceList.ROCKY,
			RaceList.QUETZU,
			RaceList.SANTAZ,
			RaceList.FEROSS,
			RaceList.KABUKI,
			RaceList.KABUKI_DEMON,
			RaceList.TOUFUFU,
			RaceList.MAHAMUTI,
			RaceList.SOUFFLET,
			RaceList.SMOG,
			RaceList.TRICERAGNON
		]
	},
	[formatName.ANTI_META_4]: {
		name: 'anti_meta_4',
		teamSize: 4,
		raceMinimum: 4,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.GORILLOZ,
			RaceList.PIGMOU,
			RaceList.PLANAILLE,
			RaceList.SIRAIN,
			RaceList.MOUEFFE,
			RaceList.NUAGOZ,
			RaceList.WINKS,
			RaceList.GORILLOZ_DEMON,
			RaceList.PIGMOU_DEMON,
			RaceList.PLANAILLE_DEMON,
			RaceList.MOUEFFE_DEMON,
			RaceList.WINKS_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.PTEROZ,
			RaceList.ROCKY,
			RaceList.QUETZU,
			RaceList.SANTAZ,
			RaceList.FEROSS,
			RaceList.KABUKI,
			RaceList.KABUKI_DEMON,
			RaceList.SOUFFLET,
			RaceList.SMOG
		]
	},
	[formatName.ANTI_META_5]: {
		name: 'anti_meta_5',
		teamSize: 5,
		raceMinimum: 5,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.GORILLOZ,
			RaceList.PIGMOU,
			RaceList.PLANAILLE,
			RaceList.SIRAIN,
			RaceList.MOUEFFE,
			RaceList.NUAGOZ,
			RaceList.WINKS,
			RaceList.GORILLOZ_DEMON,
			RaceList.PIGMOU_DEMON,
			RaceList.PLANAILLE_DEMON,
			RaceList.MOUEFFE_DEMON,
			RaceList.WINKS_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.PTEROZ,
			RaceList.ROCKY,
			RaceList.QUETZU,
			RaceList.SANTAZ,
			RaceList.FEROSS,
			RaceList.KABUKI,
			RaceList.KABUKI_DEMON,
			RaceList.SOUFFLET,
			RaceList.SMOG
		]
	},
	[formatName.ALL_IN_5]: {
		name: 'all_in_5',
		teamSize: 5,
		raceMinimum: 5,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.GORILLOZ,
			RaceList.WANWAN,
			RaceList.PIGMOU,
			RaceList.PLANAILLE,
			RaceList.SIRAIN,
			RaceList.MOUEFFE,
			RaceList.NUAGOZ,
			RaceList.WINKS,
			RaceList.CASTIVORE,
			RaceList.GORILLOZ_DEMON,
			RaceList.WANWAN_DEMON,
			RaceList.PIGMOU_DEMON,
			RaceList.PLANAILLE_DEMON,
			RaceList.MOUEFFE_DEMON,
			RaceList.WINKS_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.PTEROZ,
			RaceList.ROCKY,
			RaceList.QUETZU,
			RaceList.SANTAZ,
			RaceList.FEROSS,
			RaceList.KABUKI,
			RaceList.KABUKI_DEMON,
			RaceList.TOUFUFU,
			RaceList.MAHAMUTI,
			RaceList.SOUFFLET,
			RaceList.SMOG,
			RaceList.TRICERAGNON
		]
	},
	[formatName.ALL_IN_6]: {
		name: 'all_in_6',
		teamSize: 6,
		raceMinimum: 6,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.GORILLOZ,
			RaceList.WANWAN,
			RaceList.PIGMOU,
			RaceList.PLANAILLE,
			RaceList.SIRAIN,
			RaceList.MOUEFFE,
			RaceList.NUAGOZ,
			RaceList.WINKS,
			RaceList.CASTIVORE,
			RaceList.GORILLOZ_DEMON,
			RaceList.WANWAN_DEMON,
			RaceList.PIGMOU_DEMON,
			RaceList.PLANAILLE_DEMON,
			RaceList.MOUEFFE_DEMON,
			RaceList.WINKS_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.PTEROZ,
			RaceList.ROCKY,
			RaceList.QUETZU,
			RaceList.SANTAZ,
			RaceList.FEROSS,
			RaceList.KABUKI,
			RaceList.KABUKI_DEMON,
			RaceList.TOUFUFU,
			RaceList.MAHAMUTI,
			RaceList.SOUFFLET,
			RaceList.SMOG,
			RaceList.TRICERAGNON
		]
	},
	[formatName.FIRE]: {
		name: 'fire',
		teamSize: 3,
		raceMinimum: 3,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.PIGMOU,
			RaceList.MOUEFFE,
			RaceList.PIGMOU_DEMON,
			RaceList.MOUEFFE_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.PTEROZ,
			RaceList.ROCKY,
			RaceList.QUETZU,
			RaceList.FEROSS,
			RaceList.SMOG,
			RaceList.TRICERAGNON
		]
	},
	[formatName.WATER]: {
		name: 'water',
		teamSize: 3,
		raceMinimum: 3,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.SIRAIN,
			RaceList.NUAGOZ,
			RaceList.WINKS,
			RaceList.WINKS_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.QUETZU,
			RaceList.KABUKI,
			RaceList.KABUKI_DEMON,
			RaceList.MAHAMUTI
		]
	},
	[formatName.AIR]: {
		name: 'air',
		teamSize: 3,
		raceMinimum: 3,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.PLANAILLE,
			RaceList.NUAGOZ,
			RaceList.CASTIVORE,
			RaceList.PLANAILLE_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.PTEROZ,
			RaceList.SANTAZ,
			RaceList.KABUKI,
			RaceList.KABUKI_DEMON,
			RaceList.SOUFFLET,
			RaceList.SMOG
		]
	},
	[formatName.LIGHTNING]: {
		name: 'lightning',
		teamSize: 3,
		raceMinimum: 3,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.WANWAN,
			RaceList.PLANAILLE,
			RaceList.NUAGOZ,
			RaceList.WINKS,
			RaceList.WANWAN_DEMON,
			RaceList.PLANAILLE_DEMON,
			RaceList.WINKS_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.ROCKY,
			RaceList.TOUFUFU,
			RaceList.SMOG
		]
	},
	[formatName.WOOD]: {
		name: 'wood',
		teamSize: 3,
		raceMinimum: 2,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.GORILLOZ,
			RaceList.WANWAN,
			RaceList.CASTIVORE,
			RaceList.GORILLOZ_DEMON,
			RaceList.WANWAN_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.FEROSS,
			RaceList.TOUFUFU,
			RaceList.MAHAMUTI,
			RaceList.TRICERAGNON
		]
	},
	[formatName.FFA]: {
		name: 'ffa',
		teamSize: 6,
		teamRace: [
			RaceList.GORILLOZ,
			RaceList.WANWAN,
			RaceList.PIGMOU,
			RaceList.PLANAILLE,
			RaceList.SIRAIN,
			RaceList.MOUEFFE,
			RaceList.NUAGOZ,
			RaceList.WINKS,
			RaceList.CASTIVORE,
			RaceList.GORILLOZ_DEMON,
			RaceList.WANWAN_DEMON,
			RaceList.PIGMOU_DEMON,
			RaceList.PLANAILLE_DEMON,
			RaceList.MOUEFFE_DEMON,
			RaceList.WINKS_DEMON,
			RaceList.HIPPOCLAMP,
			RaceList.PTEROZ,
			RaceList.ROCKY,
			RaceList.QUETZU,
			RaceList.SANTAZ,
			RaceList.FEROSS,
			RaceList.KABUKI,
			RaceList.KABUKI_DEMON,
			RaceList.TOUFUFU,
			RaceList.MAHAMUTI,
			RaceList.SOUFFLET,
			RaceList.SMOG,
			RaceList.TRICERAGNON
		]
	},
	[formatName.DEMONS]: {
		name: 'demons',
		teamSize: 4,
		raceMinimum: 3,
		poison: true,
		levelLimit: 50,
		teamRace: [
			RaceList.GORILLOZ_DEMON,
			RaceList.WANWAN_DEMON,
			RaceList.PIGMOU_DEMON,
			RaceList.PLANAILLE_DEMON,
			RaceList.MOUEFFE_DEMON,
			RaceList.WINKS_DEMON
		]
	}
};
