import { RaceEnum } from '../enums/RaceEnum.mjs';

export enum formatName {
	UNCOMMON,
	COMMON,
	DUO,
	ANTI_META_4,
	ANTI_META_5,
	ALL_IN_5,
	ALL_IN_6,
	FIRE,
	WATER,
	AIR,
	LIGHTNING,
	WOOD,
	FFA,
	DEMONS
}

export type formatTeam = {
	name: string;
	teamSize?: number;
	raceMinimum?: number;
	poison?: boolean;
	levelLimit?: number;
	teamRace: RaceEnum[];
};

export const formatTID: Readonly<Record<formatName, formatTeam>> = {
	[formatName.UNCOMMON]: {
		name: 'uncommon',
		teamSize: 4,
		raceMinimum: 4,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.HIPPOCLAMP,
			RaceEnum.PTEROZ,
			RaceEnum.ROCKY,
			RaceEnum.QUETZU,
			RaceEnum.SANTAZ,
			RaceEnum.FEROSS,
			RaceEnum.KABUKI,
			RaceEnum.TOUFUFU,
			RaceEnum.MAHAMUTI,
			RaceEnum.SOUFFLET,
			RaceEnum.SMOG,
			RaceEnum.TRICERAGNON
		]
	},
	[formatName.COMMON]: {
		name: 'common',
		teamSize: 4,
		raceMinimum: 3,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.GORILLOZ,
			RaceEnum.WANWAN,
			RaceEnum.PIGMOU,
			RaceEnum.PLANAILLE,
			RaceEnum.SIRAIN,
			RaceEnum.MOUEFFE,
			RaceEnum.NUAGOZ,
			RaceEnum.WINKS,
			RaceEnum.CASTIVORE
		]
	},
	[formatName.DUO]: {
		name: 'duo',
		teamSize: 2,
		raceMinimum: 2,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.GORILLOZ,
			RaceEnum.WANWAN,
			RaceEnum.PIGMOU,
			RaceEnum.PLANAILLE,
			RaceEnum.SIRAIN,
			RaceEnum.MOUEFFE,
			RaceEnum.NUAGOZ,
			RaceEnum.WINKS,
			RaceEnum.CASTIVORE,
			RaceEnum.GORILLOZ_DEMON,
			RaceEnum.WANWAN_DEMON,
			RaceEnum.PIGMOU_DEMON,
			RaceEnum.PLANAILLE_DEMON,
			RaceEnum.MOUEFFE_DEMON,
			RaceEnum.WINKS_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.PTEROZ,
			RaceEnum.ROCKY,
			RaceEnum.QUETZU,
			RaceEnum.SANTAZ,
			RaceEnum.FEROSS,
			RaceEnum.KABUKI,
			RaceEnum.KABUKI_DEMON,
			RaceEnum.TOUFUFU,
			RaceEnum.MAHAMUTI,
			RaceEnum.SOUFFLET,
			RaceEnum.SMOG,
			RaceEnum.TRICERAGNON
		]
	},
	[formatName.ANTI_META_4]: {
		name: 'anti_meta_4',
		teamSize: 4,
		raceMinimum: 4,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.GORILLOZ,
			RaceEnum.PIGMOU,
			RaceEnum.PLANAILLE,
			RaceEnum.SIRAIN,
			RaceEnum.MOUEFFE,
			RaceEnum.NUAGOZ,
			RaceEnum.WINKS,
			RaceEnum.GORILLOZ_DEMON,
			RaceEnum.PIGMOU_DEMON,
			RaceEnum.PLANAILLE_DEMON,
			RaceEnum.MOUEFFE_DEMON,
			RaceEnum.WINKS_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.PTEROZ,
			RaceEnum.ROCKY,
			RaceEnum.QUETZU,
			RaceEnum.SANTAZ,
			RaceEnum.FEROSS,
			RaceEnum.KABUKI,
			RaceEnum.KABUKI_DEMON,
			RaceEnum.SOUFFLET,
			RaceEnum.SMOG
		]
	},
	[formatName.ANTI_META_5]: {
		name: 'anti_meta_5',
		teamSize: 5,
		raceMinimum: 5,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.GORILLOZ,
			RaceEnum.PIGMOU,
			RaceEnum.PLANAILLE,
			RaceEnum.SIRAIN,
			RaceEnum.MOUEFFE,
			RaceEnum.NUAGOZ,
			RaceEnum.WINKS,
			RaceEnum.GORILLOZ_DEMON,
			RaceEnum.PIGMOU_DEMON,
			RaceEnum.PLANAILLE_DEMON,
			RaceEnum.MOUEFFE_DEMON,
			RaceEnum.WINKS_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.PTEROZ,
			RaceEnum.ROCKY,
			RaceEnum.QUETZU,
			RaceEnum.SANTAZ,
			RaceEnum.FEROSS,
			RaceEnum.KABUKI,
			RaceEnum.KABUKI_DEMON,
			RaceEnum.SOUFFLET,
			RaceEnum.SMOG
		]
	},
	[formatName.ALL_IN_5]: {
		name: 'all_in_5',
		teamSize: 5,
		raceMinimum: 5,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.GORILLOZ,
			RaceEnum.WANWAN,
			RaceEnum.PIGMOU,
			RaceEnum.PLANAILLE,
			RaceEnum.SIRAIN,
			RaceEnum.MOUEFFE,
			RaceEnum.NUAGOZ,
			RaceEnum.WINKS,
			RaceEnum.CASTIVORE,
			RaceEnum.GORILLOZ_DEMON,
			RaceEnum.WANWAN_DEMON,
			RaceEnum.PIGMOU_DEMON,
			RaceEnum.PLANAILLE_DEMON,
			RaceEnum.MOUEFFE_DEMON,
			RaceEnum.WINKS_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.PTEROZ,
			RaceEnum.ROCKY,
			RaceEnum.QUETZU,
			RaceEnum.SANTAZ,
			RaceEnum.FEROSS,
			RaceEnum.KABUKI,
			RaceEnum.KABUKI_DEMON,
			RaceEnum.TOUFUFU,
			RaceEnum.MAHAMUTI,
			RaceEnum.SOUFFLET,
			RaceEnum.SMOG,
			RaceEnum.TRICERAGNON
		]
	},
	[formatName.ALL_IN_6]: {
		name: 'all_in_6',
		teamSize: 6,
		raceMinimum: 6,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.GORILLOZ,
			RaceEnum.WANWAN,
			RaceEnum.PIGMOU,
			RaceEnum.PLANAILLE,
			RaceEnum.SIRAIN,
			RaceEnum.MOUEFFE,
			RaceEnum.NUAGOZ,
			RaceEnum.WINKS,
			RaceEnum.CASTIVORE,
			RaceEnum.GORILLOZ_DEMON,
			RaceEnum.WANWAN_DEMON,
			RaceEnum.PIGMOU_DEMON,
			RaceEnum.PLANAILLE_DEMON,
			RaceEnum.MOUEFFE_DEMON,
			RaceEnum.WINKS_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.PTEROZ,
			RaceEnum.ROCKY,
			RaceEnum.QUETZU,
			RaceEnum.SANTAZ,
			RaceEnum.FEROSS,
			RaceEnum.KABUKI,
			RaceEnum.KABUKI_DEMON,
			RaceEnum.TOUFUFU,
			RaceEnum.MAHAMUTI,
			RaceEnum.SOUFFLET,
			RaceEnum.SMOG,
			RaceEnum.TRICERAGNON
		]
	},
	[formatName.FIRE]: {
		name: 'fire',
		teamSize: 3,
		raceMinimum: 3,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.PIGMOU,
			RaceEnum.MOUEFFE,
			RaceEnum.PIGMOU_DEMON,
			RaceEnum.MOUEFFE_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.PTEROZ,
			RaceEnum.ROCKY,
			RaceEnum.QUETZU,
			RaceEnum.FEROSS,
			RaceEnum.SMOG,
			RaceEnum.TRICERAGNON
		]
	},
	[formatName.WATER]: {
		name: 'water',
		teamSize: 3,
		raceMinimum: 3,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.SIRAIN,
			RaceEnum.NUAGOZ,
			RaceEnum.WINKS,
			RaceEnum.WINKS_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.QUETZU,
			RaceEnum.KABUKI,
			RaceEnum.KABUKI_DEMON,
			RaceEnum.MAHAMUTI
		]
	},
	[formatName.AIR]: {
		name: 'air',
		teamSize: 3,
		raceMinimum: 3,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.PLANAILLE,
			RaceEnum.NUAGOZ,
			RaceEnum.CASTIVORE,
			RaceEnum.PLANAILLE_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.PTEROZ,
			RaceEnum.SANTAZ,
			RaceEnum.KABUKI,
			RaceEnum.KABUKI_DEMON,
			RaceEnum.SOUFFLET,
			RaceEnum.SMOG
		]
	},
	[formatName.LIGHTNING]: {
		name: 'lightning',
		teamSize: 3,
		raceMinimum: 3,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.WANWAN,
			RaceEnum.PLANAILLE,
			RaceEnum.NUAGOZ,
			RaceEnum.WINKS,
			RaceEnum.WANWAN_DEMON,
			RaceEnum.PLANAILLE_DEMON,
			RaceEnum.WINKS_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.ROCKY,
			RaceEnum.TOUFUFU,
			RaceEnum.SMOG
		]
	},
	[formatName.WOOD]: {
		name: 'wood',
		teamSize: 3,
		raceMinimum: 2,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.GORILLOZ,
			RaceEnum.WANWAN,
			RaceEnum.CASTIVORE,
			RaceEnum.GORILLOZ_DEMON,
			RaceEnum.WANWAN_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.FEROSS,
			RaceEnum.TOUFUFU,
			RaceEnum.MAHAMUTI,
			RaceEnum.TRICERAGNON
		]
	},
	[formatName.FFA]: {
		name: 'ffa',
		teamSize: 6,
		teamRace: [
			RaceEnum.GORILLOZ,
			RaceEnum.WANWAN,
			RaceEnum.PIGMOU,
			RaceEnum.PLANAILLE,
			RaceEnum.SIRAIN,
			RaceEnum.MOUEFFE,
			RaceEnum.NUAGOZ,
			RaceEnum.WINKS,
			RaceEnum.CASTIVORE,
			RaceEnum.GORILLOZ_DEMON,
			RaceEnum.WANWAN_DEMON,
			RaceEnum.PIGMOU_DEMON,
			RaceEnum.PLANAILLE_DEMON,
			RaceEnum.MOUEFFE_DEMON,
			RaceEnum.WINKS_DEMON,
			RaceEnum.HIPPOCLAMP,
			RaceEnum.PTEROZ,
			RaceEnum.ROCKY,
			RaceEnum.QUETZU,
			RaceEnum.SANTAZ,
			RaceEnum.FEROSS,
			RaceEnum.KABUKI,
			RaceEnum.KABUKI_DEMON,
			RaceEnum.TOUFUFU,
			RaceEnum.MAHAMUTI,
			RaceEnum.SOUFFLET,
			RaceEnum.SMOG,
			RaceEnum.TRICERAGNON
		]
	},
	[formatName.DEMONS]: {
		name: 'demons',
		teamSize: 4,
		raceMinimum: 3,
		poison: true,
		//levelLimit: 50,
		teamRace: [
			RaceEnum.GORILLOZ_DEMON,
			RaceEnum.WANWAN_DEMON,
			RaceEnum.PIGMOU_DEMON,
			RaceEnum.PLANAILLE_DEMON,
			RaceEnum.MOUEFFE_DEMON,
			RaceEnum.WINKS_DEMON
		]
	}
};
