// ES module wrapper for Prisma enums
// Auto-generated by generate-enums-wrapper.js - do not edit manually
// This file is regenerated every time you run 'prisma generate'

export const UnavailableReason = {
  frozen: 'frozen',
  sacrificed: 'sacrificed',
  selling: 'selling',
  superdom: 'superdom',
  resting: 'resting',
  unfreezing: 'unfreezing'
};

export const NewsType = {
  update: 'update',
  information: 'information',
  war: 'war',
  war_mana: 'war_mana',
  championship: 'championship',
  tid_start: 'tid_start',
  tid_end: 'tid_end',
  event_christmas: 'event_christmas',
  story: 'story',
  announce: 'announce'
};

export const AdminRole = {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  PLAYER: 'PLAYER',
  BETA: 'BETA',
  AMPHI: 'AMPHI'
};

export const Lang = {
  fr: 'fr',
  en: 'en',
  de: 'de',
  es: 'es'
};

export const OfferStatus = {
  ONGOING: 'ONGOING',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED',
  CLAIMED: 'CLAIMED'
};

export const LogType = {
  ItemUsed: 'ItemUsed',
  ItemBought: 'ItemBought',
  GoldWon: 'GoldWon',
  GoldLost: 'GoldLost',
  Move: 'Move',
  LevelUp: 'LevelUp',
  Fight: 'Fight',
  Death: 'Death',
  Revive: 'Revive',
  MissionStep: 'MissionStep',
  MissionFinished: 'MissionFinished',
  MissionCanceled: 'MissionCanceled',
  Gather: 'Gather',
  CreateDinoz: 'CreateDinoz',
  ChangeDinozOrder: 'ChangeDinozOrder',
  AdminUpdateDinoz: 'AdminUpdateDinoz',
  AdminAddStatus: 'AdminAddStatus',
  AdminRemoveStatus: 'AdminRemoveStatus',
  AdminAddSkill: 'AdminAddSkill',
  AdminRemoveSkill: 'AdminRemoveSkill',
  AdminAddUnlockableSkill: 'AdminAddUnlockableSkill',
  AdminRemoveUnlockableSkill: 'AdminRemoveUnlockableSkill',
  AdminAddMoney: 'AdminAddMoney',
  AdminRemoveMoney: 'AdminRemoveMoney',
  AdminAddReward: 'AdminAddReward',
  AdminRemoveReward: 'AdminRemoveReward',
  AdminAddItem: 'AdminAddItem',
  AdminRemoveItem: 'AdminRemoveItem',
  AdminAddIngredient: 'AdminAddIngredient',
  AdminRemoveIngredient: 'AdminRemoveIngredient',
  AdminUpdateQuest: 'AdminUpdateQuest',
  AdminUpdatePlayer: 'AdminUpdatePlayer',
  AdminUpdateSecret: 'AdminUpdateSecret',
  AdminUpdateClan: 'AdminUpdateClan',
  IngredientSold: 'IngredientSold',
  XPEarned: 'XPEarned',
  HPLost: 'HPLost',
  PlayerCreated: 'PlayerCreated',
  PlayerConnected: 'PlayerConnected',
  LBDone: 'LBDone',
  OfferNew: 'OfferNew',
  OfferBid: 'OfferBid',
  OfferCancelled: 'OfferCancelled',
  OfferExpired: 'OfferExpired',
  OfferWon: 'OfferWon',
  GridFinished: 'GridFinished',
  ItemFound: 'ItemFound'
};

export const PantheonMotif = {
  race: 'race',
  epic: 'epic'
};

export const ModerationReason = {
  multi: 'multi',
  dinozName: 'dinozName',
  accountName: 'accountName',
  avatar: 'avatar',
  customText: 'customText'
};

export const ModerationAction = {
  closed: 'closed',
  warning: 'warning',
  shortBan: 'shortBan',
  mediumBan: 'mediumBan',
  longBan: 'longBan',
  infiniteBan: 'infiniteBan'
};

export const NotificationSeverity = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  error: 'error',
  offerWon: 'offerWon',
  offerExpired: 'offerExpired',
  offerEnded: 'offerEnded',
  ban: 'ban',
  reward: 'reward',
  scenario: 'scenario',
  event: 'event',
  newClanApply: 'newClanApply',
  clanApplyAccepted: 'clanApplyAccepted',
  message: 'message'
};

export const GameDinozUsage = {
  FBTournament: 'FBTournament'
};

export const EventType = {
  CHRISTMAS: 'CHRISTMAS',
  VALENTINE: 'VALENTINE'
};

export const ServerAction = {
  checkBans: 'checkBans',
  healRestingDinoz: 'healRestingDinoz',
  itinerantMerchant: 'itinerantMerchant',
  midnightReset: 'midnightReset'
};

export const $Enums = {
  UnavailableReason,
  NewsType,
  AdminRole,
  Lang,
  OfferStatus,
  LogType,
  PantheonMotif,
  ModerationReason,
  ModerationAction,
  NotificationSeverity,
  GameDinozUsage,
  EventType,
  ServerAction
};
