// TypeScript definitions for Prisma enums
// Auto-generated by generate-enums-wrapper.js - do not edit manually
// This file is regenerated every time you run 'prisma generate'

export const UnavailableReason: {
  frozen: 'frozen',
  sacrificed: 'sacrificed',
  selling: 'selling',
  superdom: 'superdom',
  resting: 'resting',
  unfreezing: 'unfreezing'
};

export type UnavailableReason = typeof UnavailableReason[keyof typeof UnavailableReason];

export const NewsType: {
  update: 'update',
  information: 'information',
  war: 'war',
  war_mana: 'war_mana',
  championship: 'championship',
  tid_start: 'tid_start',
  tid_end: 'tid_end',
  event_christmas: 'event_christmas',
  story: 'story',
  announce: 'announce'
};

export type NewsType = typeof NewsType[keyof typeof NewsType];

export const AdminRole: {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  PLAYER: 'PLAYER',
  BETA: 'BETA',
  AMPHI: 'AMPHI'
};

export type AdminRole = typeof AdminRole[keyof typeof AdminRole];

export const Lang: {
  fr: 'fr',
  en: 'en',
  de: 'de',
  es: 'es'
};

export type Lang = typeof Lang[keyof typeof Lang];

export const OfferStatus: {
  ONGOING: 'ONGOING',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED',
  CLAIMED: 'CLAIMED'
};

export type OfferStatus = typeof OfferStatus[keyof typeof OfferStatus];

export const LogType: {
  ItemUsed: 'ItemUsed',
  ItemBought: 'ItemBought',
  GoldWon: 'GoldWon',
  GoldLost: 'GoldLost',
  Move: 'Move',
  LevelUp: 'LevelUp',
  Fight: 'Fight',
  Death: 'Death',
  Revive: 'Revive',
  MissionStep: 'MissionStep',
  MissionFinished: 'MissionFinished',
  MissionCanceled: 'MissionCanceled',
  Gather: 'Gather',
  CreateDinoz: 'CreateDinoz',
  ChangeDinozOrder: 'ChangeDinozOrder',
  AdminUpdateDinoz: 'AdminUpdateDinoz',
  AdminAddStatus: 'AdminAddStatus',
  AdminRemoveStatus: 'AdminRemoveStatus',
  AdminAddSkill: 'AdminAddSkill',
  AdminRemoveSkill: 'AdminRemoveSkill',
  AdminAddUnlockableSkill: 'AdminAddUnlockableSkill',
  AdminRemoveUnlockableSkill: 'AdminRemoveUnlockableSkill',
  AdminAddMoney: 'AdminAddMoney',
  AdminRemoveMoney: 'AdminRemoveMoney',
  AdminAddReward: 'AdminAddReward',
  AdminRemoveReward: 'AdminRemoveReward',
  AdminAddItem: 'AdminAddItem',
  AdminRemoveItem: 'AdminRemoveItem',
  AdminAddIngredient: 'AdminAddIngredient',
  AdminRemoveIngredient: 'AdminRemoveIngredient',
  AdminUpdateQuest: 'AdminUpdateQuest',
  AdminUpdatePlayer: 'AdminUpdatePlayer',
  AdminUpdateSecret: 'AdminUpdateSecret',
  IngredientSold: 'IngredientSold',
  XPEarned: 'XPEarned',
  HPLost: 'HPLost',
  PlayerCreated: 'PlayerCreated',
  PlayerConnected: 'PlayerConnected',
  LBDone: 'LBDone',
  OfferNew: 'OfferNew',
  OfferBid: 'OfferBid',
  OfferCancelled: 'OfferCancelled',
  OfferExpired: 'OfferExpired',
  OfferWon: 'OfferWon',
  GridFinished: 'GridFinished',
  ItemFound: 'ItemFound'
};

export type LogType = typeof LogType[keyof typeof LogType];

export const PantheonMotif: {
  race: 'race',
  epic: 'epic'
};

export type PantheonMotif = typeof PantheonMotif[keyof typeof PantheonMotif];

export const ModerationReason: {
  multi: 'multi',
  dinozName: 'dinozName',
  accountName: 'accountName',
  avatar: 'avatar',
  customText: 'customText'
};

export type ModerationReason = typeof ModerationReason[keyof typeof ModerationReason];

export const ModerationAction: {
  closed: 'closed',
  warning: 'warning',
  shortBan: 'shortBan',
  mediumBan: 'mediumBan',
  longBan: 'longBan',
  infiniteBan: 'infiniteBan'
};

export type ModerationAction = typeof ModerationAction[keyof typeof ModerationAction];

export const NotificationSeverity: {
  info: 'info',
  success: 'success',
  warning: 'warning',
  error: 'error',
  offerWon: 'offerWon',
  offerExpired: 'offerExpired',
  offerEnded: 'offerEnded',
  ban: 'ban',
  reward: 'reward',
  scenario: 'scenario',
  event: 'event',
  newClanApply: 'newClanApply',
  message: 'message'
};

export type NotificationSeverity = typeof NotificationSeverity[keyof typeof NotificationSeverity];

export const GameDinozUsage: {
  FBTournament: 'FBTournament'
};

export type GameDinozUsage = typeof GameDinozUsage[keyof typeof GameDinozUsage];

export const EventType: {
  CHRISTMAS: 'CHRISTMAS',
  VALENTINE: 'VALENTINE'
};

export type EventType = typeof EventType[keyof typeof EventType];

export const ServerAction: {
  checkBans: 'checkBans',
  healRestingDinoz: 'healRestingDinoz',
  itinerantMerchant: 'itinerantMerchant',
  midnightReset: 'midnightReset'
};

export type ServerAction = typeof ServerAction[keyof typeof ServerAction];

export const $Enums: {
  UnavailableReason: typeof UnavailableReason,
  NewsType: typeof NewsType,
  AdminRole: typeof AdminRole,
  Lang: typeof Lang,
  OfferStatus: typeof OfferStatus,
  LogType: typeof LogType,
  PantheonMotif: typeof PantheonMotif,
  ModerationReason: typeof ModerationReason,
  ModerationAction: typeof ModerationAction,
  NotificationSeverity: typeof NotificationSeverity,
  GameDinozUsage: typeof GameDinozUsage,
  EventType: typeof EventType,
  ServerAction: typeof ServerAction
};
