// TypeScript definitions for Prisma enums
// Auto-generated by generate-enums-wrapper.js - do not edit manually
// This file is regenerated every time you run 'prisma generate'

export const UnavailableReason: {
  readonly frozen: 'frozen';
  readonly sacrificed: 'sacrificed';
  readonly selling: 'selling';
  readonly superdom: 'superdom';
  readonly resting: 'resting';
  readonly unfreezing: 'unfreezing';
  readonly defending: 'defending';
  readonly restingAttack: 'restingAttack'
};

export namespace UnavailableReason {
  export type frozen = 'frozen';
  export type sacrificed = 'sacrificed';
  export type selling = 'selling';
  export type superdom = 'superdom';
  export type resting = 'resting';
  export type unfreezing = 'unfreezing';
  export type defending = 'defending';
  export type restingAttack = 'restingAttack'
}

export type UnavailableReason = typeof UnavailableReason[keyof typeof UnavailableReason];

export const NewsType: {
  readonly update: 'update';
  readonly information: 'information';
  readonly war: 'war';
  readonly war_mana: 'war_mana';
  readonly championship: 'championship';
  readonly tid_start: 'tid_start';
  readonly tid_end: 'tid_end';
  readonly event_christmas: 'event_christmas';
  readonly story: 'story';
  readonly announce: 'announce'
};

export namespace NewsType {
  export type update = 'update';
  export type information = 'information';
  export type war = 'war';
  export type war_mana = 'war_mana';
  export type championship = 'championship';
  export type tid_start = 'tid_start';
  export type tid_end = 'tid_end';
  export type event_christmas = 'event_christmas';
  export type story = 'story';
  export type announce = 'announce'
}

export type NewsType = typeof NewsType[keyof typeof NewsType];

export const AdminRole: {
  readonly ADMIN: 'ADMIN';
  readonly MODERATOR: 'MODERATOR';
  readonly PLAYER: 'PLAYER';
  readonly BETA: 'BETA';
  readonly AMPHI: 'AMPHI'
};

export namespace AdminRole {
  export type ADMIN = 'ADMIN';
  export type MODERATOR = 'MODERATOR';
  export type PLAYER = 'PLAYER';
  export type BETA = 'BETA';
  export type AMPHI = 'AMPHI'
}

export type AdminRole = typeof AdminRole[keyof typeof AdminRole];

export const Lang: {
  readonly fr: 'fr';
  readonly en: 'en';
  readonly de: 'de';
  readonly es: 'es'
};

export namespace Lang {
  export type fr = 'fr';
  export type en = 'en';
  export type de = 'de';
  export type es = 'es'
}

export type Lang = typeof Lang[keyof typeof Lang];

export const OfferStatus: {
  readonly ONGOING: 'ONGOING';
  readonly ENDED: 'ENDED';
  readonly CANCELLED: 'CANCELLED';
  readonly CLAIMED: 'CLAIMED'
};

export namespace OfferStatus {
  export type ONGOING = 'ONGOING';
  export type ENDED = 'ENDED';
  export type CANCELLED = 'CANCELLED';
  export type CLAIMED = 'CLAIMED'
}

export type OfferStatus = typeof OfferStatus[keyof typeof OfferStatus];

export const LogType: {
  readonly ItemUsed: 'ItemUsed';
  readonly ItemBought: 'ItemBought';
  readonly GoldWon: 'GoldWon';
  readonly GoldLost: 'GoldLost';
  readonly Move: 'Move';
  readonly LevelUp: 'LevelUp';
  readonly Fight: 'Fight';
  readonly Death: 'Death';
  readonly Revive: 'Revive';
  readonly MissionStep: 'MissionStep';
  readonly MissionFinished: 'MissionFinished';
  readonly MissionCanceled: 'MissionCanceled';
  readonly Gather: 'Gather';
  readonly CreateDinoz: 'CreateDinoz';
  readonly ChangeDinozOrder: 'ChangeDinozOrder';
  readonly AdminUpdateDinoz: 'AdminUpdateDinoz';
  readonly AdminAddStatus: 'AdminAddStatus';
  readonly AdminRemoveStatus: 'AdminRemoveStatus';
  readonly AdminAddSkill: 'AdminAddSkill';
  readonly AdminRemoveSkill: 'AdminRemoveSkill';
  readonly AdminAddUnlockableSkill: 'AdminAddUnlockableSkill';
  readonly AdminRemoveUnlockableSkill: 'AdminRemoveUnlockableSkill';
  readonly AdminAddMoney: 'AdminAddMoney';
  readonly AdminRemoveMoney: 'AdminRemoveMoney';
  readonly AdminAddReward: 'AdminAddReward';
  readonly AdminRemoveReward: 'AdminRemoveReward';
  readonly AdminAddItem: 'AdminAddItem';
  readonly AdminRemoveItem: 'AdminRemoveItem';
  readonly AdminAddIngredient: 'AdminAddIngredient';
  readonly AdminRemoveIngredient: 'AdminRemoveIngredient';
  readonly AdminUpdateQuest: 'AdminUpdateQuest';
  readonly AdminUpdatePlayer: 'AdminUpdatePlayer';
  readonly AdminUpdateSecret: 'AdminUpdateSecret';
  readonly AdminUpdateClan: 'AdminUpdateClan';
  readonly IngredientSold: 'IngredientSold';
  readonly XPEarned: 'XPEarned';
  readonly HPLost: 'HPLost';
  readonly PlayerCreated: 'PlayerCreated';
  readonly PlayerConnected: 'PlayerConnected';
  readonly LBDone: 'LBDone';
  readonly OfferNew: 'OfferNew';
  readonly OfferBid: 'OfferBid';
  readonly OfferCancelled: 'OfferCancelled';
  readonly OfferExpired: 'OfferExpired';
  readonly OfferWon: 'OfferWon';
  readonly GridFinished: 'GridFinished';
  readonly ItemFound: 'ItemFound';
  readonly ClanWarCastleBuilt: 'ClanWarCastleBuilt';
  readonly ClanWarDeclared: 'ClanWarDeclared';
  readonly ClanWarForfeited: 'ClanWarForfeited';
  readonly ClanWarDefenderAdded: 'ClanWarDefenderAdded';
  readonly ClanWarDefenderRemoved: 'ClanWarDefenderRemoved';
  readonly ClanWarDefenseOrderUpdated: 'ClanWarDefenseOrderUpdated';
  readonly ClanWarCastleAttacked: 'ClanWarCastleAttacked';
  readonly ClanWarCastleRepaired: 'ClanWarCastleRepaired';
  readonly ClanWarResolved: 'ClanWarResolved'
};

export namespace LogType {
  export type ItemUsed = 'ItemUsed';
  export type ItemBought = 'ItemBought';
  export type GoldWon = 'GoldWon';
  export type GoldLost = 'GoldLost';
  export type Move = 'Move';
  export type LevelUp = 'LevelUp';
  export type Fight = 'Fight';
  export type Death = 'Death';
  export type Revive = 'Revive';
  export type MissionStep = 'MissionStep';
  export type MissionFinished = 'MissionFinished';
  export type MissionCanceled = 'MissionCanceled';
  export type Gather = 'Gather';
  export type CreateDinoz = 'CreateDinoz';
  export type ChangeDinozOrder = 'ChangeDinozOrder';
  export type AdminUpdateDinoz = 'AdminUpdateDinoz';
  export type AdminAddStatus = 'AdminAddStatus';
  export type AdminRemoveStatus = 'AdminRemoveStatus';
  export type AdminAddSkill = 'AdminAddSkill';
  export type AdminRemoveSkill = 'AdminRemoveSkill';
  export type AdminAddUnlockableSkill = 'AdminAddUnlockableSkill';
  export type AdminRemoveUnlockableSkill = 'AdminRemoveUnlockableSkill';
  export type AdminAddMoney = 'AdminAddMoney';
  export type AdminRemoveMoney = 'AdminRemoveMoney';
  export type AdminAddReward = 'AdminAddReward';
  export type AdminRemoveReward = 'AdminRemoveReward';
  export type AdminAddItem = 'AdminAddItem';
  export type AdminRemoveItem = 'AdminRemoveItem';
  export type AdminAddIngredient = 'AdminAddIngredient';
  export type AdminRemoveIngredient = 'AdminRemoveIngredient';
  export type AdminUpdateQuest = 'AdminUpdateQuest';
  export type AdminUpdatePlayer = 'AdminUpdatePlayer';
  export type AdminUpdateSecret = 'AdminUpdateSecret';
  export type AdminUpdateClan = 'AdminUpdateClan';
  export type IngredientSold = 'IngredientSold';
  export type XPEarned = 'XPEarned';
  export type HPLost = 'HPLost';
  export type PlayerCreated = 'PlayerCreated';
  export type PlayerConnected = 'PlayerConnected';
  export type LBDone = 'LBDone';
  export type OfferNew = 'OfferNew';
  export type OfferBid = 'OfferBid';
  export type OfferCancelled = 'OfferCancelled';
  export type OfferExpired = 'OfferExpired';
  export type OfferWon = 'OfferWon';
  export type GridFinished = 'GridFinished';
  export type ItemFound = 'ItemFound';
  export type ClanWarCastleBuilt = 'ClanWarCastleBuilt';
  export type ClanWarDeclared = 'ClanWarDeclared';
  export type ClanWarForfeited = 'ClanWarForfeited';
  export type ClanWarDefenderAdded = 'ClanWarDefenderAdded';
  export type ClanWarDefenderRemoved = 'ClanWarDefenderRemoved';
  export type ClanWarDefenseOrderUpdated = 'ClanWarDefenseOrderUpdated';
  export type ClanWarCastleAttacked = 'ClanWarCastleAttacked';
  export type ClanWarCastleRepaired = 'ClanWarCastleRepaired';
  export type ClanWarResolved = 'ClanWarResolved'
}

export type LogType = typeof LogType[keyof typeof LogType];

export const PantheonMotif: {
  readonly race: 'race';
  readonly epic: 'epic'
};

export namespace PantheonMotif {
  export type race = 'race';
  export type epic = 'epic'
}

export type PantheonMotif = typeof PantheonMotif[keyof typeof PantheonMotif];

export const ClanEventType: {
  readonly war: 'war';
  readonly mana_war: 'mana_war'
};

export namespace ClanEventType {
  export type war = 'war';
  export type mana_war = 'mana_war'
}

export type ClanEventType = typeof ClanEventType[keyof typeof ClanEventType];

export const ModerationReason: {
  readonly multi: 'multi';
  readonly dinozName: 'dinozName';
  readonly accountName: 'accountName';
  readonly avatar: 'avatar';
  readonly customText: 'customText';
  readonly other: 'other';
  readonly clanBanner: 'clanBanner';
  readonly clanBehavior: 'clanBehavior';
  readonly clanPages: 'clanPages';
  readonly clanOther: 'clanOther'
};

export namespace ModerationReason {
  export type multi = 'multi';
  export type dinozName = 'dinozName';
  export type accountName = 'accountName';
  export type avatar = 'avatar';
  export type customText = 'customText';
  export type other = 'other';
  export type clanBanner = 'clanBanner';
  export type clanBehavior = 'clanBehavior';
  export type clanPages = 'clanPages';
  export type clanOther = 'clanOther'
}

export type ModerationReason = typeof ModerationReason[keyof typeof ModerationReason];

export const ModerationAction: {
  readonly closed: 'closed';
  readonly warning: 'warning';
  readonly shortBan: 'shortBan';
  readonly mediumBan: 'mediumBan';
  readonly longBan: 'longBan';
  readonly infiniteBan: 'infiniteBan'
};

export namespace ModerationAction {
  export type closed = 'closed';
  export type warning = 'warning';
  export type shortBan = 'shortBan';
  export type mediumBan = 'mediumBan';
  export type longBan = 'longBan';
  export type infiniteBan = 'infiniteBan'
}

export type ModerationAction = typeof ModerationAction[keyof typeof ModerationAction];

export const NotificationSeverity: {
  readonly info: 'info';
  readonly success: 'success';
  readonly warning: 'warning';
  readonly error: 'error';
  readonly offerWon: 'offerWon';
  readonly offerExpired: 'offerExpired';
  readonly offerEnded: 'offerEnded';
  readonly ban: 'ban';
  readonly reward: 'reward';
  readonly scenario: 'scenario';
  readonly event: 'event';
  readonly newClanApply: 'newClanApply';
  readonly clanApplyAccepted: 'clanApplyAccepted';
  readonly message: 'message';
  readonly clanWar: 'clanWar'
};

export namespace NotificationSeverity {
  export type info = 'info';
  export type success = 'success';
  export type warning = 'warning';
  export type error = 'error';
  export type offerWon = 'offerWon';
  export type offerExpired = 'offerExpired';
  export type offerEnded = 'offerEnded';
  export type ban = 'ban';
  export type reward = 'reward';
  export type scenario = 'scenario';
  export type event = 'event';
  export type newClanApply = 'newClanApply';
  export type clanApplyAccepted = 'clanApplyAccepted';
  export type message = 'message';
  export type clanWar = 'clanWar'
}

export type NotificationSeverity = typeof NotificationSeverity[keyof typeof NotificationSeverity];

export const GameDinozUsage: {
  readonly FBTournament: 'FBTournament'
};

export namespace GameDinozUsage {
  export type FBTournament = 'FBTournament'
}

export type GameDinozUsage = typeof GameDinozUsage[keyof typeof GameDinozUsage];

export const EventType: {
  readonly CHRISTMAS: 'CHRISTMAS';
  readonly VALENTINE: 'VALENTINE'
};

export namespace EventType {
  export type CHRISTMAS = 'CHRISTMAS';
  export type VALENTINE = 'VALENTINE'
}

export type EventType = typeof EventType[keyof typeof EventType];

export const ServerAction: {
  readonly checkBans: 'checkBans';
  readonly healRestingDinoz: 'healRestingDinoz';
  readonly itinerantMerchant: 'itinerantMerchant';
  readonly midnightReset: 'midnightReset';
  readonly prospector: 'prospector'
};

export namespace ServerAction {
  export type checkBans = 'checkBans';
  export type healRestingDinoz = 'healRestingDinoz';
  export type itinerantMerchant = 'itinerantMerchant';
  export type midnightReset = 'midnightReset';
  export type prospector = 'prospector'
}

export type ServerAction = typeof ServerAction[keyof typeof ServerAction];

export const $Enums: {
  readonly UnavailableReason: typeof UnavailableReason;
  readonly NewsType: typeof NewsType;
  readonly AdminRole: typeof AdminRole;
  readonly Lang: typeof Lang;
  readonly OfferStatus: typeof OfferStatus;
  readonly LogType: typeof LogType;
  readonly PantheonMotif: typeof PantheonMotif;
  readonly ClanEventType: typeof ClanEventType;
  readonly ModerationReason: typeof ModerationReason;
  readonly ModerationAction: typeof ModerationAction;
  readonly NotificationSeverity: typeof NotificationSeverity;
  readonly GameDinozUsage: typeof GameDinozUsage;
  readonly EventType: typeof EventType;
  readonly ServerAction: typeof ServerAction
};
