version: '3'

services:

  #Database container
  drpg_database:
    image: postgres:13.1
    container_name: drpg_database
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
      - ./DB:/import
    networks:
      - drpg_network
    environment:
      POSTGRES_PASSWORD: EternalDinoSQL
      POSTGRES_USER: etwin.dev.write
      POSTGRES_MULTIPLE_DATABASES: eternaldinodb,etwin.dev

  drpg:
    container_name: drpg
    build:
      context: ./container
      dockerfile: Dockerfile
      args:
        - YOUR_APP_WEB_HTTP_PORT=8080
    volumes:
      - ../.:/www
    stdin_open: true
    tty: true
    networks:
      - drpg_network
    environment:
      # https://cli.vuejs.org/guide/mode-and-env.html#modes
      # development is used by vue-cli-service serve
      - NODE_ENV=development
      # To make sure that someone running a brand new docker gets debug logs by default
      - RUST_LOG=DEBUG

  drpg_eternal_twin:
    container_name: drpg_eternal_twin
    build:
      context: ./EternalTwin
      dockerfile: Dockerfile
    volumes:
      - ../Eternaltwin:/www
    networks:
      - drpg_network
    stdin_open: true
    tty: true

networks:
  drpg_network:
    driver: bridge
