version: '3'

services:

  #Database container
  drpg_database:
    image: postgres:13.1
    container_name: drpg_database
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    networks:
      - drpg_network
    environment:
      POSTGRES_PASSWORD: EternalDinoSQL
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: EternalDinoDB,eternal_twin

  drpg_front:
    container_name: drpg_front
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - YOUR_APP_WEB_HTTP_PORT=8080
    volumes:
      - ../ed-ui:/www
    stdin_open: true
    tty: true
    environment:
      # https://cli.vuejs.org/guide/mode-and-env.html#modes
      # development is used by vue-cli-service serve
      - NODE_ENV=development
      # one way for hot reloading ... see above for details
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - YOUR_APP_WEB_HTTP_PORT=8080

  drpg_eternal_twin:
    container_name: drpg_eternal_twin
    build:
      context: ./EternalTwin
      dockerfile: Dockerfile
    volumes:
      - ../EternalTwin:/www
    networks:
      - drpg_network
    stdin_open: true
    tty: true

  drpg_back:
    container_name: drpg_back
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        - YOUR_APP_WEB_HTTP_PORT=8080
    volumes:
      - ../ed-be:/www
    stdin_open: true
    tty: true
    environment:
      # https://cli.vuejs.org/guide/mode-and-env.html#modes
      # development is used by vue-cli-service serve
      - NODE_ENV=development
      # one way for hot reloading ... see above for details
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - YOUR_APP_WEB_HTTP_PORT=8080

networks:
  drpg_network:
    driver: bridge
