[package]
name = "native-dinorpg"
version = "0.4.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]
build = "build.rs"
publish = false

[lib]
crate-type = ["cdylib"]
test = false

[[bin]]
name = "main"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
serde_repr = "0.1.14"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]

[build-dependencies]
neon-build = "0.10.0"
