import { EpicReward, RewardType } from './EpicReward.mjs';

export enum Reward {
	PERLE = 1,
	PTEROZ = 2,
	HIPPO = 3,
	ROCKY = 4,
	QUETZU = 5,
	LABOWI = 6,
	TOUR = 7,
	VENER = 8,
	TAURUS = 9,
	BELIUS = 10,
	SCORP = 11,
	MSG = 12,
	MAGNET = 13,
	PLUME = 14,
	KAURA = 15,
	DEMON = 16,
	PMI = 17,
	PDA = 18,
	FDJV1 = 19,
	DICO1 = 20,
	DICARB = 21,
	CAUSH = 22,
	FMEDAL = 23,
	WAR1A = 24,
	WAR1B = 25,
	WAR2A = 26,
	WAR2B = 27,
	WAR3A = 28,
	WAR3B = 29,
	WAR4A = 30,
	WAR4B = 31,
	WAR5A = 32,
	WAR5B = 33,
	WARFA = 34,
	WARFB = 35,
	WARFC = 36,
	WARGA = 37,
	WARGB = 38,
	WARGC = 39,
	WARHA = 40,
	WARHB = 41,
	WARIA = 42,
	WARIB = 43,
	WARIC = 44,
	WARJA = 45,
	WARJB = 46,
	WARJC = 47,
	WARKA = 48,
	WARKB = 49,
	WARKC = 50,
	WARLA = 51,
	WARLB = 52,
	WARLC = 53,
	WARMA = 54,
	WARMB = 55,
	WARMC = 56,
	WARNA = 57,
	WARNB = 58,
	WARNC = 59,
	WAROA = 60,
	WAROB = 61,
	WAROC = 62,
	WARPA = 63,
	WARPB = 64,
	WARPC = 65,
	WARQA = 66,
	WARQB = 67,
	WARQC = 68,
	WARRA = 69,
	WARRB = 70,
	WARRC = 71,
	WARSA = 72,
	WARSB = 73,
	WARSC = 74,
	WARTA = 75,
	WARTB = 76,
	WARTC = 77,
	WARUA = 78,
	WARUB = 79,
	WARUC = 80,
	WARVA = 81,
	WARVB = 82,
	WARVC = 83,
	WARWA = 84,
	WARWB = 85,
	WARWC = 86,
	WARXA = 87,
	WARXB = 88,
	WARXC = 89,
	WARYA = 90,
	WARYB = 91,
	WARYC = 92,
	WARZA = 93,
	WARZB = 94,
	WARZC = 95,
	CH1X1A = 96,
	CH1X1B = 97,
	CH1X2A = 98,
	CH1X2B = 99,
	CH2X1A = 100,
	CH2X2A = 101,
	CH2X2B = 102,
	CH2X3A = 103,
	CH2X3B = 104,
	CH3X1A = 105,
	CH3X1B = 106,
	CH3X2A = 107,
	CH3X2B = 108,
	CH3X3A = 109,
	CH3X3B = 110,
	CH3X4A = 111,
	CH3X4B = 112,
	CH4X1A = 113,
	CH4X1B = 114,
	CH4X2A = 115,
	CH4X2B = 116,
	CH4X3A = 117,
	CH4X3B = 118,
	CH4X4A = 119,
	CH4X4B = 120,
	CH5X1 = 121,
	CH5X2 = 122,
	CH5X3 = 123,
	CH5X4 = 124,
	CHFX1 = 125,
	CHFX2 = 126,
	CHFX3 = 127,
	CHFX4 = 128,
	CHGX1A = 129,
	CHGX1B = 130,
	CHGX2A = 131,
	CHGX2B = 132,
	CHGX3A = 133,
	CHGX3B = 134,
	CHGX4A = 135,
	CHGX4B = 136,
	CHHX1A = 137,
	CHHX1B = 138,
	CHHX2A = 139,
	CHHX2B = 140,
	CHHX3A = 141,
	CHHX3B = 142,
	CHHX4A = 143,
	CHHX4B = 144,
	CHIX1A = 145,
	CHIX1B = 146,
	CHIX2A = 147,
	CHIX2B = 148,
	CHIX3A = 149,
	CHIX3B = 150,
	CHIX4B = 151,
	CHIX4A = 152,
	CHJX1A = 153,
	CHJX1B = 154,
	CHJX2A = 155,
	CHJX2B = 156,
	CHJX3A = 157,
	CHJX3B = 158,
	CHKX1B = 159,
	CHKX1A = 160,
	CHKX2B = 161,
	CHKX2A = 162,
	CHKX3B = 163,
	CHKX3A = 164,
	CHLX1B = 165,
	CHLX1A = 166,
	CHLX2B = 167,
	CHLX2A = 168,
	CHLX3B = 169,
	CHLX3A = 170,
	CHMX1B = 171,
	CHMX1A = 172,
	CHMX2B = 173,
	CHMX2A = 174,
	CHMX3B = 175,
	CHMX3A = 176,
	CHNX1B = 177,
	CHNX1A = 178,
	CHNX2B = 179,
	CHNX2A = 180,
	CHNX3B = 181,
	CHNX3A = 182,
	CHOX1A = 183,
	CHOX1B = 184,
	CHOX2A = 185,
	CHOX2B = 186,
	CHOX3A = 187,
	CHOX3B = 188,
	CHPX1A = 189,
	CHPX1B = 190,
	CHPX2A = 191,
	CHPX2B = 192,
	CHPX3A = 193,
	CHPX3B = 194,
	CHQX1A = 195,
	CHQX1B = 196,
	CHQX2A = 197,
	CHQX2B = 198,
	CHQX3A = 199,
	CHQX3B = 200,
	CHRX1A = 201,
	CHRX1B = 202,
	CHRX2A = 203,
	CHRX2B = 204,
	CHRX3A = 205,
	CHRX3B = 206,
	CINEC1 = 207,
	CINEC2 = 208,
	CINEC3 = 209,
	CINEC4 = 210,
	HALLOW = 211,
	TID1 = 212,
	TID2 = 213,
	GAZELI = 214,
	HUNT1 = 215,
	HUNINT = 216,
	XHUNT3 = 217,
	XHUNT2 = 218,
	XHUNT1 = 219,
	CINEMA = 220,
	CINEM2 = 221,
	EUGENE = 222,
	LITTER = 223,
	CLOVER = 224,
	MERGUEZ_CARD = 996,
	PAC = 997,
	TIK = 998,
	BETA = 999
}

export const rewardList: Readonly<Record<Reward, EpicReward>> = {
	[Reward.PERLE]: { id: Reward.PERLE, name: 'perle', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.PTEROZ]: { id: Reward.PTEROZ, name: 'pteroz', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.HIPPO]: { id: Reward.HIPPO, name: 'hippo', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.ROCKY]: { id: Reward.ROCKY, name: 'rocky', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.QUETZU]: { id: Reward.QUETZU, name: 'quetzu', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.LABOWI]: { id: Reward.LABOWI, name: 'labowi', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.TOUR]: { id: Reward.TOUR, name: 'tour', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.VENER]: { id: Reward.VENER, name: 'vener', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.TAURUS]: { id: Reward.TAURUS, name: 'taurus', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.BELIUS]: { id: Reward.BELIUS, name: 'belius', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.SCORP]: { id: Reward.SCORP, name: 'scorp', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.MSG]: { id: Reward.MSG, name: 'msg', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.MAGNET]: { id: Reward.MAGNET, name: 'magnet', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.PLUME]: { id: Reward.PLUME, name: 'plume', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.KAURA]: { id: Reward.KAURA, name: 'kaura', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.DEMON]: { id: Reward.DEMON, name: 'demon', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.PMI]: { id: Reward.PMI, name: 'pmi', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.PDA]: { id: Reward.PDA, name: 'pda', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.FDJV1]: { id: Reward.FDJV1, name: 'fdjv1', displayed: true, announced: false, type: RewardType.PVE },
	[Reward.DICO1]: { id: Reward.DICO1, name: 'dico1', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.DICARB]: { id: Reward.DICARB, name: 'dicarb', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.CAUSH]: { id: Reward.CAUSH, name: 'caush', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.FMEDAL]: { id: Reward.FMEDAL, name: 'fmedal', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.WAR1A]: { id: Reward.WAR1A, name: 'war1a', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAR1B]: { id: Reward.WAR1B, name: 'war1b', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAR2A]: { id: Reward.WAR2A, name: 'war2a', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAR2B]: { id: Reward.WAR2B, name: 'war2b', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAR3A]: { id: Reward.WAR3A, name: 'war3a', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAR3B]: { id: Reward.WAR3B, name: 'war3b', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAR4A]: { id: Reward.WAR4A, name: 'war4a', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAR4B]: { id: Reward.WAR4B, name: 'war4b', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAR5A]: { id: Reward.WAR5A, name: 'war5a', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAR5B]: { id: Reward.WAR5B, name: 'war5b', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARFA]: { id: Reward.WARFA, name: 'warfa', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARFB]: { id: Reward.WARFB, name: 'warfb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARFC]: { id: Reward.WARFC, name: 'warfc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARGA]: { id: Reward.WARGA, name: 'warga', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARGB]: { id: Reward.WARGB, name: 'wargb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARGC]: { id: Reward.WARGC, name: 'wargc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARHA]: { id: Reward.WARHA, name: 'warha', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARHB]: { id: Reward.WARHB, name: 'warhb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARIA]: { id: Reward.WARIA, name: 'waria', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARIB]: { id: Reward.WARIB, name: 'warib', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARIC]: { id: Reward.WARIC, name: 'waric', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARJA]: { id: Reward.WARJA, name: 'warja', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARJB]: { id: Reward.WARJB, name: 'warjb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARJC]: { id: Reward.WARJC, name: 'warjc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARKA]: { id: Reward.WARKA, name: 'warka', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARKB]: { id: Reward.WARKB, name: 'warkb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARKC]: { id: Reward.WARKC, name: 'warkc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARLA]: { id: Reward.WARLA, name: 'warla', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARLB]: { id: Reward.WARLB, name: 'warlb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARLC]: { id: Reward.WARLC, name: 'warlc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARMA]: { id: Reward.WARMA, name: 'warma', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARMB]: { id: Reward.WARMB, name: 'warmb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARMC]: { id: Reward.WARMC, name: 'warmc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARNA]: { id: Reward.WARNA, name: 'warna', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARNB]: { id: Reward.WARNB, name: 'warnb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARNC]: { id: Reward.WARNC, name: 'warnc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAROA]: { id: Reward.WAROA, name: 'waroa', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAROB]: { id: Reward.WAROB, name: 'warob', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WAROC]: { id: Reward.WAROC, name: 'waroc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARPA]: { id: Reward.WARPA, name: 'warpa', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARPB]: { id: Reward.WARPB, name: 'warpb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARPC]: { id: Reward.WARPC, name: 'warpc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARQA]: { id: Reward.WARQA, name: 'warqa', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARQB]: { id: Reward.WARQB, name: 'warqb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARQC]: { id: Reward.WARQC, name: 'warqc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARRA]: { id: Reward.WARRA, name: 'warra', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARRB]: { id: Reward.WARRB, name: 'warrb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARRC]: { id: Reward.WARRC, name: 'warrc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARSA]: { id: Reward.WARSA, name: 'warsa', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARSB]: { id: Reward.WARSB, name: 'warsb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARSC]: { id: Reward.WARSC, name: 'warsc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARTA]: { id: Reward.WARTA, name: 'warta', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARTB]: { id: Reward.WARTB, name: 'wartb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARTC]: { id: Reward.WARTC, name: 'wartc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARUA]: { id: Reward.WARUA, name: 'warua', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARUB]: { id: Reward.WARUB, name: 'warub', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARUC]: { id: Reward.WARUC, name: 'waruc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARVA]: { id: Reward.WARVA, name: 'warva', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARVB]: { id: Reward.WARVB, name: 'warvb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARVC]: { id: Reward.WARVC, name: 'warvc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARWA]: { id: Reward.WARWA, name: 'warwa', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARWB]: { id: Reward.WARWB, name: 'warwb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARWC]: { id: Reward.WARWC, name: 'warwc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARXA]: { id: Reward.WARXA, name: 'warxa', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARXB]: { id: Reward.WARXB, name: 'warxb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARXC]: { id: Reward.WARXC, name: 'warxc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARYA]: { id: Reward.WARYA, name: 'warya', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARYB]: { id: Reward.WARYB, name: 'waryb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARYC]: { id: Reward.WARYC, name: 'waryc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARZA]: { id: Reward.WARZA, name: 'warza', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARZB]: { id: Reward.WARZB, name: 'warzb', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.WARZC]: { id: Reward.WARZC, name: 'warzc', displayed: true, announced: false, type: RewardType.WAR },
	[Reward.CH1X1A]: { id: Reward.CH1X1A, name: 'ch1x1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH1X1B]: { id: Reward.CH1X1B, name: 'ch1x1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH1X2A]: { id: Reward.CH1X2A, name: 'ch1x2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH1X2B]: { id: Reward.CH1X2B, name: 'ch1x2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH2X1A]: { id: Reward.CH2X1A, name: 'ch2x1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH2X2A]: { id: Reward.CH2X2A, name: 'ch2x2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH2X2B]: { id: Reward.CH2X2B, name: 'ch2x2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH2X3A]: { id: Reward.CH2X3A, name: 'ch2x3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH2X3B]: { id: Reward.CH2X3B, name: 'ch2x3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH3X1A]: { id: Reward.CH3X1A, name: 'ch3x1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH3X1B]: { id: Reward.CH3X1B, name: 'ch3x1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH3X2A]: { id: Reward.CH3X2A, name: 'ch3x2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH3X2B]: { id: Reward.CH3X2B, name: 'ch3x2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH3X3A]: { id: Reward.CH3X3A, name: 'ch3x3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH3X3B]: { id: Reward.CH3X3B, name: 'ch3x3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH3X4A]: { id: Reward.CH3X4A, name: 'ch3x4a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH3X4B]: { id: Reward.CH3X4B, name: 'ch3x4b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH4X1A]: { id: Reward.CH4X1A, name: 'ch4x1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH4X1B]: { id: Reward.CH4X1B, name: 'ch4x1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH4X2A]: { id: Reward.CH4X2A, name: 'ch4x2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH4X2B]: { id: Reward.CH4X2B, name: 'ch4x2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH4X3A]: { id: Reward.CH4X3A, name: 'ch4x3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH4X3B]: { id: Reward.CH4X3B, name: 'ch4x3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH4X4A]: { id: Reward.CH4X4A, name: 'ch4x4a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH4X4B]: { id: Reward.CH4X4B, name: 'ch4x4b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH5X1]: { id: Reward.CH5X1, name: 'ch5x1', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH5X2]: { id: Reward.CH5X2, name: 'ch5x2', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH5X3]: { id: Reward.CH5X3, name: 'ch5x3', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CH5X4]: { id: Reward.CH5X4, name: 'ch5x4', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHFX1]: { id: Reward.CHFX1, name: 'chfx1', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHFX2]: { id: Reward.CHFX2, name: 'chfx2', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHFX3]: { id: Reward.CHFX3, name: 'chfx3', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHFX4]: { id: Reward.CHFX4, name: 'chfx4', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHGX1A]: { id: Reward.CHGX1A, name: 'chgx1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHGX1B]: { id: Reward.CHGX1B, name: 'chgx1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHGX2A]: { id: Reward.CHGX2A, name: 'chgx2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHGX2B]: { id: Reward.CHGX2B, name: 'chgx2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHGX3A]: { id: Reward.CHGX3A, name: 'chgx3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHGX3B]: { id: Reward.CHGX3B, name: 'chgx3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHGX4A]: { id: Reward.CHGX4A, name: 'chgx4a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHGX4B]: { id: Reward.CHGX4B, name: 'chgx4b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHHX1A]: { id: Reward.CHHX1A, name: 'chhx1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHHX1B]: { id: Reward.CHHX1B, name: 'chhx1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHHX2A]: { id: Reward.CHHX2A, name: 'chhx2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHHX2B]: { id: Reward.CHHX2B, name: 'chhx2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHHX3A]: { id: Reward.CHHX3A, name: 'chhx3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHHX3B]: { id: Reward.CHHX3B, name: 'chhx3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHHX4A]: { id: Reward.CHHX4A, name: 'chhx4a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHHX4B]: { id: Reward.CHHX4B, name: 'chhx4b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHIX1A]: { id: Reward.CHIX1A, name: 'chix1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHIX1B]: { id: Reward.CHIX1B, name: 'chix1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHIX2A]: { id: Reward.CHIX2A, name: 'chix2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHIX2B]: { id: Reward.CHIX2B, name: 'chix2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHIX3A]: { id: Reward.CHIX3A, name: 'chix3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHIX3B]: { id: Reward.CHIX3B, name: 'chix3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHIX4B]: { id: Reward.CHIX4B, name: 'chix4b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHIX4A]: { id: Reward.CHIX4A, name: 'chix4a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHJX1A]: { id: Reward.CHJX1A, name: 'chjx1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHJX1B]: { id: Reward.CHJX1B, name: 'chjx1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHJX2A]: { id: Reward.CHJX2A, name: 'chjx2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHJX2B]: { id: Reward.CHJX2B, name: 'chjx2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHJX3A]: { id: Reward.CHJX3A, name: 'chjx3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHJX3B]: { id: Reward.CHJX3B, name: 'chjx3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHKX1B]: { id: Reward.CHKX1B, name: 'chkx1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHKX1A]: { id: Reward.CHKX1A, name: 'chkx1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHKX2B]: { id: Reward.CHKX2B, name: 'chkx2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHKX2A]: { id: Reward.CHKX2A, name: 'chkx2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHKX3B]: { id: Reward.CHKX3B, name: 'chkx3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHKX3A]: { id: Reward.CHKX3A, name: 'chkx3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHLX1B]: { id: Reward.CHLX1B, name: 'chlx1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHLX1A]: { id: Reward.CHLX1A, name: 'chlx1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHLX2B]: { id: Reward.CHLX2B, name: 'chlx2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHLX2A]: { id: Reward.CHLX2A, name: 'chlx2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHLX3B]: { id: Reward.CHLX3B, name: 'chlx3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHLX3A]: { id: Reward.CHLX3A, name: 'chlx3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHMX1B]: { id: Reward.CHMX1B, name: 'chmx1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHMX1A]: { id: Reward.CHMX1A, name: 'chmx1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHMX2B]: { id: Reward.CHMX2B, name: 'chmx2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHMX2A]: { id: Reward.CHMX2A, name: 'chmx2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHMX3B]: { id: Reward.CHMX3B, name: 'chmx3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHMX3A]: { id: Reward.CHMX3A, name: 'chmx3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHNX1B]: { id: Reward.CHNX1B, name: 'chnx1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHNX1A]: { id: Reward.CHNX1A, name: 'chnx1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHNX2B]: { id: Reward.CHNX2B, name: 'chnx2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHNX2A]: { id: Reward.CHNX2A, name: 'chnx2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHNX3B]: { id: Reward.CHNX3B, name: 'chnx3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHNX3A]: { id: Reward.CHNX3A, name: 'chnx3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHOX1A]: { id: Reward.CHOX1A, name: 'chox1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHOX1B]: { id: Reward.CHOX1B, name: 'chox1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHOX2A]: { id: Reward.CHOX2A, name: 'chox2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHOX2B]: { id: Reward.CHOX2B, name: 'chox2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHOX3A]: { id: Reward.CHOX3A, name: 'chox3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHOX3B]: { id: Reward.CHOX3B, name: 'chox3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHPX1A]: { id: Reward.CHPX1A, name: 'chpx1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHPX1B]: { id: Reward.CHPX1B, name: 'chpx1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHPX2A]: { id: Reward.CHPX2A, name: 'chpx2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHPX2B]: { id: Reward.CHPX2B, name: 'chpx2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHPX3A]: { id: Reward.CHPX3A, name: 'chpx3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHPX3B]: { id: Reward.CHPX3B, name: 'chpx3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHQX1A]: { id: Reward.CHQX1A, name: 'chqx1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHQX1B]: { id: Reward.CHQX1B, name: 'chqx1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHQX2A]: { id: Reward.CHQX2A, name: 'chqx2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHQX2B]: { id: Reward.CHQX2B, name: 'chqx2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHQX3A]: { id: Reward.CHQX3A, name: 'chqx3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHQX3B]: { id: Reward.CHQX3B, name: 'chqx3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHRX1A]: { id: Reward.CHRX1A, name: 'chrx1a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHRX1B]: { id: Reward.CHRX1B, name: 'chrx1b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHRX2A]: { id: Reward.CHRX2A, name: 'chrx2a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHRX2B]: { id: Reward.CHRX2B, name: 'chrx2b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHRX3A]: { id: Reward.CHRX3A, name: 'chrx3a', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CHRX3B]: { id: Reward.CHRX3B, name: 'chrx3b', displayed: true, announced: false, type: RewardType.CDC },
	[Reward.CINEC1]: { id: Reward.CINEC1, name: 'cinec1', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.CINEC2]: { id: Reward.CINEC2, name: 'cinec2', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.CINEC3]: { id: Reward.CINEC3, name: 'cinec3', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.CINEC4]: { id: Reward.CINEC4, name: 'cinec4', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.HALLOW]: { id: Reward.HALLOW, name: 'hallow', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.TID1]: { id: Reward.TID1, name: 'tid1', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.TID2]: { id: Reward.TID2, name: 'tid2', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.GAZELI]: { id: Reward.GAZELI, name: 'gazeli', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.HUNT1]: { id: Reward.HUNT1, name: 'hunt1', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.HUNINT]: { id: Reward.HUNINT, name: 'hunint', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.XHUNT3]: { id: Reward.XHUNT3, name: 'xhunt3', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.XHUNT2]: { id: Reward.XHUNT2, name: 'xhunt2', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.XHUNT1]: { id: Reward.XHUNT1, name: 'xhunt1', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.CINEMA]: { id: Reward.CINEMA, name: 'cinema', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.CINEM2]: { id: Reward.CINEM2, name: 'cinem2', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.EUGENE]: { id: Reward.EUGENE, name: 'eugene', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.LITTER]: { id: Reward.LITTER, name: 'litter', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.CLOVER]: { id: Reward.CLOVER, name: 'clover', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.TIK]: { id: Reward.TIK, name: 'tik', displayed: false, announced: false, type: RewardType.PVE },
	[Reward.BETA]: { id: Reward.BETA, name: 'beta', displayed: true, announced: false, type: RewardType.SPECIAL },
	[Reward.PAC]: { id: Reward.PAC, name: 'pac', displayed: true, announced: true, type: RewardType.PVE },
	[Reward.MERGUEZ_CARD]: {
		id: Reward.MERGUEZ_CARD,
		name: 'card',
		displayed: true,
		announced: true,
		type: RewardType.PVE
	}
};
