import { Skill } from '../dinoz/SkillList.mjs';
import { MapZone } from '../enums/MapZone.mjs';
import { MonsterFiche } from './MonsterFiche.mjs';

export enum Boss {
	TOWER_GUARDIAN = 'TOWER_GUARDIAN',
	SUMMIT_GUARDIAN = 'SUMMIT_GUARDIAN',
	LOWER_GUARDIAN = 'LOWER_GUARDIAN',
	ELEMENTAIRE_FEU = 'ELEMENTAIRE_FEU',
	ELEMENTAIRE_EAU = 'ELEMENTAIRE_EAU',
	RASCAPHANDRE = 'RASCAPHANDRE',
	ELEMENTAIRE_TERRE = 'ELEMENTAIRE_TERRE',
	PTEROZ = 'PTEROZ',
	HIPPOCLAMP = 'HIPPOCLAMP',
	ROCKY = 'ROCKY',
	MASTER_CHA = 'MASTER_CHA',
	PIRHANOS_3 = 'PIRHANOS_3',
	TW_BIGBEASTLY = 'TW_BIGBEASTLY',
	PR_IGOR = 'PR_IGOR',
	VENERABLE = 'VENERABLE',
	VENERABLE_2 = 'VENERABLE_2',
	VENERABLE_3 = 'VENERABLE_3',
	VENERABLE_4 = 'VENERABLE_4',
	SCORPIOUS = 'SCORPIOUS',
	YAKUZI = 'YAKUZI',
	DARK_MEGASHROOM = 'DARK_MEGASHROOM',
	DARK_MEGASHROOM_2 = 'DARK_MEGASHROOM_2',
	MASKED_KORGON = 'MASKED_KORGON',
	SOUTHERN_KORGON = 'SOUTHERN_KORGON',
	BIO_METALIC_LEECH = 'BIO_METALIC_LEECH',
	DEMYOM_DEFENDER = 'DEMYOM_DEFENDER',
	GROTOX = 'GROTOX',
	BEHEMOUNT = 'BEHEMOUNT',
	SERPETHER = 'SERPETHER',
	SERPETHER_2 = 'SERPETHER_2',
	MORG = 'MORG',
	MORG_2 = 'MORG_2',
	MUTATED_MORG = 'MUTATED_MORG',
	GRIZORG = 'GRIZORG',
	GRIZOU = 'GRIZOU',
	MUTATED_GRIZORG = 'MUTATED_GRIZORG',
	ULTIMATE_GRIZORG = 'ULTIMATE_GRIZORG',
	CHIEF_DOROGON = 'CHIEF_DOROGON',
	SOFIA = 'SOFIA'
}

export const bossList: Readonly<Record<Boss, MonsterFiche>> = {
	[Boss.TOWER_GUARDIAN]: {
		id: Boss.TOWER_GUARDIAN,
		boss: true,
		name: 'towgrd',
		hp: 300,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		balanced: false,
		gold: 0,
		xp: 40,
		odds: 100,
		level: 30,
		zones: [],
		canBeCaptured: false,
		skills: [Skill.M_ELEMENTAL]
	},
	[Boss.SUMMIT_GUARDIAN]: {
		id: Boss.SUMMIT_GUARDIAN,
		boss: true,
		name: 'upgrd',
		level: 40,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		balanced: false,
		groups: [
			{ quantity: 0, odds: 1 },
			{ quantity: 1, odds: 0 },
			{ quantity: 2, odds: 0 }
		],
		hp: 500,
		xp: 40,
		odds: 100,
		zones: [],
		canBeCaptured: false,
		skills: [Skill.M_ELEMENTAL]
	},
	[Boss.LOWER_GUARDIAN]: {
		id: Boss.LOWER_GUARDIAN,
		boss: true,
		name: 'updwn',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		balanced: false,
		groups: [
			{ quantity: 0, odds: 1 },
			{ quantity: 1, odds: 0 },
			{ quantity: 2, odds: 0 }
		],
		hp: 600,
		xp: 60,
		odds: 100,
		zones: [],
		canBeCaptured: false,
		skills: [Skill.M_ELEMENTAL]
	},
	[Boss.ELEMENTAIRE_FEU]: {
		id: Boss.ELEMENTAIRE_FEU,
		boss: true,
		name: 'efire',
		hp: 60,
		elements: {
			fire: 4,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		balanced: false,
		gold: 0,
		xp: 50,
		odds: 1,
		level: 5,
		zones: [MapZone.DARKWORLD],
		canBeCaptured: false,
		display: 'efire'
	},
	[Boss.ELEMENTAIRE_EAU]: {
		id: Boss.ELEMENTAIRE_EAU,
		boss: true,
		name: 'ewater',
		hp: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 4,
			lightning: 0,
			air: 0
		},
		balanced: false,
		gold: 0,
		xp: 50,
		odds: 1,
		level: 5,
		zones: [MapZone.DARKWORLD],
		canBeCaptured: false,
		display: 'ewater'
	},
	[Boss.RASCAPHANDRE]: {
		id: Boss.RASCAPHANDRE,
		boss: true,
		name: 'rasca',
		hp: 60,
		elements: {
			fire: 1,
			wood: 2,
			water: 8,
			lightning: 1,
			air: 2
		},
		balanced: false,
		gold: 0,
		xp: 100,
		odds: 1,
		level: 10,
		zones: [MapZone.ILES],
		canBeCaptured: false,
		display: 'rasca'
	},
	[Boss.ELEMENTAIRE_TERRE]: {
		id: Boss.ELEMENTAIRE_TERRE,
		boss: true,
		name: 'eearth',
		hp: 100,
		elements: {
			fire: 2,
			wood: 8,
			water: 2,
			lightning: 2,
			air: 2
		},
		balanced: false,
		gold: 0,
		xp: 100,
		odds: 1,
		level: 10,
		zones: [MapZone.ILES],
		canBeCaptured: false,
		display: 'eearth'
	},
	[Boss.PTEROZ]: {
		id: Boss.PTEROZ,
		boss: true,
		name: 'pteroz',
		hp: 70,
		elements: {
			fire: 4,
			wood: 1,
			water: 0,
			lightning: 2,
			air: 3
		},
		balanced: false,
		gold: 0,
		xp: 50,
		odds: 1,
		level: 7,
		zones: [MapZone.ALL],
		skills: [Skill.COLERE, Skill.FORCE, Skill.FOCUS, Skill.GRIFFES_ENFLAMMEES, Skill.ENVOL],
		canBeCaptured: false,
		display: 'pteroz'
	},
	[Boss.HIPPOCLAMP]: {
		id: Boss.HIPPOCLAMP,
		boss: true,
		name: 'hippo',
		hp: 70,
		elements: {
			fire: 2,
			wood: 4,
			water: 3,
			lightning: 1,
			air: 1
		},
		balanced: false,
		gold: 0,
		xp: 50,
		odds: 1,
		level: 7,
		zones: [MapZone.ALL],
		skills: [Skill.CARAPACE, Skill.SAUVAGERIE, Skill.CANON_A_EAU, Skill.ENDURANCE],
		canBeCaptured: false,
		display: 'hippo'
	},
	[Boss.ROCKY]: {
		id: Boss.ROCKY,
		boss: true,
		name: 'rocky',
		hp: 100,
		elements: {
			fire: 1,
			wood: 2,
			water: 3,
			lightning: 6,
			air: 3
		},
		balanced: false,
		gold: 0,
		xp: 50,
		odds: 1,
		level: 12,
		zones: [MapZone.ALL],
		skills: [Skill.FOUDRE, Skill.FOCUS, Skill.CARAPACE, Skill.CELERITE, Skill.COUP_DOUBLE],
		canBeCaptured: false,
		display: 'rocky'
	},
	[Boss.MASTER_CHA]: {
		id: Boss.MASTER_CHA,
		boss: true,
		name: 'mcha',
		level: 80,
		elements: {
			fire: 20,
			wood: 40,
			water: 20,
			lightning: 40,
			air: 20
		},
		bonus_attack: 0,
		bonus_defense: 0,
		balanced: false,
		hp: 500,
		odds: 100,
		xp: 200,
		skills: [
			Skill.BRAVE,
			Skill.ZERO_ABSOLU,
			Skill.CLONE_AQUEUX,
			Skill.MUR_DE_BOUE,
			// Missing Skill.SKILL_FORGER
			Skill.MAINS_COLLANTES,
			Skill.BERSERK,
			Skill.AMAZONIE,
			Skill.PERCEPTION,
			Skill.M_ELECTROCUTION
		],
		zones: [],
		canBeCaptured: false
	},
	[Boss.PIRHANOS_3]: {
		id: Boss.PIRHANOS_3,
		boss: true,
		name: 'pirao3',
		zones: [],
		level: 15,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 30,
		bonus_defense: 20,
		balanced: true,
		odds: 100,
		hp: 30,
		groups: [
			{ quantity: 0, odds: 0 },
			{ quantity: 1, odds: 0 },
			{ quantity: 2, odds: 1 }
		],
		xp: 50,
		skills: [Skill.M_FLIGHT],
		canBeCaptured: false
	},
	[Boss.TW_BIGBEASTLY]: {
		id: Boss.TW_BIGBEASTLY,
		boss: true,
		name: 'wbour2',
		level: 35,
		elements: {
			fire: 0,
			wood: 11,
			water: 0,
			lightning: 20,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 0,
		balanced: true,
		hp: 300,
		odds: 100,
		xp: 50,
		skills: [
			Skill.CELERITE,
			Skill.ATTAQUE_ECLAIR,
			Skill.FOUDRE,
			Skill.COUP_DOUBLE,
			Skill.DANSE_FOUDROYANTE,
			Skill.M_RESISTANCE
		],
		zones: [],
		canBeCaptured: false
	},
	[Boss.PR_IGOR]: {
		id: Boss.PR_IGOR,
		boss: true,
		name: 'igor',
		level: 20,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 20,
		bonus_defense: 20,
		balanced: true,
		hp: 200,
		odds: 100,
		skills: [Skill.M_RESISTANCE, Skill.M_INVISIBILITY],
		zones: [],
		canBeCaptured: false
	},
	[Boss.VENERABLE]: {
		id: Boss.VENERABLE,
		boss: true,
		name: 'vener',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 60,
		balanced: false,
		hp: 1000,
		odds: 100,
		skills: [Skill.M_VENERABLE],
		xp: 1000,
		zones: [],
		canBeCaptured: false,
		noMove: true,
		display: 'vener'
	},
	[Boss.VENERABLE_2]: {
		id: Boss.VENERABLE_2,
		boss: true,
		name: 'vener2',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 60,
		balanced: false,
		hp: 1000,
		odds: 100,
		skills: [Skill.M_VENERABLE],
		xp: 0,
		zones: [],
		canBeCaptured: false,
		noMove: true,
		display: 'vener'
	},
	[Boss.VENERABLE_3]: {
		id: Boss.VENERABLE_3,
		boss: true,
		name: 'vener3',
		level: 20,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 5,
		balanced: false,
		hp: 500,
		odds: 100,
		skills: [Skill.M_VENERABLE],
		xp: 0,
		gold: 0,
		zones: [],
		canBeCaptured: false,
		noMove: true,
		display: 'vener'
	},
	[Boss.VENERABLE_4]: {
		id: Boss.VENERABLE_4,
		boss: true,
		name: 'vener4',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 40,
		balanced: false,
		hp: 700,
		odds: 100,
		skills: [Skill.M_VENERABLE],
		xp: 100,
		zones: [],
		canBeCaptured: false,
		noMove: true,
		display: 'vener'
	},
	[Boss.SCORPIOUS]: {
		id: Boss.SCORPIOUS,
		boss: true,
		name: 'scorpu',
		level: 90,
		elements: {
			fire: 40,
			wood: 30,
			water: 20,
			lightning: 0,
			air: 30
		},
		bonus_attack: 0,
		bonus_defense: 0,
		balanced: false,
		hp: 1200,
		odds: 100,
		xp: 800,
		skills: [
			Skill.PERCEPTION,
			Skill.M_ELEMENTAL,
			Skill.CELERITE,
			Skill.COUP_DOUBLE,
			Skill.FOCUS,
			Skill.CARAPACE,
			Skill.BRAVE,
			Skill.ZERO_ABSOLU,
			Skill.CLONE_AQUEUX,
			Skill.SOUFFLE_DE_VIE
		],
		zones: [],
		canBeCaptured: false
	},
	[Boss.YAKUZI]: {
		id: Boss.YAKUZI,
		boss: true,
		name: 'yakuzi',
		level: 15,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 22,
		bonus_defense: 22,
		balanced: true,
		hp: 50,
		odds: 100,
		skills: [Skill.M_YAKUZI, Skill.PERCEPTION],
		zones: [],
		canBeCaptured: false
	},
	[Boss.DARK_MEGASHROOM]: {
		id: Boss.DARK_MEGASHROOM,
		boss: true,
		name: 'megoup',
		level: 7,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 60,
		bonus_defense: 12,
		balanced: true,
		hp: 50,
		odds: 100,
		skills: [Skill.M_CONTAMINATION],
		zones: [],
		canBeCaptured: false
	},
	[Boss.DARK_MEGASHROOM_2]: {
		id: Boss.DARK_MEGASHROOM_2,
		boss: true,
		name: 'megou2',
		level: 7,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 60,
		bonus_defense: 12,
		balanced: true,
		hp: 50,
		odds: 100,
		xp: 60,
		skills: [Skill.M_CONTAMINATION],
		zones: [],
		canBeCaptured: false
	},
	[Boss.MASKED_KORGON]: {
		id: Boss.MASKED_KORGON,
		boss: true,
		name: 'kvenbs',
		level: 15,
		elements: {
			fire: 6,
			wood: 12,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 0,
		balanced: true,
		hp: 60,
		odds: 100,
		skills: [Skill.M_CURSED_WAND, Skill.LANCEUR_DE_GLAND],
		zones: [],
		canBeCaptured: false,
		display: 'kmask'
	},
	[Boss.SOUTHERN_KORGON]: {
		id: Boss.SOUTHERN_KORGON,
		boss: true,
		name: 'ksudbs',
		level: 35,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 40,
		bonus_defense: 30,
		balanced: true,
		hp: 150,
		odds: 100,
		skills: [Skill.M_CURSED_WAND, Skill.LANCEUR_DE_GLAND],
		zones: [],
		canBeCaptured: false
	},
	[Boss.BIO_METALIC_LEECH]: {
		id: Boss.BIO_METALIC_LEECH,
		boss: true,
		name: 'saboss',
		level: 80,
		elements: {
			fire: 20,
			wood: 5,
			water: 30,
			lightning: 20,
			air: 30
		},
		bonus_attack: 0,
		bonus_defense: 0,
		balanced: false,
		hp: 500,
		odds: 100,
		xp: 150,
		skills: [Skill.PERCEPTION, Skill.M_INITIATIVE_RESET],
		zones: [],
		canBeCaptured: false
	},
	[Boss.DEMYOM_DEFENDER]: {
		id: Boss.DEMYOM_DEFENDER,
		boss: true,
		name: 'cuzbos',
		level: 30,
		elements: {
			fire: 10,
			wood: 20,
			water: 10,
			lightning: 10,
			air: 10
		},
		bonus_attack: 0,
		bonus_defense: 0,
		balanced: true,
		hp: 300,
		odds: 100,
		xp: 50,
		skills: [Skill.M_DEMYOM_ATTACK, Skill.M_DEMYOM_HEAL],
		zones: [],
		canBeCaptured: false
	},
	[Boss.GROTOX]: {
		// This boss has a weird patch in the source code
		// It's not implemented as it's unclear if we need it
		id: Boss.GROTOX,
		boss: true,
		name: 'frking',
		level: 30,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 40,
		bonus_defense: 30,
		balanced: true,
		hp: 50,
		odds: 100,
		skills: [Skill.M_GROTOX],
		zones: [],
		canBeCaptured: false
	},
	[Boss.BEHEMOUNT]: {
		id: Boss.BEHEMOUNT,
		boss: true,
		name: 'behem2',
		level: 75,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 80,
		bonus_defense: 120,
		balanced: false,
		hp: 500,
		odds: 100,
		skills: [],
		zones: [],
		canBeCaptured: false
	},
	[Boss.SERPETHER]: {
		id: Boss.SERPETHER,
		boss: true,
		name: 'serpe',
		level: 75,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 60,
		bonus_defense: 110,
		balanced: false,
		hp: 1000,
		xp: 500,
		odds: 100,
		noMove: true,
		skills: [Skill.M_GRIZOU, Skill.CELERITE, Skill.COUP_DOUBLE, Skill.SOURCE_DE_VIE],
		zones: [],
		canBeCaptured: false
	},
	[Boss.SERPETHER_2]: {
		id: Boss.SERPETHER_2,
		boss: true,
		name: 'serpe2',
		level: 75,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 70,
		bonus_defense: 120,
		balanced: false,
		hp: 1000,
		odds: 100,
		noMove: true,
		skills: [Skill.M_GRIZOU],
		zones: [],
		canBeCaptured: false
	},
	[Boss.MORG]: {
		id: Boss.MORG,
		boss: true,
		name: 'morg',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 60,
		bonus_defense: 90,
		balanced: false,
		hp: 500,
		xp: 400,
		odds: 100,
		skills: [Skill.FEU_DE_ST_ELME, Skill.FOCUS, Skill.CELERITE],
		zones: [],
		canBeCaptured: false
	},
	[Boss.MORG_2]: {
		id: Boss.MORG_2,
		boss: true,
		name: 'morgu',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 60,
		bonus_defense: 90,
		balanced: false,
		hp: 500,
		xpBonus: 10,
		odds: 100,
		skills: [Skill.FEU_DE_ST_ELME, Skill.FOCUS, Skill.CELERITE],
		zones: [],
		canBeCaptured: false
	},
	[Boss.MUTATED_MORG]: {
		id: Boss.MUTATED_MORG,
		boss: true,
		name: 'morg2',
		level: 60,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 55,
		bonus_defense: 100,
		balanced: false,
		hp: 800,
		xp: 500,
		odds: 100,
		noMove: true,
		skills: [Skill.M_GRIZOU],
		zones: [],
		canBeCaptured: false
	},
	[Boss.GRIZORG]: {
		id: Boss.GRIZORG,
		boss: true,
		name: 'grizor',
		level: 80,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 65,
		bonus_defense: 90,
		balanced: false,
		hp: 700,
		xp: 0,
		gold: 0,
		odds: 100,
		noMove: true,
		skills: [Skill.M_GRIZOU],
		zones: [],
		canBeCaptured: false
	},
	[Boss.GRIZOU]: {
		id: Boss.GRIZOU,
		boss: true,
		name: 'grizou',
		level: 80,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 200,
		bonus_defense: 400,
		balanced: false,
		hp: 1000,
		xp: 0,
		gold: 0,
		odds: 100,
		noMove: true,
		skills: [Skill.M_GRIZOU],
		zones: [],
		canBeCaptured: false
	},
	[Boss.MUTATED_GRIZORG]: {
		id: Boss.MUTATED_GRIZORG,
		boss: true,
		name: 'grizo2',
		level: 90,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 120,
		bonus_defense: 150,
		balanced: false,
		hp: 1200,
		xp: 0,
		gold: 0,
		odds: 100,
		noMove: true,
		skills: [Skill.M_GRIZOU],
		zones: [],
		canBeCaptured: false
	},
	[Boss.ULTIMATE_GRIZORG]: {
		id: Boss.ULTIMATE_GRIZORG,
		boss: true,
		name: 'grizo3',
		level: 99,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 150,
		bonus_defense: 150,
		balanced: false,
		hp: 1800,
		xp: 0,
		gold: 0,
		odds: 100,
		noMove: true,
		skills: [Skill.M_GRIZOU],
		zones: [],
		canBeCaptured: false
	},
	[Boss.SOFIA]: {
		id: Boss.SOFIA,
		boss: true,
		name: 'sofia',
		level: 85,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 250,
		bonus_defense: 100,
		balanced: false,
		hp: 5000,
		odds: 100,
		noMove: true,
		skills: [Skill.M_GRIZOU],
		zones: [],
		canBeCaptured: false
	},
	[Boss.CHIEF_DOROGON]: {
		id: Boss.CHIEF_DOROGON,
		boss: true,
		name: 'dorou',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 55,
		bonus_defense: 85,
		balanced: false,
		hp: 450,
		xpBonus: 10,
		odds: 100,
		skills: [Skill.FEU_DE_ST_ELME, Skill.FOCUS, Skill.CELERITE],
		zones: [],
		canBeCaptured: false
	}
};
