import { Skill } from '../dinoz/SkillList.mjs';
import { MapZone } from '../enums/MapZone.mjs';
import { MonsterFiche } from './MonsterFiche.mjs';

export enum Boss {
	TOWER_GUARDIAN = 'TOWER_GUARDIAN',
	SUMMIT_GUARDIAN = 'SUMMIT_GUARDIAN',
	LOWER_GUARDIAN = 'LOWER_GUARDIAN',
	ELEMENTAIRE_FEU = 'ELEMENTAIRE_FEU',
	ELEMENTAIRE_EAU = 'ELEMENTAIRE_EAU',
	RASCAPHANDRE = 'RASCAPHANDRE',
	ELEMENTAIRE_TERRE = 'ELEMENTAIRE_TERRE',
	PTEROZ = 'PTEROZ',
	HIPPOCLAMP = 'HIPPOCLAMP',
	ROCKY = 'ROCKY',
	MASTER_CHA = 'MASTER_CHA',
	PIRHANOS_3 = 'PIRHANOS_3',
	TW_BIGBEASTLY = 'TW_BIGBEASTLY',
	PR_IGOR = 'PR_IGOR',
	VENERABLE = 'VENERABLE',
	VENERABLE_2 = 'VENERABLE_2',
	VENERABLE_3 = 'VENERABLE_3',
	VENERABLE_4 = 'VENERABLE_4',
	SCORPIOUS = 'SCORPIOUS',
	YAKUZI = 'YAKUZI',
	DARK_MEGASHROOM = 'DARK_MEGASHROOM',
	DARK_MEGASHROOM_2 = 'DARK_MEGASHROOM_2',
	MASKED_KORGON = 'MASKED_KORGON',
	SOUTHERN_KORGON = 'SOUTHERN_KORGON',
	BIO_METALIC_LEECH = 'BIO_METALIC_LEECH',
	DEMYOM_DEFENDER = 'DEMYOM_DEFENDER',
	GROTOX = 'GROTOX',
}

export const bossList: Readonly<Record<Boss, MonsterFiche>> = {
	[Boss.TOWER_GUARDIAN]: {
		id: Boss.TOWER_GUARDIAN,
		name: 'towgrd',
		hp: 300,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		gold: 0,
		xp: 40,
		odds: 100,
		level: 30,
		zones: [],
		canBeCaptured: false,
		skills: [Skill.M_ELEMENTAL]
	},
	[Boss.SUMMIT_GUARDIAN]: {
		id: Boss.SUMMIT_GUARDIAN,
		name: 'upgrd',
		level: 40,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		groups: [1, 0, 0],
		hp: 500,
		xp: 40,
		odds: 100,
		zones: [],
		canBeCaptured: false,
		skills: [Skill.M_ELEMENTAL]
	},
	[Boss.LOWER_GUARDIAN]: {
		id: Boss.LOWER_GUARDIAN,
		name: 'updwn',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		groups: [1, 0, 0],
		hp: 600,
		xp: 60,
		odds: 100,
		zones: [],
		canBeCaptured: false,
		skills: [Skill.M_ELEMENTAL]
	},
	[Boss.ELEMENTAIRE_FEU]: {
		id: Boss.ELEMENTAIRE_FEU,
		name: 'efire',
		hp: 60,
		elements: {
			fire: 4,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		gold: 0,
		xp: 50,
		odds: 1,
		level: 5,
		zones: [MapZone.DARKWORLD],
		canBeCaptured: false,
	},
	[Boss.ELEMENTAIRE_EAU]: {
		id: Boss.ELEMENTAIRE_EAU,
		name: 'ewater',
		hp: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 4,
			lightning: 0,
			air: 0
		},
		gold: 0,
		xp: 50,
		odds: 1,
		level: 5,
		zones: [MapZone.DARKWORLD],
		canBeCaptured: false,
	},
	[Boss.RASCAPHANDRE]: {
		id: Boss.RASCAPHANDRE,
		name: 'rasca',
		hp: 60,
		elements: {
			fire: 1,
			wood: 2,
			water: 8,
			lightning: 1,
			air: 2
		},
		gold: 0,
		xp: 100,
		odds: 1,
		level: 10,
		zones: [MapZone.ILES],
		canBeCaptured: false,
	},
	[Boss.ELEMENTAIRE_TERRE]: {
		id: Boss.ELEMENTAIRE_TERRE,
		name: 'eearth',
		hp: 100,
		elements: {
			fire: 2,
			wood: 8,
			water: 2,
			lightning: 2,
			air: 2
		},
		gold: 0,
		xp: 100,
		odds: 1,
		level: 10,
		zones: [MapZone.ILES],
		canBeCaptured: false,
	},
	[Boss.PTEROZ]: {
		id: Boss.PTEROZ,
		name: 'pteroz',
		hp: 70,
		elements: {
			fire: 4,
			wood: 1,
			water: 0,
			lightning: 2,
			air: 3
		},
		gold: 0,
		xp: 50,
		odds: 1,
		level: 7,
		zones: [MapZone.ALL],
		skills: [11102, 11103, 41102, 11101, 51105],
		canBeCaptured: false,
	},
	[Boss.HIPPOCLAMP]: {
		id: Boss.HIPPOCLAMP,
		name: 'hippo',
		hp: 70,
		elements: {
			fire: 2,
			wood: 4,
			water: 3,
			lightning: 1,
			air: 1
		},
		gold: 0,
		xp: 50,
		odds: 1,
		level: 7,
		zones: [MapZone.ALL],
		skills: [21101, 21102, 31101, 21103],
		canBeCaptured: false,
	},
	[Boss.ROCKY]: {
		id: Boss.ROCKY,
		name: 'rocky',
		hp: 100,
		elements: {
			fire: 1,
			wood: 2,
			water: 3,
			lightning: 6,
			air: 3
		},
		gold: 0,
		xp: 50,
		odds: 1,
		level: 12,
		zones: [MapZone.ALL],
		skills: [21101, 41102, 41301, 41103, 41204],
		canBeCaptured: false,
	},
	[Boss.MASTER_CHA]: {
		id: Boss.MASTER_CHA,
		name: 'mcha',
		level: 80,
		elements: {
			fire: 20,
			wood: 40,
			water: 20,
			lightning: 40,
			air: 20
		},
		bonus_attack: 0,
		bonus_defense: 0,
		hp: 500,
		odds: 100,
		xp: 200,
		skills: [
			Skill.BRAVE,
			Skill.ZERO_ABSOLU,
			Skill.CLONE_AQUEUX,
			Skill.MUR_DE_BOUE,
			// Missing Skill.SKILL_FORGER
			Skill.MAINS_COLLANTES,
			Skill.BERSERK,
			Skill.AMAZONIE,
			Skill.PERCEPTION,
			Skill.M_ELECTROCUTION
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.PIRHANOS_3]: {
		id: Boss.PIRHANOS_3,
		name: 'pirao3',
		zones: [],
		level: 15,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 30,
		bonus_defense: 20,
		odds: 100,
		hp: 30,
		groups: [0, 0, 1],
		xp: 50,
		skills: [Skill.M_FLIGHT],
		canBeCaptured: false,
	},
	[Boss.TW_BIGBEASTLY]: {
		id: Boss.TW_BIGBEASTLY,
		name: 'wbour2',
		level: 35,
		elements: {
			fire: 0,
			wood: 11,
			water: 0,
			lightning: 20,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 0,
		hp: 300,
		odds: 100,
		xp: 50,
		skills: [
			Skill.CELERITE,
			Skill.ATTAQUE_ECLAIR,
			Skill.FOUDRE,
			Skill.COUP_DOUBLE,
			Skill.DANSE_FOUDROYANTE,
			Skill.M_RESISTANCE
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.PR_IGOR]: {
		id: Boss.PR_IGOR,
		name: 'igor',
		level: 20,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 20,
		bonus_defense: 20,
		hp: 200,
		odds: 100,
		skills: [
			Skill.M_RESISTANCE,
			Skill.M_INVISIBILITY,
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.VENERABLE]: {
		id: Boss.VENERABLE,
		name: 'vener',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 60,
		hp: 1000,
		odds: 100,
		skills: [
			Skill.M_VENERABLE,
		],
		xp: 1000,
		zones: [],
		canBeCaptured: false,
		noMove: true,
	},
	[Boss.VENERABLE_2]: {
		id: Boss.VENERABLE_2,
		name: 'vener2',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 60,
		hp: 1000,
		odds: 100,
		skills: [
			Skill.M_VENERABLE,
		],
		xp: 0,
		zones: [],
		canBeCaptured: false,
		noMove: true,
	},
	[Boss.VENERABLE_3]: {
		id: Boss.VENERABLE_3,
		name: 'vener3',
		level: 20,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 5,
		hp: 500,
		odds: 100,
		skills: [
			Skill.M_VENERABLE,
		],
		xp: 0,
		gold: 0,
		zones: [],
		canBeCaptured: false,
		noMove: true,
	},
	[Boss.VENERABLE_4]: {
		id: Boss.VENERABLE_4,
		name: 'vener4',
		level: 50,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 40,
		hp: 700,
		odds: 100,
		skills: [
			Skill.M_VENERABLE,
		],
		xp: 100,
		zones: [],
		canBeCaptured: false,
		noMove: true,
	},
	[Boss.SCORPIOUS]: {
		id: Boss.SCORPIOUS,
		name: 'scorpu',
		level: 90,
		elements: {
			fire: 40,
			wood: 30,
			water: 20,
			lightning: 0,
			air: 30
		},
		bonus_attack: 0,
		bonus_defense: 0,
		hp: 1200,
		odds: 100,
		xp: 800,
		skills: [
			Skill.PERCEPTION,
			Skill.M_ELEMENTAL,
			Skill.CELERITE,
			Skill.COUP_DOUBLE,
			Skill.FOCUS,
			Skill.CARAPACE,
			Skill.BRAVE,
			Skill.ZERO_ABSOLU,
			Skill.CLONE_AQUEUX,
			Skill.SOUFFLE_DE_VIE,
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.YAKUZI]: {
		id: Boss.YAKUZI,
		name: 'yakuzi',
		level: 15,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 22,
		bonus_defense: 22,
		hp: 50,
		odds: 100,
		skills: [
			Skill.M_YAKUZI,
			Skill.PERCEPTION,
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.DARK_MEGASHROOM]: {
		id: Boss.DARK_MEGASHROOM,
		name: 'megoup',
		level: 7,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 60,
		bonus_defense: 12,
		hp: 50,
		odds: 100,
		skills: [
			Skill.M_CONTAMINATION,
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.DARK_MEGASHROOM_2]: {
		id: Boss.DARK_MEGASHROOM_2,
		name: 'megou2',
		level: 7,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 60,
		bonus_defense: 12,
		hp: 50,
		odds: 100,
		xp: 60,
		skills: [
			Skill.M_CONTAMINATION,
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.MASKED_KORGON]: {
		id: Boss.MASKED_KORGON,
		name: 'kvenbs',
		level: 15,
		elements: {
			fire: 6,
			wood: 12,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 0,
		bonus_defense: 0,
		hp: 60,
		odds: 100,
		skills: [
			Skill.M_CURSED_WAND,
			Skill.LANCEUR_DE_GLAND,
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.SOUTHERN_KORGON]: {
		id: Boss.SOUTHERN_KORGON,
		name: 'ksudbs',
		level: 35,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 40,
		bonus_defense: 30,
		hp: 150,
		odds: 100,
		skills: [
			Skill.M_CURSED_WAND,
			Skill.LANCEUR_DE_GLAND,
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.BIO_METALIC_LEECH]: {
		id: Boss.BIO_METALIC_LEECH,
		name: 'saboss',
		level: 80,
		elements: {
			fire: 20,
			wood: 5,
			water: 30,
			lightning: 20,
			air: 30
		},
		bonus_attack: 0,
		bonus_defense: 0,
		hp: 500,
		odds: 100,
		xp: 150,
		skills: [
			Skill.PERCEPTION,
			Skill.M_INITIATIVE_RESET,
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.DEMYOM_DEFENDER]: {
		id: Boss.DEMYOM_DEFENDER,
		name: 'cuzbos',
		level: 30,
		elements: {
			fire: 10,
			wood: 20,
			water: 10,
			lightning: 10,
			air: 10
		},
		bonus_attack: 0,
		bonus_defense: 0,
		hp: 300,
		odds: 100,
		xp: 50,
		skills: [
			Skill.M_DEMYOM_ATTACK,
			Skill.M_DEMYOM_HEAL,
		],
		zones: [],
		canBeCaptured: false,
	},
	[Boss.GROTOX]: {
		id: Boss.GROTOX,
		name: 'frking',
		level: 30,
		elements: {
			fire: 0,
			wood: 0,
			water: 0,
			lightning: 0,
			air: 0
		},
		bonus_attack: 40,
		bonus_defense: 30,
		hp: 50,
		odds: 100,
		skills: [
			Skill.M_BOOM,
		],
		zones: [],
		canBeCaptured: false,
	},
};
