/**
 * Every fight background key understood by the animation engine — the keys of `ref` in
 * `@eternaltwin/dinorpg_animations/src/gfx/backgrounds.js`, which `Scene.setBackground` looks
 * a fight's `bg` up in. Anything outside this list renders no background at all.
 *
 * `placeList.background` picks from the same namespace, and so does a dungeon's
 * `fightBackgrounds` pool. Note `ed-ui/src/assets/battle/*.webp` is a *different*, partly
 * overlapping set of decorative files — only ~2/3 of these keys have a file of the same name
 * there, so it cannot be used as the source of truth.
 */
export const fightBackgroundList = [
	'broc',
	'c_labo',
	'c_palais',
	'c_porte',
	'c_reacteur',
	'c_rocher',
	'c_skull',
	'c_trone',
	'c_usine',
	'c_ville',
	'cave1',
	'cave2',
	'cave3',
	'cave4',
	'cavern2',
	'city2',
	'clinique1',
	'clinique2',
	'debug',
	'desert0',
	'desert1',
	'desert5',
	'dnv_chateau',
	'dnv_portal',
	'dnv_trone',
	'dojo_arene',
	'dojo_champion',
	'fond_champion',
	'i_cite',
	'i_egout',
	'i_lac',
	'i_lac2',
	'i_lacroc',
	'i_mont',
	'i_observ',
	'i_palais',
	'i_plaine',
	'i_pont',
	'i_porte',
	'i_prison',
	'i_rocher',
	'i_sommet',
	'i_ville1',
	'i_ville2',
	'i_voie',
	'm_antraxov',
	'm_campdelite',
	'm_cuzcous',
	'm_grotox',
	'm_kazekami',
	'm_outpost_frutox',
	'm_outpost_vegetox',
	'm_port',
	's_auree',
	's_baobob',
	's_camp',
	's_campRogues',
	's_campWanwans',
	's_caushDoor',
	's_caushEnt',
	's_cef',
	's_chemin',
	's_chutes',
	's_cinema',
	's_colesc',
	's_collin',
	's_corail',
	's_desertEnt',
	's_devor',
	's_dkBaobob',
	's_dkChutes',
	's_dkSwamp',
	's_dnv',
	's_dome',
	's_fleuve',
	's_forges',
	's_fosslv',
	's_fountj',
	's_frcbrt',
	's_garde',
	's_graveyard',
	's_iceberg2',
	's_ilewkk',
	's_jungle',
	's_king',
	's_labo2',
	's_papy',
	's_pentes',
	's_plaza',
	's_port',
	's_pylon',
	's_rashpk',
	's_syphon',
	's_totem',
	's_tunel',
	's_univ',
	's_vener',
	'snow2',
	'snow4',
	'swp_clear',
	'swp_fog',
	'temple3',
	'villa'
] as const;

export type FightBackground = (typeof fightBackgroundList)[number];

export function isFightBackground(value: string): value is FightBackground {
	return (fightBackgroundList as readonly string[]).includes(value);
}
