export const raceList = {
	0: 'moueffe',
	1: 'pigmou',
	2: 'winks',
	3: 'planaille',
	4: 'castivore',
	5: 'rocky',
	6: 'pteroz',
	7: 'nuagoz',
	8: 'sirain',
	9: 'hippoclamp',
	10: 'gorilloz',
	11: 'wanwan',
	12: 'santaz',
	13: 'feross',
	14: 'kabuki',
	15: 'mahamuti',
	16: 'soufflet',
	17: 'toufufu',
	18: 'quetzu',
	19: 'smog',
	20: 'triceragnon'
};
