export enum ClanHistoryType {
	CLAN_CREATED = 'CLAN_CREATED',
	PLAYER_JOIN = 'PLAYER_JOIN',
	PLAYER_LEAVE = 'PLAYER_LEAVE',
	PLAYER_EXCLUSION = 'PLAYER_EXCLUSION',
	CASTLE_BUILD = 'CASTLE_BUILD',
	CASTLE_REBUILD = 'CASTLE_REBUILD',
	NEW_LEADER = 'NEW_LEADER',
	WAR_START = 'WAR_START',
	WAR_ATTACKED = 'WAR_ATTACKED',
	WAR_LOSE = 'WAR_LOSE',
	WAR_DEFENDED = 'WAR_DEFENDED',
	WAR_WON = 'WAR_WON',
	WAR_FORFEIT = 'WAR_FORFEIT',
	WAR_PLAYER_ATTACKED = 'WAR_PLAYER_ATTACKED',
	WAR_PLAYER_ATTACK = 'WAR_PLAYER_ATTACK',
	WAR_CANCELLED = 'WAR_CANCELLED'
}
