export enum ClanMemberRight {
	PAGE_MANAGE = 'PAGE_MANAGE',
	MEMBER_ACCEPT_AND_DENY_REQUESTS = 'MEMBER_ACCEPT_AND_DENY_REQUESTS',
	MEMBER_EXCLUDE = 'MEMBER_EXCLUDE',
	MEMBER_EDIT = 'MEMBER_EDIT',
	DISCUSSION_DELETE_MESSAGE = 'DISCUSSION_DELETE_MESSAGE',
	CLAN_EDIT_BANNER = 'CLAN_EDIT_BANNER',
	CLAN_EDIT_LANG = 'CLAN_EDIT_LANG'
}
