export enum RaceEnum {
	MOUEFFE = 1,
	// RESERVED_A = 2, intentionally commented to avoid conflicts with historical data
	PIGMOU = 3,
	// RESERVED_B = 4, intentionally commented to avoid conflicts with historical data
	WINKS = 5,
	// RESERVED_C = 6, intentionally commented to avoid conflicts with historical data
	PLANAILLE = 7,
	// RESERVED_D = 8, intentionally commented to avoid conflicts with historical data
	CASTIVORE = 9,
	ROCKY = 10,
	PTEROZ = 11,
	NUAGOZ = 12,
	SIRAIN = 13,
	HIPPOCLAMP = 14,
	GORILLOZ = 15,
	// RESERVED_E = 16, intentionally commented to avoid conflicts with historical data
	WANWAN = 17,
	// RESERVED_F = 18, intentionally commented to avoid conflicts with historical data
	SANTAZ = 19,
	FEROSS = 20,
	KABUKI = 21,
	// RESERVED_G = 22, intentionally commented to avoid conflicts with historical data
	MAHAMUTI = 23,
	SOUFFLET = 24,
	TOUFUFU = 25,
	QUETZU = 26,
	SMOG = 27,
	TRICERAGNON = 28
}
