export enum StatTracking {
	MOVES = 'moves', // OK
	DEATHS = 'deaths', //OK
	P_DAYS = 'pdays', //OK
	LVL_UP = 'lvlup', //OK
	KILL_M = 'killm', //OK
	KILL_D = 'killd', //TODO: kill dinoz
	HEAL_PV = 'healpv', //OK
	UP_WOOD = 'upwood', //OK
	UP_FIRE = 'upfire', //OK
	UP_LIGHTNING = 'upthun', //OK
	UP_AIR = 'upair', //OK
	UP_WATER = 'upwatr', //OK
	BROKEN_SHOVEL = 'brkpel', //OK
	CHASSE = 'chasse', //OK
	CUEILLE = 'cueill', //OK
	FISH = 'peche', //OK
	ENERGY = 'energy', //OK
	SEEK = 'fouill', //OK
	MARKET = 'market', //OK
	S_BUYER = 'sbuyer', //OK
	CLANS = 'clans', //OK
	BEAUTY = 'beauty',
	GDC_ATK = 'gdcatt',
	GDC_DEF = 'gdcdef',
	BGUM = 'bgum',
	// EPIC REWARDS
	PERLE = 'perle',
	PTEROZ = 'pteroz',
	HIPPO = 'hippo',
	ROCKY = 'rocky',
	QUETZU = 'quetzu',
	TOUR = 'tour',
	VENER = 'vener',
	TAURUS = 'taurus',
	MSG = 'msg',
	MAGNET = 'magnet',
	PLUME = 'plume',
	KAURA = 'kaura',
	DEMON = 'demon',
	PMI = 'pmi',
	PDA = 'pda',
	DICARB = 'dicarb',
	TID1 = 'tid1',
	BELIUS = 'belius',
	CAUSH = 'caush',
	FMEDAL = 'fmedal',
	LABOWI = 'labowi',
	MEDAL_1 = 'medgol',
	MEDAL_2 = 'medsil',
	MEDAL_3 = 'medbro',
	MEDAL_4 = 'medpla',
	LEVELUP_1 = 'lvlup1',
	LEVELUP_2 = 'lvlup2',
	CARD = 'card',
	PAC = 'pac'
}
