export enum TournamentNamePrefix {
	ANNE = 'anne',
	ALT = 'alt',
	BOR = 'bor',
	BEL = 'bel',
	CRI = 'cri',
	CASSE = 'casse',
	COM = 'com',
	DUR = 'dur',
	DAS = 'das',
	DE = 'de',
	ETA = 'eta',
	EX = 'ex',
	FOU = 'fou',
	GRO = 'gro',
	GLA = 'gla',
	GENTI = 'genti',
	HENRI = 'henri',
	IPPO = 'ippo',
	IVA = 'iva',
	JUL = 'jul',
	KRA = 'kra',
	KROL = 'krol',
	LE = 'le',
	LUDO = 'ludo',
	MOU = 'mou',
	MOL = 'mol',
	NICO = 'nico',
	NUL = 'nul',
	PTI = 'pti',
	POL = 'pol',
	PA = 'pa',
	QUA = 'qua',
	RA = 'ra',
	ROU = 'rou',
	SUPER = 'super',
	SAL = 'sal',
	TRUC = 'truc',
	TOP = 'top',
	ULTI = 'ulti',
	VON = 'von',
	VA = 'va',
	YAKA = 'yaka'
}

export enum TournamentNameMiddle {
	LAP = 'lap',
	LIM = 'lim',
	LUT = 'lut',
	LES = 'les',
	LOP = 'lop',
	DAT = 'dat',
	DIG = 'dig',
	DUP = 'dup',
	DES = 'des',
	DON = 'don',
	MAK = 'mak',
	MIN = 'min',
	MUG = 'mug',
	MEL = 'mel',
	MOUL = 'moul',
	TAP = 'tap',
	TIG = 'tig',
	TUT = 'tut',
	TES = 'tes',
	TON = 'ton'
}

export enum TournamentNameSuffix {
	OR = 'or',
	ERE = 'ere',
	US = 'us',
	OS = 'os',
	OX = 'ox',
	EE = 'ee',
	ULE = 'ule',
	ISSE = 'isse',
	SA = 'sa',
	ON = 'on',
	AR = 'ar',
	ASSE = 'asse',
	IEUX = 'ieux',
	OURG = 'ourg',
	AISE = 'aise'
}

export enum TournamentNameTitle {
	LE_GRAND = 'leGrand',
	LE_MAGNIFIQUE = 'leMagnifique',
	L_ARME_ULTIME = 'lArmeUltime',
	LE_TUEUR = 'leTueur',
	L_EXTERMINATEUR = 'lExterminateur',
	LE_GENTIL = 'leGentil',
	LE_TIMIDE = 'leTimide',
	LE_CATCHEUR = 'leCatcheur',
	L_ETERNEL = 'lEternel',
	LE_PUISSANT = 'lePuissant',
	LE_BOSS = 'leBoss',
	LE_DERATISEUR = 'leDeratiseur',
	LE_FAIBLE = 'leFaible',
	LE_PEUREUX = 'lePeureux',
	EL_TOREADOR = 'elToreador',
	THE_KILLER = 'theKiller',
	LE_GEANT = 'leGeant',
	LE_GLADIATEUR = 'leGladiateur',
	LE_CONQUERANT = 'leConquerant',
	LE_PRETENTIEUX = 'lePretentieux',
	LE_DOMPTEUR = 'leDompteur',
	LE_LAUREAT = 'leLaureat',
	LE_SUPERBE = 'leSuperbe',
	LE_FIER = 'leFier',
	LE_CHARMEUR = 'leCharmeur',
	LE_BRILLANT = 'leBrillant',
	LE_SORCIER = 'leSorcier',
	LE_PRODIGIEUX = 'leProdigieux',
	LE_BIENVEILLANT = 'leBienveillant'
}

export enum TournamentNameQuality {
	DU_75 = 'du75',
	DU_33 = 'du33',
	DE_DINOVILLE = 'deDinoville',
	ENCHANTE = 'enchante',
	MAGIQUE = 'magique',
	ROUGE = 'rouge',
	NOIR = 'noir',
	SURDOUE = 'surdoue',
	INDIGENT = 'indigent',
	SURPUISSANT = 'surpuissant',
	DESTRUCTEUR = 'destructeur',
	APOCALYPTIQUE = 'apocalyptique',
	NUM_2000 = '2000',
	NUM_3000 = '3000',
	POILU = 'poilu',
	ACERE = 'acere',
	EN_ACIER = 'enAcier',
	EN_OR = 'enOr',
	EN_CARTON = 'enCarton',
	VU_A_LA_TELE = 'vualaTele',
	FANTASTIQUE = 'fantastique',
	INSIGNIFIANT = 'insignifiant',
	INUTILE = 'inutile',
	IDIOT = 'idiot',
	PERIME = 'perime',
	INVISIBLE = 'invisible'
}
