export enum TournamentNamePrefix {
	ANNE = 'Anne',
	ALT = 'Alt',
	BOR = 'Bor',
	BEL = 'Bel',
	CRI = 'Cri',
	CASSE = 'Casse',
	COM = 'Com',
	DUR = 'Dur',
	DAS = 'Das',
	DE = 'Dé',
	ETA = 'Eta',
	EX = 'Ex',
	FOU = 'Fou',
	GRO = 'Gro',
	GLA = 'Gla',
	GENTI = 'Genti',
	HENRI = 'Henri',
	IPPO = 'Ippo',
	IVA = 'Iva',
	JUL = 'Jul',
	KRA = 'Kra',
	KROL = 'Krol',
	LE = 'Le',
	LUDO = 'Ludo',
	MOU = 'Mou',
	MOL = 'Mol',
	NICO = 'Nico',
	NUL = 'Nul',
	PTI = 'Pti',
	POL = 'Pol',
	PA = 'Pa',
	QUA = 'Qua',
	RA = 'Ra',
	ROU = 'Rou',
	SUPER = 'Super',
	SAL = 'Sal',
	TRUC = 'Truc',
	TOP = 'Top',
	ULTI = 'Ulti',
	VON = 'Von',
	VA = 'Va',
	YAKA = 'Yaka'
}

export enum TournamentNameMiddle {
	LAP = 'lap',
	LIM = 'lim',
	LUT = 'lut',
	LES = 'les',
	LOP = 'lop',
	DAT = 'dat',
	DIG = 'dig',
	DUP = 'dup',
	DES = 'des',
	DON = 'don',
	MAK = 'mak',
	MIN = 'min',
	MUG = 'mug',
	MEL = 'mel',
	MOUL = 'moul',
	TAP = 'tap',
	TIG = 'tig',
	TUT = 'tut',
	TES = 'tes',
	TON = 'ton'
}

export enum TournamentNameSuffix {
	OR = 'or',
	ERE = 'ere',
	US = 'us',
	OS = 'os',
	OX = 'ox',
	EE = 'ée',
	ULE = 'ule',
	ISSE = 'isse',
	SA = 'sa',
	ON = 'on',
	AR = 'ar',
	ASSE = 'asse',
	IEUX = 'ieux',
	OURG = 'ourg',
	AISE = 'aise'
}

export enum TournamentNameTitle {
	LE_GRAND = 'le Grand',
	LE_MAGNIFIQUE = 'le Magnifique',
	L_ARME_ULTIME = "l'Arme Ultime",
	LE_TUEUR = 'le Tueur',
	L_EXTERMINATEUR = "l'Exterminateur",
	LE_GENTIL = 'le Gentil',
	LE_TIMIDE = 'le Timide',
	LE_CATCHEUR = 'le Catcheur',
	L_ETERNEL = "l'Eternel",
	LE_PUISSANT = 'le Puissant',
	LE_BOSS = 'le Boss',
	LE_DERATISEUR = 'le Dératiseur',
	LE_FAIBLE = 'le Faible',
	LE_PEUREUX = 'le Peureux',
	EL_TOREADOR = 'el Toreador',
	THE_KILLER = 'the Killer',
	LE_GEANT = 'le Géant',
	LE_GLADIATEUR = 'le Gladiateur',
	LE_CONQUERANT = 'le Conquérant',
	LE_PRETENTIEUX = 'le Prétentieux',
	LE_DOMPTEUR = 'le Dompteur',
	LE_LAUREAT = 'le Lauréat',
	LE_SUPERBE = 'le Superbe',
	LE_FIER = 'le Fier',
	LE_CHARMEUR = 'le Charmeur',
	LE_BRILLANT = 'le Brillant',
	LE_SORCIER = 'le Sorcier',
	LE_PRODIGIEUX = 'le Prodigieux',
	LE_BIENVEILLANT = 'le Bienveillant'
}

export enum TournamentNameQuality {
	DU_75 = 'du 75',
	DU_33 = 'du 33',
	DE_DINOVILLE = 'de Dinoville',
	ENCHANTE = 'Enchanté',
	MAGIQUE = 'Magique',
	ROUGE = 'Rouge',
	NOIR = 'Noir',
	SURDOUE = 'Surdoué',
	INDIGENT = 'Indigent',
	SURPUISSANT = 'Surpuissant',
	DESTRUCTEUR = 'Destructeur',
	APOCALYPTIQUE = 'Apocalyptique',
	NUM_2000 = '2000',
	NUM_3000 = '3000',
	POILU = 'Poilu',
	ACERE = 'Acéré',
	EN_ACIER = 'en Acier',
	EN_OR = 'en Or',
	EN_CARTON = 'en Carton',
	VU_A_LA_TELE = 'vu à la Télé',
	FANTASTIQUE = 'Fantastique',
	INSIGNIFIANT = 'Insignifiant',
	INUTILE = 'Inutile',
	IDIOT = 'Idiot',
	PERIME = 'Périmé',
	INVISIBLE = 'Invisible'
}
