import { ElementType } from '../enums/ElementType.mjs';
import { Energy } from '../enums/Energy.mjs';
import { Stat } from '../enums/SkillStat.mjs';
import { SkillTree } from '../enums/SkillTree.mjs';
import { SkillType } from '../enums/SkillType.mjs';
import { DinozSkillFiche } from './DinozSkillFiche.mjs';
import { raceList } from './RaceList.mjs';

export enum Skill {
	GRIFFES_ENFLAMMEES = 11101,
	COLERE = 11102,
	FORCE = 11103,
	BRASERO = 11104,
	SOUFFLE_ARDENT = 11201,
	CHARGE = 11202,
	SANG_CHAUD = 11203,
	FURIE = 11204,
	CHASSEUR_DE_GOUPIGNON = 11205,
	ARTS_MARTIAUX = 11206,
	DETONATION = 11207,
	PROPULSION_DIVINE = 11208,
	VIGILANCE = 11301,
	COEUR_ARDENT = 11302,
	COULEE_DE_LAVE = 11303,
	SIESTE = 11304,
	KAMIKAZE = 11305,
	CHASSEUR_DE_GEANT = 11306,
	BOULE_DE_FEU = 11307,
	WAIKIKIDO = 11308,
	AURA_INCANDESCENTE = 11309,
	VENGEANCE = 11310,
	COMBUSTION = 11311,
	PAUME_CHALUMEAU = 11312,
	COEUR_DU_PHOENIX = 11313,
	BOUDDHA = 11314,
	GRIFFES_INFERNALES = 11315,
	CHASSEUR_DE_DRAGON = 11401,
	BELIER = 11402,
	TORCHE = 11403,
	SELF_CONTROL = 11404,
	SPRINT = 11405,
	VENDETTA = 11406,
	METEORES = 11407,
	CHEF_DE_GUERRE = 11408,
	ARMURE_DE_BASALTE = 11409,
	MAITRE_ELEMENTAIRE = 11410,
	SALAMANDRE = 11411,
	VULCAIN = 11412,
	ARMURE_DIFRIT = 11413,
	BRAVE = 11501,
	PROTEINES_DINOZIENNES = 12101,
	EXTENUATION = 12201,
	ROUGE = 12202,
	CARAPACE_DE_MAGMA = 12301,
	CRI_DE_GUERRE = 12302,
	FIEVRE_BRULANTE = 12401,
	BENEDICTION_DARTEMIS = 12402,
	JOKER = 12403,
	ARMURE_DE_FEU = 12404,
	PAYS_DE_CENDRE = 12501,
	RECEPTACLE_ROCHEUX = 12502,
	PLUMES_DE_PHOENIX = 12503,
	ACCLAMATION_FRATERNELLE = 12504,
	POING_DE_FEU = 12505,
	CARAPACE = 21101,
	SAUVAGERIE = 21102,
	ENDURANCE = 21103,
	LANCEUR_DE_GLAND = 21104,
	VIGNES = 21201,
	RENFORTS_KORGON = 21202,
	SYMPATIQUE = 21203,
	TENACITE = 21204,
	FOUILLE = 21205,
	CROISSANCE = 21206,
	GRATTEUR = 21207,
	ETAT_PRIMAL = 21301,
	DETECTIVE = 21302,
	COCON = 21303,
	INSTINCT_SAUVAGE = 21304,
	LARGE_MACHOIRE = 21305,
	ACROBATE = 21306,
	PRINTEMPS_PRECOCE = 21307,
	CHARISME = 21308,
	RESISTANCE_A_LA_MAGIE = 21309,
	PLANIFICATEUR = 21310,
	HERITAGE_FAROE = 21311,
	EXPERT_EN_FOUILLE = 21312,
	GROSSE_BEIGNE = 21313,
	ESPRIT_GORILLOZ = 21401,
	LEADER = 21402,
	INGENIEUR = 21403,
	GEANT = 21404,
	GARDE_FORESTIER = 21405,
	ARCHEOLOGUE = 21406,
	BENEDICTION_DES_FEES = 21407,
	CHOC = 21408,
	LOUP_GAROU = 21409,
	COLOSSE = 21501,
	OXYGENATION_MUSCULAIRE = 22101,
	VERT = 22102,
	SOURCE_DE_VIE = 22201,
	VIDE_ENERGETIQUE = 22202,
	BOUCLIER_DINOZ = 22203,
	ACIDE_LACTIQUE = 22204,
	LANCER_DE_ROCHE = 22301,
	COURBATURES = 22302,
	FORCE_CONTROL = 22303,
	PEAU_DE_FER = 22304,
	CHAMPOLLION = 22401,
	COURANT_DE_VIE = 22402,
	BERSERK = 22403,
	RIVIERE_DE_VIE = 22404,
	MUR_DE_BOUE = 22501,
	PEAU_DACIER = 22502,
	SHARIGNAN = 22503,
	AMAZONIE = 22504,
	RECEPTACLE_AQUEUX = 22505,
	CANON_A_EAU = 31101,
	PERCEPTION = 31102,
	MUTATION = 31103,
	VITALITE = 31104,
	GEL = 31201,
	DOUCHE_ECOSSAISE = 31202,
	COUP_SOURNOIS = 31203,
	APPRENTI_PECHEUR = 31204,
	POCHE_VENTRALE = 31205,
	KARATE_SOUS_MARIN = 31206,
	ECAILLES_LUMINESCENTES = 31207,
	MOIGNONS_LIQUIDES = 31208,
	ZERO_ABSOLU = 31301,
	PETRIFICATION = 31302,
	ACUPUNCTURE = 31303,
	SAPEUR = 31304,
	COUP_FATAL = 31305,
	ENTRAINEMENT_SOUS_MARIN = 31306,
	PECHEUR_CONFIRME = 31307,
	MARECAGE = 31308,
	SUMO = 31309,
	SANS_PITIE = 31310,
	CLONE_AQUEUX = 31311,
	GRIFFES_EMPOISONNEES = 31312,
	DELUGE = 31313,
	PEAU_DE_SERPENT = 31314,
	RAYON_KAAR_SHER = 31401,
	MAGASINIER = 31402,
	ENTRAINEMENT_SOUS_MARIN_AVANCE = 31403,
	MAITRE_PECHEUR = 31404,
	CUISINIER = 31405,
	SANG_ACIDE = 31406,
	BULLE = 31407,
	INCREVABLE = 31408,
	ONDINE = 31409,
	MAITRE_NAGEUR = 31501,
	LEVIATHAN = 31502,
	EAU_DIVINE = 32101,
	RADIATIONS_GAMMA = 32201,
	BLEU = 32202,
	MUE_ACQUEUSE = 32301,
	CARAPACE_BLINDEE = 32302,
	DIETE_CHROMATIQUE = 32303,
	EFFLUVE_APHRODISIAQUE = 32401,
	NEMO = 32402,
	CLEPTOMANE = 32403,
	ABYSSE = 32404,
	BANNI_DES_DIEUX = 32405,
	TOURBILLON_MAGIQUE = 32501,
	HYPERVENTILATION = 32502,
	THERAPIE_DE_GROUPE = 32503,
	RECEPTACLE_TESLA = 32504,
	VITALITE_MARINE = 32505,
	INTELLIGENCE = 41101,
	FOCUS = 41102,
	CELERITE = 41103,
	REFLEX = 41104,
	CONCENTRATION = 41201,
	ATTAQUE_ECLAIR = 41202,
	PARATONNERRE = 41203,
	COUP_DOUBLE = 41204,
	REGENERESCENCE = 41205,
	PREMIERS_SOINS = 41206,
	ECLAIR_SINUEUX = 41207,
	FOUDRE = 41301,
	FISSION_ELEMENTAIRE = 41302,
	VOIE_DE_KAOS = 41303,
	PLAN_DE_CARRIERE = 41304,
	ADRENALINE = 41305,
	VOIE_DE_GAIA = 41306,
	MEDECINE = 41307,
	DANSE_FOUDROYANTE = 41308,
	EMBUCHE = 41309,
	PUREE_SALVATRICE = 41310,
	AURA_HERMETIQUE = 41311,
	CROCS_DIAMANT = 41312,
	SURVIE = 41313,
	AUBE_FEUILLUE = 41401,
	BRANCARDIER = 41402,
	BENEDICTION = 41403,
	CREPUSCULE_FLAMBOYANT = 41404,
	MARCHAND = 41405,
	REINCARNATION = 41406,
	SURCHARGE = 41408,
	ELECTROLYSE = 41409,
	GOLEM = 41410,
	RAIJIN = 41411,
	QUETZACOATL = 41412,
	ROI_DES_SINGES = 41413,
	ARCHANGE_CORROSIF = 41501,
	ARCHANGE_GENESIF = 41502,
	PRETRE = 41503,
	SOUTIEN_MORAL = 42101,
	STIMULATION_CARDIAQUE = 42201,
	JAUNE = 42202,
	MORSURE_DU_SOLEIL = 42301,
	CRAMPE_CHRONIQUE = 42303,
	BATTERIE_SUPPLEMENTAIRE = 42401,
	EINSTEIN = 42402,
	BARRIERE_ELECTRIFIEE = 42403,
	ORACLE = 42404,
	RECEPTACLE_AERIEN = 42501,
	FEU_DE_ST_ELME = 42502,
	FORCE_DE_ZEUS = 42503,
	REMANENCE_HERTZIENNE = 42504,
	AGILITE = 51101,
	STRATEGIE = 51102,
	MISTRAL = 51103,
	AIGUILLON = 51104,
	ENVOL = 51105,
	ESQUIVE = 51201,
	SAUT = 51202,
	ANALYSE = 51203,
	CUEILLETTE = 51204,
	TAICHI = 51205,
	TORNADE = 51206,
	AURA_PUANTE = 51207,
	DISQUE_VACUUM = 51301,
	ELASTICITE = 51302,
	ATTAQUE_PLONGEANTE = 51303,
	FURTIVITE = 51304,
	SPECIALISTE = 51305,
	TALON_DACHILLE = 51306,
	NUAGE_TOXIQUE = 51307,
	OEIL_DE_LYNX = 51308,
	EVEIL = 51309,
	PAUME_EJECTABLE = 51310,
	VENT_VIF = 51311,
	FORME_VAPOREUSE = 51312,
	HYPNOSE = 51313,
	SECOUSSE = 51314,
	TROU_NOIR = 51401,
	MAITRE_LEVITATEUR = 51402,
	HALEINE_FETIVE = 51403,
	MEDITATION_SOLITAIRE = 51404,
	PROFESSEUR = 51405,
	SOUFFLE_DE_VIE = 51406,
	TOTEM_ANCESTRAL_AEROPORTE = 51407,
	FUJIN = 51408,
	MEDITATION_TRANCHANTE = 51501,
	DJINN = 51502,
	HADES = 51503,
	FORME_ETHERALE = 51601,
	MAITRISE_CORPORELLE = 52101,
	BLANC = 52201,
	ANAEROBIE = 52202,
	DOUBLE_FACE = 52301,
	FLAGELLATION = 52302,
	SOUFFLE_DANGE = 52303,
	OURAGAN = 52304,
	OURANOS = 52401,
	TWINOID_500MG = 52402,
	LONDUHAUT = 52403,
	SURPLIS_DHADES = 52404,
	RECEPTABLE_THERMIQUE = 52405,
	QI_GONG = 52501,
	SYLPHIDES = 52502,
	MESSIE = 52503,
	MUTINERIE = 52504,
	MAINS_COLLANTES = 52505,
	COMPETENCE_DOUBLE = 61119,
	LIMITE_BRISEE = 61120,
	INVOCATEUR = 61121,
	FRENESIE_COLLECTIVE = 61101,
	COQUE = 61102,
	CHARGE_CORNUE = 61103,
	ROCK = 61104,
	PIETINEMENT = 61105,
	CUIRASSE = 61106,
	INSAISISSABLE = 61107,
	DEPLACEMENT_INSTANTANE = 61108,
	NAPOMAGICIEN = 61109,
	GROS_COSTAUD = 61111,
	ORIGINE_CAUSHEMESHENNE = 61112,
	ECRASEMENT = 61113,
	FORCE_DE_LUMIERE = 61114,
	CHARGE_PIGMOU = 61115,
	FORCE_DES_TENEBRES = 61116,
	BIGMAGNON = 61117,
	DUR_A_CUIRE = 61118,
	HERCOLUBUS = 41504,
	REINE_DE_LA_RUCHE = 41505,
	BIG_MAMA = 51506,
	YGGDRASIL = 41507,
	BALEINE_BLANCHE = 41508
}

// skillId are counted like this : ABCDE
// A = Element (from fire to void)
// B = Tree (Vanilla or Ether)
// C = Column of the skill
// DE = Number of the skill in this column
export const skillList: Readonly<Record<Skill, DinozSkillFiche>> = {
	// FIRE Skills
	[Skill.GRIFFES_ENFLAMMEES]: {
		id: Skill.GRIFFES_ENFLAMMEES,
		name: 'GriffesEnflammees',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_ASSAULT]: 7
		}
	},
	[Skill.COLERE]: {
		id: Skill.COLERE,
		name: 'Colere',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 20,
	},
	[Skill.FORCE]: {
		id: Skill.FORCE,
		name: 'Force',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.AIR_ASSAULT]: 1,
			[Stat.FIRE_ASSAULT]: 1,
			[Stat.LIGHTNING_ASSAULT]: 1,
			[Stat.WATER_ASSAULT]: 1,
			[Stat.WOOD_ASSAULT]: 1
		}
	},
	[Skill.BRASERO]: {
		id: Skill.BRASERO,
		name: 'Brasero',
		type: SkillType.E,
		energy: Energy.E30,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: true,
		priority: 1,
		probability: 25
	},
	[Skill.SOUFFLE_ARDENT]: {
		id: Skill.SOUFFLE_ARDENT,
		name: 'SouffleArdent',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11101],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 10,
	},
	[Skill.CHARGE]: {
		id: Skill.CHARGE,
		name: 'Charge',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11103],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.SANG_CHAUD]: {
		id: Skill.SANG_CHAUD,
		name: 'SangChaud',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11102],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.INITIATIVE]: 4
		}
	},
	[Skill.FURIE]: {
		id: Skill.FURIE,
		name: 'Furie',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11102],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_ASSAULT]: 3,
			[Stat.WATER_ASSAULT]: 3,
			[Stat.AIR_ASSAULT]: 3,
			[Stat.LIGHTNING_ASSAULT]: 3,
			[Stat.WOOD_ASSAULT]: 3,
			[Stat.FIRE_DEFENSE]: -2,
			[Stat.WATER_DEFENSE]: -2,
			[Stat.AIR_DEFENSE]: -2,
			[Stat.LIGHTNING_DEFENSE]: -2,
			[Stat.WOOD_DEFENSE]: -2
		}
	},
	[Skill.CHASSEUR_DE_GOUPIGNON]: {
		id: Skill.CHASSEUR_DE_GOUPIGNON,
		name: 'ChasseurDeGoupignon',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11101],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ARTS_MARTIAUX]: {
		id: Skill.ARTS_MARTIAUX,
		name: 'ArtsMartiaux',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11103],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.AIR_ASSAULT]: 2,
			[Stat.FIRE_ASSAULT]: 2,
			[Stat.LIGHTNING_ASSAULT]: 2,
			[Stat.WATER_ASSAULT]: 2,
			[Stat.WOOD_ASSAULT]: 2
		}
	},
	[Skill.DETONATION]: {
		id: Skill.DETONATION,
		name: 'Detonation',
		type: SkillType.E,
		energy: Energy.E60,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11104],
		isBaseSkill: false,
		isSphereSkill: true,
		priority: 1,
		probability: 10,
	},
	[Skill.PROPULSION_DIVINE]: {
		id: Skill.PROPULSION_DIVINE,
		name: 'PropulsionDivine',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11103],
		raceId: [raceList.QUETZU.raceId],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_ELEMENT]: -2,
			[Stat.FIRE_SPEED]: 0.7
		}
	},
	[Skill.VIGILANCE]: {
		id: Skill.VIGILANCE,
		name: 'Vigilance',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11206],
		isBaseSkill: false,
		isSphereSkill: false,
		globalEffects: {
			[Stat.FIRE_DEFENSE]: 5
		}
	},
	[Skill.COEUR_ARDENT]: {
		id: Skill.COEUR_ARDENT,
		name: 'CoeurArdent',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11203],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 20,
			[Stat.FIRE_ASSAULT]: 12,
			[Stat.WATER_ASSAULT]: 12,
			[Stat.AIR_ASSAULT]: 12,
			[Stat.LIGHTNING_ASSAULT]: 12,
			[Stat.WOOD_ASSAULT]: 12
		}
	},
	[Skill.COULEE_DE_LAVE]: {
		id: Skill.COULEE_DE_LAVE,
		name: 'CouleeDeLave',
		type: SkillType.A,
		energy: Energy.E25,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11205],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 8,
		probability: 5,
	},
	[Skill.SIESTE]: {
		id: Skill.SIESTE,
		name: 'Sieste',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11203],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 5,
	},
	[Skill.KAMIKAZE]: {
		id: Skill.KAMIKAZE,
		name: 'Kamikaze',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11202],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 5,
	},
	[Skill.CHASSEUR_DE_GEANT]: {
		id: Skill.CHASSEUR_DE_GEANT,
		name: 'ChasseurDeGeant',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11205],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.BOULE_DE_FEU]: {
		id: Skill.BOULE_DE_FEU,
		name: 'BouleDeFeu',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11201],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 2,
		probability: 15,
	},
	[Skill.WAIKIKIDO]: {
		id: Skill.WAIKIKIDO,
		name: 'Waikikido',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11206],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.COUNTER]: 0.1,
			[Stat.MAX_HP]: 20,
			[Stat.INITIATIVE]: -5
		}
	},
	[Skill.AURA_INCANDESCENTE]: {
		id: Skill.AURA_INCANDESCENTE,
		name: 'AuraIncandescente',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11204],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_ELEMENT]: 2
		}
	},
	[Skill.VENGEANCE]: {
		id: Skill.VENGEANCE,
		name: 'Vengeance',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11204],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.COUNTER]: 0.05
		}
	},
	[Skill.COMBUSTION]: {
		id: Skill.COMBUSTION,
		name: 'Combustion',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11201],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 10,
	},
	[Skill.PAUME_CHALUMEAU]: {
		id: Skill.PAUME_CHALUMEAU,
		name: 'PaumeChalumeau',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11206],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 2,
		probability: 15,
	},
	[Skill.COEUR_DU_PHOENIX]: {
		id: Skill.COEUR_DU_PHOENIX,
		name: 'CoeurDuPhenix',
		type: SkillType.P,
		energy: Energy.E75,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11207],
		isBaseSkill: false,
		isSphereSkill: true,
		effects: {
			[Stat.HP_REGEN]: ['x', 0.15]
		}
	},
	[Skill.BOUDDHA]: {
		id: Skill.BOUDDHA,
		name: 'Bouddha',
		type: SkillType.I,
		energy: Energy.E50,
		element: [ElementType.FIRE, ElementType.LIGHTNING, ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41201, 11206, 51309, 61121],
		raceId: [raceList.HIPPOCLAMP.raceId],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 4,
		probability: 10,
	},
	[Skill.GRIFFES_INFERNALES]: {
		id: Skill.GRIFFES_INFERNALES,
		name: 'GriffesInfernales',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11208],
		raceId: [raceList.QUETZU.raceId],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.CHASSEUR_DE_DRAGON]: {
		id: Skill.CHASSEUR_DE_DRAGON,
		name: 'ChasseurDeDragon',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11306],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.BELIER]: {
		id: Skill.BELIER,
		name: 'Belier',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11305],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.TORCHE]: {
		id: Skill.TORCHE,
		name: 'Torche',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11311],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_DEFENSE]: 10
		}
	},
	[Skill.SELF_CONTROL]: {
		id: Skill.SELF_CONTROL,
		name: 'SelfControl',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11304],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.INITIATIVE]: -3
		}
	},
	[Skill.SPRINT]: {
		id: Skill.SPRINT,
		name: 'Sprint',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE, ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11305, 41303, 61119],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.INITIATIVE]: 6
		}
	},
	[Skill.VENDETTA]: {
		id: Skill.VENDETTA,
		name: 'Vendetta',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE, ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11310, 51306, 61119],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.COUNTER]: 0.2
		}
	},
	[Skill.METEORES]: {
		id: Skill.METEORES,
		name: 'Meteores',
		type: SkillType.A,
		energy: Energy.E35,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11309],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 4,
		probability: 7,
	},
	[Skill.CHEF_DE_GUERRE]: {
		id: Skill.CHEF_DE_GUERRE,
		name: 'ChefDeGuerre',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11301],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ARMURE_DE_BASALTE]: {
		id: Skill.ARMURE_DE_BASALTE,
		name: 'ArmureDeBasalte',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE, ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11308, 21303, 61119],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ARMOR]: 3
		}
	},
	[Skill.MAITRE_ELEMENTAIRE]: {
		id: Skill.MAITRE_ELEMENTAIRE,
		name: 'MaitreElementaire',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE, ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11311, 31301, 61119],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WOOD_ELEMENT]: 2,
			[Stat.FIRE_ELEMENT]: 2
		}
	},
	[Skill.SALAMANDRE]: {
		id: Skill.SALAMANDRE,
		name: 'Salamandre',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.FIRE, ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31305, 11312, 61121],
		raceId: [raceList.FEROSS.raceId],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.VULCAIN]: {
		id: Skill.VULCAIN,
		name: 'Vulcain',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.FIRE, ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11303, 41312, 61121],
		raceId: [raceList.MOUEFFE.raceId, raceList.MOUEFFE_DEMON.raceId],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ARMURE_DIFRIT]: {
		id: Skill.ARMURE_DIFRIT,
		name: 'ArmureDIfrit',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.FIRE, ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11307, 21311, 61121],
		raceId: [raceList.PIGMOU.raceId, raceList.PIGMOU_DEMON.raceId],
		isBaseSkill: false,
		isSphereSkill: false
		// TODO: Implement AoE effect
	},
	[Skill.BRAVE]: {
		id: Skill.BRAVE,
		name: 'Brave',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11404],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 50,
			[Stat.FIRE_ELEMENT]: 6,
			[Stat.SPEED]: 0.85,
		}
	},
	[Skill.PROTEINES_DINOZIENNES]: {
		id: Skill.PROTEINES_DINOZIENNES,
		name: 'ProteinesDinozienne',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ENERGY]: 0.3
		}
	},
	[Skill.EXTENUATION]: {
		id: Skill.EXTENUATION,
		name: 'Extenuation',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [12101],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 4,
		probability: 15,
	},
	[Skill.ROUGE]: {
		id: Skill.ROUGE,
		name: 'Rouge',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [12101],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 7,
		probability: 10,
	},
	[Skill.CARAPACE_DE_MAGMA]: {
		id: Skill.CARAPACE_DE_MAGMA,
		name: 'CarapaceDeMagma',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [12201],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 30,
			[Stat.FIRE_ASSAULT]: 5
		}
	},
	[Skill.CRI_DE_GUERRE]: {
		id: Skill.CRI_DE_GUERRE,
		name: 'CriDeGuerre',
		type: SkillType.A,
		energy: Energy.E25,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [12202],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 7,
		probability: 10,
	},
	[Skill.FIEVRE_BRULANTE]: {
		id: Skill.FIEVRE_BRULANTE,
		name: 'FievreBrulante',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [12301],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MULTIHIT]: 0.3
		}
	},
	[Skill.BENEDICTION_DARTEMIS]: {
		id: Skill.BENEDICTION_DARTEMIS,
		name: 'BenedictionDArtemis',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [12301],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.JOKER]: {
		id: Skill.JOKER,
		name: 'Joker',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [12302],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ARMURE_DE_FEU]: {
		id: Skill.ARMURE_DE_FEU,
		name: 'ArmureDeFeu',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [12302],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WOOD_DEFENSE]: 20
		}
	},
	[Skill.PAYS_DE_CENDRE]: {
		id: Skill.PAYS_DE_CENDRE,
		name: 'PaysDeCendre',
		type: SkillType.E,
		energy: Energy.E35,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [12401],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 20,
	},
	[Skill.RECEPTACLE_ROCHEUX]: {
		id: Skill.RECEPTACLE_ROCHEUX,
		name: 'ReceptacleRocheux',
		type: SkillType.A,
		energy: Energy.E35,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [12402],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 7,
		probability: 15,
	},
	[Skill.PLUMES_DE_PHOENIX]: {
		id: Skill.PLUMES_DE_PHOENIX,
		name: 'PlumesDePhoenix',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [12402],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ACCLAMATION_FRATERNELLE]: {
		id: Skill.ACCLAMATION_FRATERNELLE,
		name: 'AcclamationFraternelle',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.FIRE],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [12403],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 6,
		probability: 15,
	},
	[Skill.POING_DE_FEU]: {
		id: Skill.POING_DE_FEU,
		name: 'PoingDeFeu',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.FIRE],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [12404],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_ASSAULT]: 20
		}
	},
	// WOOD Skills
	[Skill.CARAPACE]: {
		id: Skill.CARAPACE,
		name: 'Carapace',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ARMOR]: 1
		}
	},
	[Skill.SAUVAGERIE]: {
		id: Skill.SAUVAGERIE,
		name: 'Sauvagerie',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WOOD_ASSAULT]: 5
		}
	},
	[Skill.ENDURANCE]: {
		id: Skill.ENDURANCE,
		name: 'Endurance',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		globalEffects: {
			[Stat.WOOD_DEFENSE]: 2
		}
	},
	[Skill.LANCEUR_DE_GLAND]: {
		id: Skill.LANCEUR_DE_GLAND,
		name: 'LanceurDeGland',
		type: SkillType.A,
		energy: Energy.E25,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: true
	},
	[Skill.VIGNES]: {
		id: Skill.VIGNES,
		name: 'Vignes',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21101],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 2,
		probability: 20,
	},
	[Skill.RENFORTS_KORGON]: {
		id: Skill.RENFORTS_KORGON,
		name: 'RenfortsKorgon',
		type: SkillType.E,
		energy: Energy.E30,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21102],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 15,
	},
	[Skill.SYMPATIQUE]: {
		id: Skill.SYMPATIQUE,
		name: 'Sympathique',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21101],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_FOLLOWERS]: 1
		}
	},
	[Skill.TENACITE]: {
		id: Skill.TENACITE,
		name: 'Tenacite',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21102],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.FOUILLE]: {
		id: Skill.FOUILLE,
		name: 'Fouille',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21103],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.CROISSANCE]: {
		id: Skill.CROISSANCE,
		name: 'Croissance',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21103],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 20,
			[Stat.FIRE_ASSAULT]: 1,
			[Stat.WATER_ASSAULT]: 1,
			[Stat.AIR_ASSAULT]: 1,
			[Stat.LIGHTNING_ASSAULT]: 1,
			[Stat.WOOD_ASSAULT]: 1
		}
	},
	[Skill.GRATTEUR]: {
		id: Skill.GRATTEUR,
		name: 'Gratteur',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21104],
		isBaseSkill: false,
		isSphereSkill: true
	},
	[Skill.ETAT_PRIMAL]: {
		id: Skill.ETAT_PRIMAL,
		name: 'EtatPrimal',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21201],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.DETECTIVE]: {
		id: Skill.DETECTIVE,
		name: 'Detective',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21205],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.COCON]: {
		id: Skill.COCON,
		name: 'Cocon',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21206],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.HP_REGEN]: 2
		}
	},
	[Skill.INSTINCT_SAUVAGE]: {
		id: Skill.INSTINCT_SAUVAGE,
		name: 'InstinctSauvage',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21202],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WOOD_ELEMENT]: 2
		}
	},
	[Skill.LARGE_MACHOIRE]: {
		id: Skill.LARGE_MACHOIRE,
		name: 'LargeMachoire',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21206],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WOOD_ASSAULT]: 15
		}
	},
	[Skill.ACROBATE]: {
		id: Skill.ACROBATE,
		name: 'Acrobate',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21202],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.SPEED]: 0.85,
		}
	},
	[Skill.PRINTEMPS_PRECOCE]: {
		id: Skill.PRINTEMPS_PRECOCE,
		name: 'PrintempsPrecoce',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21201],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 2,
		probability: 10,
	},
	[Skill.CHARISME]: {
		id: Skill.CHARISME,
		name: 'Charisme',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21204],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_FOLLOWERS]: 1
		}
	},
	[Skill.RESISTANCE_A_LA_MAGIE]: {
		id: Skill.RESISTANCE_A_LA_MAGIE,
		name: 'ResistanceALaMagie',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21204],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 50,
	},
	[Skill.PLANIFICATEUR]: {
		id: Skill.PLANIFICATEUR,
		name: 'Planificateur',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21203],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.HERITAGE_FAROE]: {
		id: Skill.HERITAGE_FAROE,
		name: 'HeritageFaroe',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21203],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WOOD_ASSAULT]: 12,
			[Stat.ARMOR]: 1
		}
	},
	[Skill.EXPERT_EN_FOUILLE]: {
		id: Skill.EXPERT_EN_FOUILLE,
		name: 'ExpertEnFouille',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21205],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.GROSSE_BEIGNE]: {
		id: Skill.GROSSE_BEIGNE,
		name: 'GrosseBeigne',
		type: SkillType.E,
		energy: Energy.E45,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21207],
		isBaseSkill: false,
		isSphereSkill: true,
		priority: 4,
		probability: 10,
	},
	[Skill.ESPRIT_GORILLOZ]: {
		id: Skill.ESPRIT_GORILLOZ,
		name: 'EspritGorilloz',
		type: SkillType.E,
		energy: Energy.E40,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21311],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 4,
		probability: 20,
	},
	[Skill.LEADER]: {
		id: Skill.LEADER,
		name: 'Leader',
		type: SkillType.U,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21308],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.INGENIEUR]: {
		id: Skill.INGENIEUR,
		name: 'Ingenieur',
		type: SkillType.U,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21304],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.GEANT]: {
		id: Skill.GEANT,
		name: 'Geant',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21303],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WOOD_ASSAULT]: 5,
			[Stat.AIR_ASSAULT]: 5,
			[Stat.FIRE_ASSAULT]: 5,
			[Stat.WATER_ASSAULT]: 5,
			[Stat.LIGHTNING_ASSAULT]: 5,
			[Stat.MAX_HP]: 30,
			[Stat.SPEED]: 1.2,
		}
	},
	[Skill.GARDE_FORESTIER]: {
		id: Skill.GARDE_FORESTIER,
		name: 'GardeForestier',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21307],
		isBaseSkill: false,
		isSphereSkill: false,
	},
	[Skill.ARCHEOLOGUE]: {
		id: Skill.ARCHEOLOGUE,
		name: 'Archeologue',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21302],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.BENEDICTION_DES_FEES]: {
		id: Skill.BENEDICTION_DES_FEES,
		name: 'BenedictionDesFees',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.WOOD, ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11302, 21301, 61121],
		raceId: [raceList.GORILLOZ.raceId, raceList.GORILLOZ_DEMON.raceId],
		isBaseSkill: false,
		isSphereSkill: false
		// TODO: Implement AoE effect
	},
	[Skill.CHOC]: {
		id: Skill.CHOC,
		name: 'Choc',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD, ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21301, 41306, 61119],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WOOD_ASSAULT]: Stat.LIGHTNING_ASSAULT,
			[Stat.LIGHTNING_ASSAULT]: Stat.WOOD_ASSAULT
		}
	},
	[Skill.LOUP_GAROU]: {
		id: Skill.LOUP_GAROU,
		name: 'LoupGarou',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.WOOD, ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21304, 51311, 61121],
		raceId: [raceList.CASTIVORE.raceId],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.COLOSSE]: {
		id: Skill.COLOSSE,
		name: 'Colosse',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21404],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 50,
			[Stat.FIRE_ASSAULT]: 15,
			[Stat.WATER_ASSAULT]: 15,
			[Stat.AIR_ASSAULT]: 15,
			[Stat.LIGHTNING_ASSAULT]: 15,
			[Stat.WOOD_ASSAULT]: 15,
			[Stat.SPEED]: 1.2,
		}
	},
	[Skill.OXYGENATION_MUSCULAIRE]: {
		id: Skill.OXYGENATION_MUSCULAIRE,
		name: 'OxygenationMusculaire',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ENERGY]: 0.2
		}
	},
	[Skill.VERT]: {
		id: Skill.VERT,
		name: 'Vert',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.SOURCE_DE_VIE]: {
		id: Skill.SOURCE_DE_VIE,
		name: 'SourceDeVie',
		type: SkillType.S,
		energy: Energy.E20,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [22101],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.VIDE_ENERGETIQUE]: {
		id: Skill.VIDE_ENERGETIQUE,
		name: 'VideEnergetique',
		type: SkillType.S,
		energy: Energy.E20,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [22101],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.BOUCLIER_DINOZ]: {
		id: Skill.BOUCLIER_DINOZ,
		name: 'BouclierDinoz',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [22102],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 9,
		probability: 10,
	},
	[Skill.ACIDE_LACTIQUE]: {
		id: Skill.ACIDE_LACTIQUE,
		name: 'AcideLactique',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [22102],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ENERGY]: -0.15
		}
	},
	[Skill.LANCER_DE_ROCHE]: {
		id: Skill.LANCER_DE_ROCHE,
		name: 'LancerDeRoche',
		type: SkillType.A,
		energy: Energy.E35,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [22201],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 7,
		probability: 10,
	},
	[Skill.COURBATURES]: {
		id: Skill.COURBATURES,
		name: 'Courbatures',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [22202],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 5,
		probability: 10,
	},
	[Skill.FORCE_CONTROL]: {
		id: Skill.FORCE_CONTROL,
		name: 'ForceControl',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [22203],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.PEAU_DE_FER]: {
		id: Skill.PEAU_DE_FER,
		name: 'PeauDeFer',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [22204],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 50
		}
	},
	[Skill.CHAMPOLLION]: {
		id: Skill.CHAMPOLLION,
		name: 'Champollion',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [22301],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.COURANT_DE_VIE]: {
		id: Skill.COURANT_DE_VIE,
		name: 'CourantDeVie',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [22302],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WATER_DEFENSE]: 20,
			[Stat.WOOD_ASSAULT]: 20
		}
	},
	[Skill.BERSERK]: {
		id: Skill.BERSERK,
		name: 'Berserk',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [22303],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 8,
		probability: 10,
	},
	[Skill.RIVIERE_DE_VIE]: {
		id: Skill.RIVIERE_DE_VIE,
		name: 'RiviereDeVie',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [22304],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.INITIATIVE]: 20
		}
	},
	[Skill.MUR_DE_BOUE]: {
		id: Skill.MUR_DE_BOUE,
		name: 'MurDeBoue',
		type: SkillType.A,
		energy: Energy.E45,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [22401],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 8,
		probability: 5,
	},
	[Skill.PEAU_DACIER]: {
		id: Skill.PEAU_DACIER,
		name: 'PeauDAcier',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [22401],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 100
		}
	},
	[Skill.SHARIGNAN]: {
		id: Skill.SHARIGNAN,
		name: 'Sharignan',
		type: SkillType.E,
		energy: Energy.E45,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [22402],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.AMAZONIE]: {
		id: Skill.AMAZONIE,
		name: 'Amazonie',
		type: SkillType.A,
		energy: Energy.E40,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [22403],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 20,
	},
	[Skill.RECEPTACLE_AQUEUX]: {
		id: Skill.RECEPTACLE_AQUEUX,
		name: 'ReceptacleAqueux',
		type: SkillType.A,
		energy: Energy.E50,
		element: [ElementType.WOOD],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [22404],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 7,
		probability: 15,
	},
	// WATER
	[Skill.CANON_A_EAU]: {
		id: Skill.CANON_A_EAU,
		name: 'CanonAEau',
		type: SkillType.A,
		energy: Energy.E5,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 25,
	},
	[Skill.PERCEPTION]: {
		id: Skill.PERCEPTION,
		name: 'Perception',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WATER_ASSAULT]: 4
		}
	},
	[Skill.MUTATION]: {
		id: Skill.MUTATION,
		name: 'Mutation',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 30
		}
	},
	[Skill.VITALITE]: {
		id: Skill.VITALITE,
		name: 'Vitalite',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: true,
		effects: {
			[Stat.MAX_HP]: 10
		}
	},
	[Skill.GEL]: {
		id: Skill.GEL,
		name: 'Gel',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31101],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 10
	},
	[Skill.DOUCHE_ECOSSAISE]: {
		id: Skill.DOUCHE_ECOSSAISE,
		name: 'DoucheEcossaise',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31101],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 40,
	},
	[Skill.COUP_SOURNOIS]: {
		id: Skill.COUP_SOURNOIS,
		name: 'CoupsSournois',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31102],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 7,
	},
	[Skill.APPRENTI_PECHEUR]: {
		id: Skill.APPRENTI_PECHEUR,
		name: 'ApprentiPecheur',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31102],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.POCHE_VENTRALE]: {
		id: Skill.POCHE_VENTRALE,
		name: 'PocheVentrale',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31103],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.KARATE_SOUS_MARIN]: {
		id: Skill.KARATE_SOUS_MARIN,
		name: 'KarateSousMarin',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31103],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WATER_ASSAULT]: 10
		}
	},
	[Skill.ECAILLES_LUMINESCENTES]: {
		id: Skill.ECAILLES_LUMINESCENTES,
		name: 'EcaillesLuminescentes',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31103],
		raceId: [raceList.QUETZU.raceId],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ARMOR]: 2
		}
	},
	[Skill.MOIGNONS_LIQUIDES]: {
		id: Skill.MOIGNONS_LIQUIDES,
		name: 'MoignonsLiquides',
		type: SkillType.A,
		energy: Energy.E75,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31104],
		isBaseSkill: false,
		isSphereSkill: true,
		priority: 4,
		probability: 8,
	},
	[Skill.ZERO_ABSOLU]: {
		id: Skill.ZERO_ABSOLU,
		name: 'ZeroAbsolu',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31201],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_DEFENSE]: 25
		}
	},
	[Skill.PETRIFICATION]: {
		id: Skill.PETRIFICATION,
		name: 'Petrification',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31201],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 10
	},
	[Skill.ACUPUNCTURE]: {
		id: Skill.ACUPUNCTURE,
		name: 'Acupuncture',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31202],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.SAPEUR]: {
		id: Skill.SAPEUR,
		name: 'Sapeur',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31202],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.COUP_FATAL]: {
		id: Skill.COUP_FATAL,
		name: 'CoupFatal',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31203],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 4,
		probability: 2
	},
	[Skill.ENTRAINEMENT_SOUS_MARIN]: {
		id: Skill.ENTRAINEMENT_SOUS_MARIN,
		name: 'EntrainementSousMarin',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31203],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 10
		}
	},
	[Skill.PECHEUR_CONFIRME]: {
		id: Skill.PECHEUR_CONFIRME,
		name: 'PecheurConfirme',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31204],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.MARECAGE]: {
		id: Skill.MARECAGE,
		name: 'Marecage',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31204],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 6,
		probability: 15
	},
	[Skill.SUMO]: {
		id: Skill.SUMO,
		name: 'Sumo',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31205],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 100
		}
	},
	[Skill.SANS_PITIE]: {
		id: Skill.SANS_PITIE,
		name: 'SansPitie',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31205],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.CLONE_AQUEUX]: {
		id: Skill.CLONE_AQUEUX,
		name: 'CloneAqueux',
		type: SkillType.E,
		energy: Energy.E35,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31206],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 8,
		probability: 15
	},
	[Skill.GRIFFES_EMPOISONNEES]: {
		id: Skill.GRIFFES_EMPOISONNEES,
		name: 'GriffesEmpoisonnees',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31206],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.DELUGE]: {
		id: Skill.DELUGE,
		name: 'Deluge',
		type: SkillType.A,
		energy: Energy.E75,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31208],
		isBaseSkill: false,
		isSphereSkill: true,
		priority: 5,
		probability: 5
	},
	[Skill.PEAU_DE_SERPENT]: {
		id: Skill.PEAU_DE_SERPENT,
		name: 'PeauDeSerpent',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31207],
		raceId: [raceList.QUETZU.raceId],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.EVASION]: 0.1,
			[Stat.WATER_SPEED]: 1.15
		}
	},
	[Skill.RAYON_KAAR_SHER]: {
		id: Skill.RAYON_KAAR_SHER,
		name: 'RayonKaarSher',
		type: SkillType.A,
		energy: Energy.E40,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31302],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 20
	},
	[Skill.MAGASINIER]: {
		id: Skill.MAGASINIER,
		name: 'Magasinier',
		type: SkillType.U,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31304],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ENTRAINEMENT_SOUS_MARIN_AVANCE]: {
		id: Skill.ENTRAINEMENT_SOUS_MARIN_AVANCE,
		name: 'EntrainementSousMarinAvance',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31306],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 20
		}
	},
	[Skill.MAITRE_PECHEUR]: {
		id: Skill.MAITRE_PECHEUR,
		name: 'MaitrePecheur',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31307],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.CUISINIER]: {
		id: Skill.CUISINIER,
		name: 'Cuisinier',
		type: SkillType.U,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31309],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.SANG_ACIDE]: {
		id: Skill.SANG_ACIDE,
		name: 'SangAcide',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31312],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.BULLE]: {
		id: Skill.BULLE,
		name: 'Bulle',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER, ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31304, 51312, 61119],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.INCREVABLE]: {
		id: Skill.INCREVABLE,
		name: 'Increvable',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WOOD, ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31311, 21309, 61119],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_DEFENSE]: 2,
			[Stat.WATER_DEFENSE]: 2,
			[Stat.AIR_DEFENSE]: 2,
			[Stat.LIGHTNING_DEFENSE]: 2,
			[Stat.WOOD_DEFENSE]: 2
		}
	},
	[Skill.ONDINE]: {
		id: Skill.ONDINE,
		name: 'Ondine',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.WATER, ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31310, 31310, 61121],
		raceId: [raceList.SIRAIN.raceId],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.MAITRE_NAGEUR]: {
		id: Skill.MAITRE_NAGEUR,
		name: 'MaitreNageur',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31403],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WATER_ELEMENT]: 5
		}
	},
	[Skill.LEVIATHAN]: {
		id: Skill.LEVIATHAN,
		name: 'Leviathan',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.WATER, ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [31406, 51206, 61121],
		raceId: [raceList.MAHAMUTI.raceId],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.EAU_DIVINE]: {
		id: Skill.EAU_DIVINE,
		name: 'EauDivine',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.HP_REGEN]: ['x', 2]
		}
	},
	[Skill.RADIATIONS_GAMMA]: {
		id: Skill.RADIATIONS_GAMMA,
		name: 'RadiationsGamma',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [32101],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 30,
			[Stat.INITIATIVE]: -10,
			[Stat.FIRE_ASSAULT]: 5,
			[Stat.WATER_ASSAULT]: 5,
			[Stat.AIR_ASSAULT]: 5,
			[Stat.LIGHTNING_ASSAULT]: 5,
			[Stat.WOOD_ASSAULT]: 5
		}
	},
	[Skill.BLEU]: {
		id: Skill.BLEU,
		name: 'Bleu',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [32101],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.MUE_ACQUEUSE]: {
		id: Skill.MUE_ACQUEUSE,
		name: 'MueAcqueuse',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [32201],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.LIGHTNING_DEFENSE]: 20
		}
	},
	[Skill.CARAPACE_BLINDEE]: {
		id: Skill.CARAPACE_BLINDEE,
		name: 'CarapaceBlindee',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [32201],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ARMOR]: 10,
			[Stat.SPEED]: 1.2,
		}
	},
	[Skill.DIETE_CHROMATIQUE]: {
		id: Skill.DIETE_CHROMATIQUE,
		name: 'DieteChromatique',
		type: SkillType.E,
		energy: Energy.E45,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [32202],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 8,
		probability: 15
	},
	[Skill.EFFLUVE_APHRODISIAQUE]: {
		id: Skill.EFFLUVE_APHRODISIAQUE,
		name: 'EffluveAphrodisiaque',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [32301],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_FOLLOWERS]: 1
		}
	},
	[Skill.NEMO]: {
		id: Skill.NEMO,
		name: 'Nemo',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [32301],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.CLEPTOMANE]: {
		id: Skill.CLEPTOMANE,
		name: 'Cleptomane',
		type: SkillType.P,
		energy: Energy.E45,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [32302],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ABYSSE]: {
		id: Skill.ABYSSE,
		name: 'Abysse',
		type: SkillType.A,
		energy: Energy.E35,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [32303],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 20,
	},
	[Skill.BANNI_DES_DIEUX]: {
		id: Skill.BANNI_DES_DIEUX,
		name: 'BanniDesDieux',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [32303],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 8,
		probability: 10,
	},
	[Skill.TOURBILLON_MAGIQUE]: {
		id: Skill.TOURBILLON_MAGIQUE,
		name: 'TourbillonMagique',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [32401],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WATER_ASSAULT]: 20
		}
	},
	[Skill.HYPERVENTILATION]: {
		id: Skill.HYPERVENTILATION,
		name: 'Hyperventilation',
		type: SkillType.A,
		energy: Energy.E55,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [32402],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 8,
		probability: 15,
	},
	[Skill.THERAPIE_DE_GROUPE]: {
		id: Skill.THERAPIE_DE_GROUPE,
		name: 'TherapieDeGroupe',
		type: SkillType.E,
		energy: Energy.E55,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [32403],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.RECEPTACLE_TESLA]: {
		id: Skill.RECEPTACLE_TESLA,
		name: 'ReceptacleTesla',
		type: SkillType.A,
		energy: Energy.E45,
		element: [ElementType.WATER],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [32404],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 7,
		probability: 15,
	},
	[Skill.VITALITE_MARINE]: {
		id: Skill.VITALITE_MARINE,
		name: 'VitaliteMarine',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [32405],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 80
		}
	},
	// LIGHTNING
	[Skill.INTELLIGENCE]: {
		id: Skill.INTELLIGENCE,
		name: 'Intelligence',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.FOCUS]: {
		id: Skill.FOCUS,
		name: 'Focus',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 30
	},
	[Skill.CELERITE]: {
		id: Skill.CELERITE,
		name: 'Celerite',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.SPEED]: 0.85,
		}
	},
	[Skill.REFLEX]: {
		id: Skill.REFLEX,
		name: 'Reflex',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: true,
		effects: {
			[Stat.INITIATIVE]: 5
		}
	},
	[Skill.CONCENTRATION]: {
		id: Skill.CONCENTRATION,
		name: 'Concentration',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41102],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ATTAQUE_ECLAIR]: {
		id: Skill.ATTAQUE_ECLAIR,
		name: 'AttaqueEclair',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41103],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.LIGHTNING_SPEED]: 0.6
		}
	},
	[Skill.PARATONNERRE]: {
		id: Skill.PARATONNERRE,
		name: 'Paratonnerre',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41101],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.COUP_DOUBLE]: {
		id: Skill.COUP_DOUBLE,
		name: 'CoupDouble',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41103],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MULTIHIT]: 0.2
		}
	},
	[Skill.REGENERESCENCE]: {
		id: Skill.REGENERESCENCE,
		name: 'Regenerescence',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41102],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.HP_REGEN]: 2
		}
	},
	[Skill.PREMIERS_SOINS]: {
		id: Skill.PREMIERS_SOINS,
		name: 'PremiersSoins',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41101],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ECLAIR_SINUEUX]: {
		id: Skill.ECLAIR_SINUEUX,
		name: 'EclairSinueux',
		type: SkillType.A,
		energy: Energy.E50,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41104],
		isBaseSkill: false,
		isSphereSkill: true,
		priority: 3,
		probability: 10
	},
	[Skill.FOUDRE]: {
		id: Skill.FOUDRE,
		name: 'Foudre',
		type: SkillType.A,
		energy: Energy.E25,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41204],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 4,
		probability: 10
	},
	[Skill.FISSION_ELEMENTAIRE]: {
		id: Skill.FISSION_ELEMENTAIRE,
		name: 'FissionElementaire',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41203],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.VOIE_DE_KAOS]: {
		id: Skill.VOIE_DE_KAOS,
		name: 'VoieDeKaos',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41201],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_ASSAULT]: 6,
			[Stat.LIGHTNING_ASSAULT]: 6
		}
	},
	[Skill.PLAN_DE_CARRIERE]: {
		id: Skill.PLAN_DE_CARRIERE,
		name: 'PlanDeCarriere',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41204],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ADRENALINE]: {
		id: Skill.ADRENALINE,
		name: 'Adrenaline',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41206],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.LIGHTNING_SPEED]: 0.5
		}
	},
	[Skill.VOIE_DE_GAIA]: {
		id: Skill.VOIE_DE_GAIA,
		name: 'VoieDeGaia',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41201],
		isBaseSkill: false,
		isSphereSkill: false,
		globalEffects: {
			[Stat.WOOD_DEFENSE]: 3,
			[Stat.LIGHTNING_DEFENSE]: 3
		}
	},
	[Skill.MEDECINE]: {
		id: Skill.MEDECINE,
		name: 'Medecine',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41206],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.DANSE_FOUDROYANTE]: {
		id: Skill.DANSE_FOUDROYANTE,
		name: 'DanseFoudroyante',
		type: SkillType.A,
		energy: Energy.E35,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41204],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 10
	},
	[Skill.EMBUCHE]: {
		id: Skill.EMBUCHE,
		name: 'Embuche',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41202],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.INITIATIVE]: 7
		}
	},
	[Skill.PUREE_SALVATRICE]: {
		id: Skill.PUREE_SALVATRICE,
		name: 'PureeSalvatrice',
		type: SkillType.E,
		energy: Energy.E45,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41205],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 15

	},
	[Skill.AURA_HERMETIQUE]: {
		id: Skill.AURA_HERMETIQUE,
		name: 'AuraHermetique',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41205],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 1,
		probability: 30
	},
	[Skill.CROCS_DIAMANT]: {
		id: Skill.CROCS_DIAMANT,
		name: 'CrocsDiamant',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41203],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_ASSAULT]: 2,
			[Stat.WOOD_ASSAULT]: 2,
			[Stat.LIGHTNING_ASSAULT]: 2,
			[Stat.WATER_ASSAULT]: 2,
			[Stat.AIR_ASSAULT]: 2
		}
	},
	[Skill.SURVIE]: {
		id: Skill.SURVIE,
		name: 'Survie',
		type: SkillType.S,
		energy: Energy.E75,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41207],
		isBaseSkill: false,
		isSphereSkill: true
	},
	[Skill.AUBE_FEUILLUE]: {
		id: Skill.AUBE_FEUILLUE,
		name: 'AubeFeuillue',
		type: SkillType.A,
		energy: Energy.E65,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41306],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 10
	},
	[Skill.BRANCARDIER]: {
		id: Skill.BRANCARDIER,
		name: 'Brancardier',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41307],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.BENEDICTION]: {
		id: Skill.BENEDICTION,
		name: 'Benediction',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41310],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 25
	},
	[Skill.CREPUSCULE_FLAMBOYANT]: {
		id: Skill.CREPUSCULE_FLAMBOYANT,
		name: 'CrepusculeFlambloyant',
		type: SkillType.A,
		energy: Energy.E40,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41303],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 5
	},
	[Skill.MARCHAND]: {
		id: Skill.MARCHAND,
		name: 'Marchand',
		type: SkillType.U,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41302],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.REINCARNATION]: {
		id: Skill.REINCARNATION,
		name: 'Reincarnation',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41304],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.SURCHARGE]: {
		id: Skill.SURCHARGE,
		name: 'Surcharge',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING, ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51302, 41305, 61119],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MULTIHIT]: 0.15
		}
	},
	[Skill.ELECTROLYSE]: {
		id: Skill.ELECTROLYSE,
		name: 'Electrolyse',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.WATER, ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41301, 31308, 61119],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.GOLEM]: {
		id: Skill.GOLEM,
		name: 'Golem',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.LIGHTNING, ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41302, 11309, 61121],
		raceId: [raceList.ROCKY.raceId],
		isBaseSkill: false,
		isSphereSkill: false
		// TODO: Implement AoE effect
	},
	[Skill.RAIJIN]: {
		id: Skill.RAIJIN,
		name: 'Raijin',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.LIGHTNING, ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41301, 51302, 61121],
		raceId: [raceList.PLANAILLE.raceId, raceList.PLANAILLE_DEMON.raceId],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.QUETZACOATL]: {
		id: Skill.QUETZACOATL,
		name: 'Quetzacoatl',
		type: SkillType.I,
		energy: Energy.E50,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41301],
		raceId: [raceList.QUETZU.raceId],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 4,
		probability: 10
	},
	[Skill.ROI_DES_SINGES]: {
		id: Skill.ROI_DES_SINGES,
		name: 'RoiDesSinges',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.LIGHTNING, ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21308, 41308, 61121],
		raceId: [raceList.TOUFUFU.raceId],
		isBaseSkill: false,
		isSphereSkill: false
		// TODO: Implement AoE effect
	},
	[Skill.ARCHANGE_CORROSIF]: {
		id: Skill.ARCHANGE_CORROSIF,
		name: 'ArchangeCorrosif',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41404],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_ELEMENT]: 2,
			[Stat.LIGHTNING_ELEMENT]: 1
		}
	},
	[Skill.ARCHANGE_GENESIF]: {
		id: Skill.ARCHANGE_GENESIF,
		name: 'ArchangeGenesif',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41401],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.WOOD_ELEMENT]: 2,
			[Stat.LIGHTNING_ELEMENT]: 1
		}
	},
	[Skill.PRETRE]: {
		id: Skill.PRETRE,
		name: 'Pretre',
		type: SkillType.U,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41403],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.SOUTIEN_MORAL]: {
		id: Skill.SOUTIEN_MORAL,
		name: 'SoutienMoral',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ENERGY]: 0.1
		}
	},
	[Skill.STIMULATION_CARDIAQUE]: {
		id: Skill.STIMULATION_CARDIAQUE,
		name: 'StimulationCardiaque',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [42101],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ENERGY_RECOVERY]: 0.2
		}
	},
	[Skill.JAUNE]: {
		id: Skill.JAUNE,
		name: 'Jaune',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [42101],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.MORSURE_DU_SOLEIL]: {
		id: Skill.MORSURE_DU_SOLEIL,
		name: 'MorsureDuSoleil',
		type: SkillType.E,
		energy: Energy.E30,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [42201],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 7,
		probability: 15
	},
	[Skill.CRAMPE_CHRONIQUE]: {
		id: Skill.CRAMPE_CHRONIQUE,
		name: 'CrampeChronique',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [42202],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 7,
		probability: 10
	},
	[Skill.BATTERIE_SUPPLEMENTAIRE]: {
		id: Skill.BATTERIE_SUPPLEMENTAIRE,
		name: 'BatterieSupplementaire',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [42301],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.MAX_HP]: 50,
			[Stat.INITIATIVE]: -0.15
		}
	},
	[Skill.EINSTEIN]: {
		id: Skill.EINSTEIN,
		name: 'Einstein',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [42301],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.BARRIERE_ELECTRIFIEE]: {
		id: Skill.BARRIERE_ELECTRIFIEE,
		name: 'BarriereElectrifiee',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [42303],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.AIR_DEFENSE]: 20
		}
	},
	[Skill.ORACLE]: {
		id: Skill.ORACLE,
		name: 'Oracle',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [42303],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.RECEPTACLE_AERIEN]: {
		id: Skill.RECEPTACLE_AERIEN,
		name: 'ReceptacleAerien',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [42401],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 7,
		probability: 15
	},
	[Skill.FEU_DE_ST_ELME]: {
		id: Skill.FEU_DE_ST_ELME,
		name: 'FeuDeStElme',
		type: SkillType.A,
		energy: Energy.E40,
		element: [ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [42402],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 20,
	},
	[Skill.FORCE_DE_ZEUS]: {
		id: Skill.FORCE_DE_ZEUS,
		name: 'ForceDeZeus',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [42403],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.LIGHTNING_ASSAULT]: 20
		}
	},
	[Skill.REMANENCE_HERTZIENNE]: {
		id: Skill.REMANENCE_HERTZIENNE,
		name: 'RemanenceHertzienne',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.LIGHTNING],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [42404],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.EVASION]: 0.2
		}
	},
	[Skill.AGILITE]: {
		id: Skill.AGILITE,
		name: 'Agilite',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.AIR_ASSAULT]: 5
		}
	},
	[Skill.STRATEGIE]: {
		id: Skill.STRATEGIE,
		name: 'Strategie',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.MISTRAL]: {
		id: Skill.MISTRAL,
		name: 'Mistral',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.AIGUILLON]: {
		id: Skill.AIGUILLON,
		name: 'Aiguillon',
		type: SkillType.E,
		energy: Energy.E50,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: true
	},
	[Skill.ENVOL]: {
		id: Skill.ENVOL,
		name: 'Envol',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [],
		raceId: [
			raceList.PTEROZ.raceId,
			raceList.PLANAILLE.raceId,
			raceList.PLANAILLE_DEMON.raceId,
			raceList.NUAGOZ.raceId,
			raceList.SOUFFLET.raceId
		],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ESQUIVE]: {
		id: Skill.ESQUIVE,
		name: 'Esquive',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51101],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.EVASION]: 0.1
		}
	},
	[Skill.SAUT]: {
		id: Skill.SAUT,
		name: 'Saut',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51101],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ANALYSE]: {
		id: Skill.ANALYSE,
		name: 'Analyse',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51102],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.CUEILLETTE]: {
		id: Skill.CUEILLETTE,
		name: 'Cueillette',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51102],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.TAICHI]: {
		id: Skill.TAICHI,
		name: 'TaiChi',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51103],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.AIR_ASSAULT]: 15,
			[Stat.AIR_SPEED]: 1.2
		}
	},
	[Skill.TORNADE]: {
		id: Skill.TORNADE,
		name: 'Tornade',
		type: SkillType.A,
		energy: Energy.E25,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51103],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.AURA_PUANTE]: {
		id: Skill.AURA_PUANTE,
		name: 'AuraPuante',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51104],
		isBaseSkill: false,
		isSphereSkill: true
	},
	[Skill.DISQUE_VACUUM]: {
		id: Skill.DISQUE_VACUUM,
		name: 'DisqueVacuum',
		type: SkillType.A,
		energy: Energy.E50,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51201],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ELASTICITE]: {
		id: Skill.ELASTICITE,
		name: 'Elasticite',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51201],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.AIR_ASSAULT]: 10
		},
		globalEffects: {
			[Stat.AIR_DEFENSE]: 3
		}
	},
	[Skill.ATTAQUE_PLONGEANTE]: {
		id: Skill.ATTAQUE_PLONGEANTE,
		name: 'AttaquePlongeante',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51202],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.FURTIVITE]: {
		id: Skill.FURTIVITE,
		name: 'Furtivite',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51202],
		isBaseSkill: false,
		isSphereSkill: false,
		globalEffects: {
			[Stat.AIR_DEFENSE]: 2,
			[Stat.WATER_DEFENSE]: 2,
			[Stat.LIGHTNING_DEFENSE]: 2
		}
	},
	[Skill.SPECIALISTE]: {
		id: Skill.SPECIALISTE,
		name: 'Specialiste',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51203],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.TALON_DACHILLE]: {
		id: Skill.TALON_DACHILLE,
		name: 'TalonDAchille',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51203],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_ASSAULT]: 2,
			[Stat.AIR_ASSAULT]: 2,
			[Stat.WOOD_ASSAULT]: 2,
			[Stat.WATER_ASSAULT]: 2,
			[Stat.LIGHTNING_ASSAULT]: 2
		}
	},
	[Skill.NUAGE_TOXIQUE]: {
		id: Skill.NUAGE_TOXIQUE,
		name: 'NuageToxique',
		type: SkillType.A,
		energy: Energy.E50,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51204],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.OEIL_DE_LYNX]: {
		id: Skill.OEIL_DE_LYNX,
		name: 'OeilDeLynx',
		type: SkillType.C,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51204],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.EVEIL]: {
		id: Skill.EVEIL,
		name: 'Eveil',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51205],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.AIR_SPEED]: 1.2
		}
	},
	[Skill.PAUME_EJECTABLE]: {
		id: Skill.PAUME_EJECTABLE,
		name: 'PaumeEjectable',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51205],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.VENT_VIF]: {
		id: Skill.VENT_VIF,
		name: 'VentVif',
		type: SkillType.E,
		energy: Energy.E25,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51206],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.FORME_VAPOREUSE]: {
		id: Skill.FORME_VAPOREUSE,
		name: 'FormeVaporeuse',
		type: SkillType.S,
		energy: Energy.E25,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51206],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.HYPNOSE]: {
		id: Skill.HYPNOSE,
		name: 'Hypnose',
		type: SkillType.A,
		energy: Energy.E50,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51207],
		isBaseSkill: false,
		isSphereSkill: true,
		priority: 7,
		probability: 5,
	},
	[Skill.SECOUSSE]: {
		id: Skill.SECOUSSE,
		name: 'Secousse',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.WOOD, ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51310, 21304, 61119],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.TROU_NOIR]: {
		id: Skill.TROU_NOIR,
		name: 'TrouNoir',
		type: SkillType.A,
		energy: Energy.E60,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51301],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 10,
		probability: 3,
	},
	[Skill.MAITRE_LEVITATEUR]: {
		id: Skill.MAITRE_LEVITATEUR,
		name: 'MaitreLevitateur',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51303],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.HALEINE_FETIVE]: {
		id: Skill.HALEINE_FETIVE,
		name: 'HaleineFetive',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51307],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.MEDITATION_SOLITAIRE]: {
		id: Skill.MEDITATION_SOLITAIRE,
		name: 'MeditationSolitaire',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51309],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.AIR_SPEED]: 1.5
		},
		globalEffects: {
			[Stat.AIR_DEFENSE]: 3
		}
	},
	[Skill.PROFESSEUR]: {
		id: Skill.PROFESSEUR,
		name: 'Professeur',
		type: SkillType.U,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51309],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.SOUFFLE_DE_VIE]: {
		id: Skill.SOUFFLE_DE_VIE,
		name: 'SouffleDeVie',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51311],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.TOTEM_ANCESTRAL_AEROPORTE]: {
		id: Skill.TOTEM_ANCESTRAL_AEROPORTE,
		name: 'TotemAncestralAeroporte',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.AIR, ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11311, 51309, 61121],
		raceId: [raceList.KABUKI.raceId, raceList.KABUKI_DEMON.raceId],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.FUJIN]: {
		id: Skill.FUJIN,
		name: 'Fujin',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.AIR, ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41308, 51301, 61121],
		raceId: [raceList.NUAGOZ.raceId],
		isBaseSkill: false,
		isSphereSkill: false
		// TODO: Implement AoE effect
	},
	[Skill.MEDITATION_TRANCHANTE]: {
		id: Skill.MEDITATION_TRANCHANTE,
		name: 'MeditationTranchante',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51404],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.AIR_SPEED]: 1.5
		},
		globalEffects: {
			[Stat.AIR_DEFENSE]: 6
		}
	},
	[Skill.DJINN]: {
		id: Skill.DJINN,
		name: 'Djinn',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.AIR, ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [11201, 51403, 61121],
		raceId: [raceList.PTEROZ.raceId],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.HADES]: {
		id: Skill.HADES,
		name: 'Hades',
		type: SkillType.I,
		energy: Energy.E60,
		element: [ElementType.AIR, ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51403, 21204, 31203, 61121],
		raceId: [raceList.SANTAZ.raceId],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 4,
		probability: 10
	},
	[Skill.FORME_ETHERALE]: {
		id: Skill.FORME_ETHERALE,
		name: 'FormeEtherale',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51501],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.MAITRISE_CORPORELLE]: {
		id: Skill.MAITRISE_CORPORELLE,
		name: 'MaitriseCorporelle',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ENERGY_RECOVERY]: 0.25
		}
	},
	[Skill.BLANC]: {
		id: Skill.BLANC,
		name: 'Blanc',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [52101],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.ANAEROBIE]: {
		id: Skill.ANAEROBIE,
		name: 'Anaerobie',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [52101],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ENERGY]: -0.25
		}
	},
	[Skill.DOUBLE_FACE]: {
		id: Skill.DOUBLE_FACE,
		name: 'DoubleFace',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [52201],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.FLAGELLATION]: {
		id: Skill.FLAGELLATION,
		name: 'Flagellation',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [52201],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ENERGY_RECOVERY]: -0.15
		}
	},
	[Skill.SOUFFLE_DANGE]: {
		id: Skill.SOUFFLE_DANGE,
		name: 'SouffleDange',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [52202],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_DEFENSE]: 20
		}
	},
	[Skill.OURAGAN]: {
		id: Skill.OURAGAN,
		name: 'Ouragan',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [52202],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.AIR_ASSAULT]: 20
		}
	},
	[Skill.OURANOS]: {
		id: Skill.OURANOS,
		name: 'Ouranos',
		type: SkillType.A,
		energy: Energy.E45,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [52301],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 3,
		probability: 20,
	},
	[Skill.TWINOID_500MG]: {
		id: Skill.TWINOID_500MG,
		name: 'Twinoid500mg',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [52302],
		isBaseSkill: false,
		isSphereSkill: false,
		effects: {
			[Stat.ENERGY]: 0.5
		}
	},
	[Skill.LONDUHAUT]: {
		id: Skill.LONDUHAUT,
		name: 'LonDuhaut',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [52303],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.SURPLIS_DHADES]: {
		id: Skill.SURPLIS_DHADES,
		name: 'SurplisDhades',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [52304],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.RECEPTABLE_THERMIQUE]: {
		id: Skill.RECEPTABLE_THERMIQUE,
		name: 'ReceptacleThermique',
		type: SkillType.A,
		energy: Energy.E45,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [52304],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 7,
		probability: 15,
	},
	[Skill.QI_GONG]: {
		id: Skill.QI_GONG,
		name: 'QiGong',
		type: SkillType.E,
		energy: Energy.E55,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [52401],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.SYLPHIDES]: {
		id: Skill.SYLPHIDES,
		name: 'Sylphides',
		type: SkillType.A,
		energy: Energy.E65,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [52402],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 10,
		probability: 10,
	},
	[Skill.MESSIE]: {
		id: Skill.MESSIE,
		name: 'Messie',
		type: SkillType.U,
		energy: Energy.NONE,
		element: [ElementType.AIR],
		activatable: false,
		tree: SkillTree.ETHER,
		unlockedFrom: [52403],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.MUTINERIE]: {
		id: Skill.MUTINERIE,
		name: 'Mutinerie',
		type: SkillType.E,
		energy: Energy.E40,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [52405],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 10,
		probability: 10,
	},
	[Skill.MAINS_COLLANTES]: {
		id: Skill.MAINS_COLLANTES,
		name: 'MainsCollantes',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.AIR],
		activatable: true,
		tree: SkillTree.ETHER,
		unlockedFrom: [52404],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 10,
		probability: 15,
	},
	[Skill.COMPETENCE_DOUBLE]: {
		id: Skill.COMPETENCE_DOUBLE,
		name: 'CompetenceDouble',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.LIMITE_BRISEE]: {
		id: Skill.LIMITE_BRISEE,
		name: 'LimiteBrisee',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.INVOCATEUR]: {
		id: Skill.INVOCATEUR,
		name: 'Invocateur',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.FRENESIE_COLLECTIVE]: {
		id: Skill.FRENESIE_COLLECTIVE,
		name: 'FrenesieCollective',
		type: SkillType.E,
		energy: Energy.E20,
		element: [ElementType.VOID],
		activatable: true,
		tree: SkillTree.VANILLA,
		raceId: [raceList.WANWAN_DEMON.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.COQUE]: {
		id: Skill.COQUE,
		name: 'Coque',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.WINKS.raceId],
		isBaseSkill: true,
		isSphereSkill: false,
		effects: {
			[Stat.ARMOR]: 1
		}
	},
	[Skill.CHARGE_CORNUE]: {
		id: Skill.CHARGE_CORNUE,
		name: 'ChargeCornue',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.PIGMOU.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.ROCK]: {
		id: Skill.ROCK,
		name: 'Rock',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: true,
		tree: SkillTree.VANILLA,
		raceId: [raceList.ROCKY.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.PIETINEMENT]: {
		id: Skill.PIETINEMENT,
		name: 'Pietinement',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.SANTAZ.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.CUIRASSE]: {
		id: Skill.CUIRASSE,
		name: 'Cuirasse',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.FEROSS.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.INSAISISSABLE]: {
		id: Skill.INSAISISSABLE,
		name: 'Insaisissable',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.KABUKI.raceId, raceList.KABUKI_DEMON.raceId],
		isBaseSkill: true,
		isSphereSkill: false,
		effects: {
			[Stat.EVASION]: 0.1
		}
	},
	[Skill.DEPLACEMENT_INSTANTANE]: {
		id: Skill.DEPLACEMENT_INSTANTANE,
		name: 'DeplacementInstantane',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.TOUFUFU.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.NAPOMAGICIEN]: {
		id: Skill.NAPOMAGICIEN,
		name: 'Napomagicien',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.SOUFFLET.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.GROS_COSTAUD]: {
		id: Skill.GROS_COSTAUD,
		name: 'GrosCostaud',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.GORILLOZ_DEMON.raceId],
		isBaseSkill: true,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_ASSAULT]: 6,
			[Stat.WOOD_ASSAULT]: 6,
			[Stat.WATER_ASSAULT]: 6,
			[Stat.LIGHTNING_ASSAULT]: 6,
			[Stat.AIR_ASSAULT]: 6
		}
	},
	[Skill.ORIGINE_CAUSHEMESHENNE]: {
		id: Skill.ORIGINE_CAUSHEMESHENNE,
		name: 'OrigineCaushemeshenne',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.KABUKI_DEMON.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.ECRASEMENT]: {
		id: Skill.ECRASEMENT,
		name: 'Ecrasement',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.VOID],
		activatable: true,
		tree: SkillTree.VANILLA,
		raceId: [raceList.MAHAMUTI.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.FORCE_DE_LUMIERE]: {
		id: Skill.FORCE_DE_LUMIERE,
		name: 'ForceDeLumiere',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.MOUEFFE_DEMON.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.CHARGE_PIGMOU]: {
		id: Skill.CHARGE_PIGMOU,
		name: 'ChargePigmou',
		type: SkillType.A,
		energy: Energy.E20,
		element: [ElementType.VOID],
		activatable: true,
		tree: SkillTree.VANILLA,
		raceId: [raceList.PIGMOU_DEMON.raceId],
		isBaseSkill: true,
		isSphereSkill: false
	},
	[Skill.FORCE_DES_TENEBRES]: {
		id: Skill.FORCE_DES_TENEBRES,
		name: 'ForceDesTenebres',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.PLANAILLE_DEMON.raceId],
		isBaseSkill: true,
		isSphereSkill: false,
		effects: {
			[Stat.ENERGY]: 0.25,
			[Stat.ENERGY_RECOVERY]: 0.25
		}
	},
	[Skill.BIGMAGNON]: {
		id: Skill.BIGMAGNON,
		name: 'Bigmagnon',
		type: SkillType.S,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.TRICERAGNON.raceId],
		isBaseSkill: true,
		isSphereSkill: false,
		priority: 8,
		probability: 15,
	},
	[Skill.DUR_A_CUIRE]: {
		id: Skill.DUR_A_CUIRE,
		name: 'DurACuire',
		type: SkillType.P,
		energy: Energy.NONE,
		element: [ElementType.VOID],
		activatable: false,
		tree: SkillTree.VANILLA,
		raceId: [raceList.WINKS_DEMON.raceId],
		isBaseSkill: true,
		isSphereSkill: false,
		effects: {
			[Stat.FIRE_DEFENSE]: 6,
			[Stat.WOOD_DEFENSE]: 6,
			[Stat.WATER_DEFENSE]: 6,
			[Stat.LIGHTNING_DEFENSE]: 6,
			[Stat.AIR_DEFENSE]: 6
		}
	},
	[Skill.HERCOLUBUS]: {
		id: Skill.HERCOLUBUS,
		name: 'Hercolubus',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.LIGHTNING, ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41501, 51312, 61121],
		raceId: [raceList.SMOG.raceId],
		isBaseSkill: false,
		isSphereSkill: false
	},
	[Skill.REINE_DE_LA_RUCHE]: {
		id: Skill.REINE_DE_LA_RUCHE,
		name: 'ReineDeLaRuche',
		type: SkillType.I,
		energy: Energy.E50,
		element: [ElementType.AIR, ElementType.WOOD],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [51405, 51311, 61121],
		raceId: [raceList.SOUFFLET.raceId],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 4,
		probability: 10,
	},
	[Skill.BIG_MAMA]: {
		id: Skill.BIG_MAMA,
		name: 'BigMama',
		type: SkillType.I,
		energy: Energy.E50,
		element: [ElementType.WOOD, ElementType.FIRE],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [12502, 22504, 61121],
		raceId: [raceList.TRICERAGNON.raceId],
		isBaseSkill: false,
		isSphereSkill: false,
		priority: 6,
		probability: 15,
	},
	[Skill.YGGDRASIL]: {
		id: Skill.YGGDRASIL,
		name: 'Yggdrasil',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.WOOD, ElementType.AIR],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [21405, 51204],
		raceId: [raceList.WANWAN.raceId, raceList.WANWAN_DEMON.raceId],
		isBaseSkill: false,
		isSphereSkill: false
		// TODO: Implement AoE effect
	},
	[Skill.BALEINE_BLANCHE]: {
		id: Skill.BALEINE_BLANCHE,
		name: 'BaleineBlanche',
		type: SkillType.I,
		energy: Energy.E75,
		element: [ElementType.WATER, ElementType.LIGHTNING],
		activatable: true,
		tree: SkillTree.VANILLA,
		unlockedFrom: [41305, 31404],
		raceId: [raceList.WINKS.raceId, raceList.WINKS_DEMON.raceId],
		isBaseSkill: false,
		isSphereSkill: false
		// TODO: Implement AoE effect
	}
};
