
# Main secret key. This key is used to derive all the secrets used to protect the tokens generated
# by the website and encrypted database columns.

# Main configuration for the backend system of Eternaltwin
[backend]
# HTTP port for the server backend (REST API and action handlers)
listen = "127.0.0.1:50320"

# Secret key used for encryption and signatures
secret = "dev"

# Data store implementation to use
# - `Memory`: Keep all data in memory (RAM). Allows to start Eternaltwin without
#   a database, but data is lost on restart.
# - `Postgres`: Store data in a Postgres databse. Further configuration in the
#   the section `postgres`.
# `backend.store` expands to apply to all backend stores. You can also set
# the implementation type for each store explicitly.
store = "Postgres"

# Frontend configuration
[frontend]
# HTTP port for the frontend. This applies to the Node server performing Server
# Side Rendering.
# Setting it automatically updates `frontend.uri` to be
# `http://localhost:{port}/`.
port = 50321

# External URL where Eternaltwin is accessible from.
uri = "http://localhost:50321/"

# Default number of posts to display in a forum thread page
forum_posts_per_page = 10

# Default number of threads to display in a forum section page
forum_threads_per_page = 20

# Postgres database configuration
# Used by the `Postgres` stores configured in the `backend` section.
[postgres]
# Database service host
host = "localhost"
# Database service port
port = 5432
# Database name
name = "etwin.dev"
# Database user (role) for regular runtime.
user = "etwin.dev.write"
# Password for the database user.
password = "EternalDinoSQL"


[opentelemetry]
enabled = true
